In [5]:
%pip install requests
%pip install pandas

Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.4 MB/s eta 0:00:00 MB/s eta 0:00:01
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 10.5 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 13.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
#@title Imports
from IPython.core.display import json
import requests
import pandas as pd
import time
import datetime
import json
import os

In [2]:
topPlayers = pd.read_csv('topPlayers.csv')
topPlayers

,account_id,steamid,avatar,avatarmedium,avatarfull,profileurl,personaname,last_login,full_history_time,cheese,...,rank_tier_time,name,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,1111506,7.656120e+16,https://avatars.steamstatic.com/8c540801f27f13...,https://avatars.steamstatic.com/8c540801f27f13...,https://avatars.steamstatic.com/8c540801f27f13...,https://steamcommunity.com/id/Line/,LineDOTA2,2026-02-16T09:18:34.196Z,2026-01-20T09:07:01.351Z,0.0,...,2026-06-07T18:45:10.966Z,LINE,us,2.0,9885271.0,TRIES,TRIES,NaN,NaN,NaN
1,1296625,7.656120e+16,https://avatars.steamstatic.com/2db6b65f1ba032...,https://avatars.steamstatic.com/2db6b65f1ba032...,https://avatars.steamstatic.com/2db6b65f1ba032...,https://steamcommunity.com/id/Newsham/,Newsham,2025-10-23T08:31:29.662Z,2026-05-22T18:28:46.036Z,0.0,...,2026-05-22T18:28:42.508Z,Newsham,NaN,2.0,8944221.0,Fart Studios,FRT,True,True,NaN
2,2029214,7.656120e+16,https://avatars.steamstatic.com/c26f88d781e1a2...,https://avatars.steamstatic.com/c26f88d781e1a2...,https://avatars.steamstatic.com/c26f88d781e1a2...,https://steamcommunity.com/id/shindvqq/,АНИМЕ ПСИХОЗ,2024-04-18T15:33:18.532Z,2026-04-08T13:09:41.476Z,0.0,...,2026-04-14T08:57:16.501Z,Shindaqq,ax,1.0,9928877.0,SHADOW GOVERNMENT,SG,NaN,NaN,NaN
3,2503633,7.656120e+16,https://avatars.steamstatic.com/a717da8d029408...,https://avatars.steamstatic.com/a717da8d029408...,https://avatars.steamstatic.com/a717da8d029408...,https://steamcommunity.com/profiles/7656119796...,是打不过啊,NaN,2026-05-02T17:29:26.601Z,0.0,...,2026-06-03T16:05:26.587Z,还不错,NaN,0.0,9717978.0,bilibili,bilibili,NaN,NaN,NaN
4,3035021,7.656120e+16,https://avatars.steamstatic.com/c63bb771a7cec4...,https://avatars.steamstatic.com/c63bb771a7cec4...,https://avatars.steamstatic.com/c63bb771a7cec4...,https://steamcommunity.com/id/Snoowiee/,Snowie,NaN,2026-05-22T20:07:17.282Z,0.0,...,2026-05-22T20:07:17.394Z,Snowie,NaN,0.0,9531587.0,SOG,SOG,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4471,1927313273,7.656120e+16,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://steamcommunity.com/profiles/7656119988...,linglaiofficial,NaN,2026-02-26T05:54:51.639Z,0.0,...,2026-05-18T07:00:45.548Z,Linglai,cn,1.0,9855678.0,This Not Smurf,Smurf,NaN,NaN,NaN
4472,1928064793,7.656120e+16,https://avatars.steamstatic.com/c56aa36c56064c...,https://avatars.steamstatic.com/c56aa36c56064c...,https://avatars.steamstatic.com/c56aa36c56064c...,https://steamcommunity.com/profiles/7656119988...,наруто,NaN,2026-04-19T11:59:29.690Z,0.0,...,2026-04-26T02:11:57.231Z,67,NaN,2.0,10142777.0,TeamPidors2010,PidrTeam,NaN,NaN,NaN
4473,1929726323,7.656120e+16,https://avatars.steamstatic.com/bdee3be4086251...,https://avatars.steamstatic.com/bdee3be4086251...,https://avatars.steamstatic.com/bdee3be4086251...,https://steamcommunity.com/id/kyowadoto/,Kane`,NaN,2026-04-24T15:09:19.677Z,0.0,...,2026-05-11T01:21:13.895Z,Kyowa,pe,1.0,10041049.0,Awa Team,LFT,NaN,NaN,NaN
4474,1930115322,7.656120e+16,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://steamcommunity.com/profiles/7656119989...,прив,NaN,2026-05-20T03:27:03.351Z,0.0,...,2026-05-30T21:11:53.589Z,Pink Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4475,1930918551,7.656120e+16,https://avatars.steamstatic.com/3d598f847cb0ab...,https://avatars.steamstatic.com/3d598f847cb0ab...,https://avatars.steamstatic.com/3d598f847cb0ab...,https://steamcommunity.com/profiles/7656119989...,Сосу за деньги,NaN,2026-01-28T12:21:29.953Z,0.0,...,2026-05-23T09:26:10.526Z,y0nd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
def realiza_request(url, method='get'):
  try:
    match method.lower():
      case 'get':
        response = requests.get(url)
      case 'post':
        response = requests.post(url)

    # Verifica se a requisição foi bem sucedida (Status 200)
    response.raise_for_status()
    json_response = response.json()

    if not json_response:
        print("Sem resposta")
        return 404
    return json_response
  except requests.exceptions.RequestException as e:
    print(f"Erro ao acessar a API: {e}")
    if e.response is not None: # prevê erro de rede (descobri conectado na rede da faculdade)
      if e.response.status_code == 404:
        return 404
      if e.response.status_code in [429, 500]:
        time.sleep(65)
        return realiza_request(url, method)
      else:
        return None
  except Exception as e:
    print(f"Erro ao acessar a API: {e}")
    return None

In [4]:
def player_info(account_id):
  return realiza_request(f"https://api.opendota.com/api/players/{account_id}")

In [5]:
def get_top_players_info(ids):
  ids_lidos = []
  ids_com_erro = []
  indice=0
  try:
    for id in ids:

      info = player_info(id)

      if info == None:
        raise Exception()
      if info == 404:
        ids_com_erro.append(id)
        continue
      
      with open(f'info_players/id{id}.json', 'w', encoding='utf-8') as arquivo:
        json.dump(info, arquivo, ensure_ascii=False, indent=2)
      indice+=1
      ids_lidos.append(int(id))

  except Exception as e:
    print(f"erro no id {id} de indice {indice}")
    print(e)
  finally:
    return ids_lidos, ids_com_erro

In [6]:
ultimo_id = 1118496070
ultimo_index = list(topPlayers[topPlayers["account_id"] == ultimo_id].index)[0]
ultimo_index

2801

In [7]:
para_coletar = list(topPlayers["account_id"])[ultimo_index+1:]
para_coletar[0]

1118646774

In [ ]:

ids_lidos, ids_com_erro = get_top_players_info(para_coletar)
ids_coletados = {"sucesso": ids_lidos, "erro": ids_com_erro}
with open('ids_coletados.json', 'w', encoding='utf-8') as arquivo:
      json.dump(ids_coletados, arquivo, ensure_ascii=False, indent=2)

In [2]:
def player_matches(account_id):
    return realiza_request(f"https://api.opendota.com/api/players/{account_id}/matches")

In [3]:
def get_top_players_matches(ids):
  ids_lidos = []
  ids_com_erro = []
  indice=0
  try:
    for id in ids:

      info = player_matches(id)

      if info == None:
        raise Exception()
      if info == 404:
        print("id com erro 404 ou sem resposta:", id)
        ids_com_erro.append(id)
        continue
      
      with open(f'match_players/id{id}.json', 'w', encoding='utf-8') as arquivo:
        json.dump(info, arquivo, ensure_ascii=False, indent=2)
      indice+=1
      ids_lidos.append(int(id))

  except Exception as e:
    print(f"erro no id {id} de indice {indice}")
    print(e)
  finally:
    return ids_lidos, ids_com_erro

In [5]:
topPlayers = pd.read_csv("topPlayersAllInfo.csv")
topPlayers

,account_id,personaname,name,plus,cheese,steamid,avatar,avatarmedium,avatarfull,profileurl,...,profile_time,rank_tier_time,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,1455598719,dissmilateq,dissmilateq,False,0,76561199415864447,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://steamcommunity.com/id/dissmilateqq/,...,2026-05-14T22:53:53.444Z,2026-05-26T04:59:59.067Z,NaN,1.0,9834639.0,I Hate Women,IHW,NaN,NaN,NaN
1,1674581159,трусики мерксли,whydantezzcry,True,0,76561199634846887,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://steamcommunity.com/profiles/7656119963...,...,2026-05-11T00:19:52.865Z,2026-06-07T13:43:04.511Z,ru,1.0,9383049.0,98squad,98,NaN,NaN,NaN
2,1097934237,Dummheit,vetmo,False,0,76561199058199965,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://steamcommunity.com/id/fuckfuckfuckxdx/,...,2026-05-24T14:25:49.611Z,2026-06-01T22:44:34.227Z,by,1.0,0.0,paris x gen,PXG,NaN,NaN,NaN
3,1600007774,Лобанов,Dekty,False,0,76561199560273502,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://steamcommunity.com/profiles/7656119956...,...,2026-05-10T11:55:51.654Z,2026-05-29T14:25:03.812Z,NaN,1.0,10136414.0,Team Nakurilis,BRUD999,NaN,NaN,NaN
4,114374024,Calm,AN****❧,False,0,76561198074639752,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://steamcommunity.com/profiles/7656119807...,...,2026-05-19T21:48:56.558Z,2026-04-13T02:31:17.485Z,pe,2.0,8318424.0,COCHLEA,CH,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4460,408562539,MotyaRolla,MotyaRolla,False,0,76561198368828267,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://steamcommunity.com/id/motyarolla/,...,2026-05-18T16:12:17.413Z,2026-06-06T01:09:29.106Z,us,3.0,10145397.0,Makoto,MKT,NaN,NaN,NaN
4461,187123736,six-six-sick,Norma,True,0,76561198147389464,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://steamcommunity.com/id/NeeNorma/,...,2026-05-19T16:47:50.849Z,2026-05-07T18:56:38.657Z,ua,1.0,10150889.0,Team Jazz,Jazz,NaN,NaN,NaN
4462,1255505146,iwalkwhenitalk</3,w1lfychyo,True,0,76561199215770874,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://steamcommunity.com/profiles/7656119921...,...,2026-05-23T22:19:11.886Z,2026-05-31T16:41:32.119Z,NaN,1.0,10144048.0,Averiour,AV3,NaN,NaN,NaN
4463,1919826264,светящийся пацан - он светит,footballist,False,0,76561199880091992,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://steamcommunity.com/profiles/7656119988...,...,2026-05-07T15:51:23.592Z,2026-04-13T23:40:35.390Z,NaN,1.0,9938641.0,спортсмены,SPORT,NaN,NaN,NaN
4464,1463561231,Saint-Saëns,saintsaens,False,0,76561199423826959,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://steamcommunity.com/profiles/7656119942...,...,2026-05-17T22:53:18.752Z,2026-06-06T21:35:25.788Z,ru,1.0,9616402.0,rakov,Allah,NaN,NaN,NaN

In [16]:
ultimo_id = 320563321
ultimo_index = list(topPlayers[topPlayers["account_id"] == ultimo_id].index)[0]
ultimo_index

3391

In [17]:
para_coletar = list(topPlayers["account_id"])[ultimo_index+1:]
para_coletar[0]

355168766

In [18]:
ids_lidos, ids_com_erro = get_top_players_matches(para_coletar)
ids_coletados = {"sucesso": ids_lidos, "erro": ids_com_erro}
with open('ids_coletados.json', 'a', encoding='utf-8') as arquivo:
      json.dump(ids_coletados, arquivo, ensure_ascii=False, indent=2)

Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/1594361018/matches
Sem resposta
id com erro 404 ou sem resposta: 1138974461
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/1402510425/matches
Sem resposta
id com erro 404 ou sem resposta: 1816719366
Sem resposta
id com erro 404 ou sem resposta: 1927313273
Sem resposta
id com erro 404 ou sem resposta: 748737168
Sem resposta
id com erro 404 ou sem resposta: 832870704
Sem resposta
id com erro 404 ou sem resposta: 1548053400
Sem resposta
id com erro 404 ou sem resposta: 1536661529
Sem resposta
id com erro 404 ou sem resposta: 1146249681
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/1285038332/matches
Sem resposta
id com erro 404 ou sem resposta: 1856010980
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/877861163/matches
Sem resposta
id com erro 404 ou sem resposta: 1921995663
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/1481397131/matches
Sem resposta
id com erro 404 ou sem resposta: 789942957

In [8]:
ids_com_erro = [ 820409716, 1080116539, 1591441041, 744123582, 769328419, 1908304296, 418749303, 888989832, 1251755786, 1296458867, 817047780, 1861903171, 1873063907, 830365555, 907158874, 1457433600, 1875773869, 1739300202, 1882145259, 816508536, 380762874, 1862391813, 1683204828, 820155635, 814853393, 1719197838, 1735842105, 368080962, 1615557126, 1138974461, 1816719366, 1927313273, 748737168, 832870704, 1548053400, 1536661529, 1146249681, 1856010980, 1921995663, 789942957 ]
ids_lidos, ids_com_erro = get_top_players_matches(ids_com_erro)
ids_coletados = {"sucesso": ids_lidos, "erro": ids_com_erro}
with open('ids_coletados.json', 'a', encoding='utf-8') as arquivo:
      json.dump(ids_coletados, arquivo, ensure_ascii=False, indent=2)

Sem resposta
id com erro 404 ou sem resposta: 820409716
Sem resposta
id com erro 404 ou sem resposta: 1080116539
Sem resposta
id com erro 404 ou sem resposta: 1591441041
Sem resposta
id com erro 404 ou sem resposta: 744123582
Sem resposta
id com erro 404 ou sem resposta: 769328419
Sem resposta
id com erro 404 ou sem resposta: 1908304296
Sem resposta
id com erro 404 ou sem resposta: 418749303
Sem resposta
id com erro 404 ou sem resposta: 888989832
Sem resposta
id com erro 404 ou sem resposta: 1251755786
Sem resposta
id com erro 404 ou sem resposta: 1296458867
Sem resposta
id com erro 404 ou sem resposta: 817047780
Sem resposta
id com erro 404 ou sem resposta: 1861903171
Sem resposta
id com erro 404 ou sem resposta: 1873063907
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/830365555/matches
Sem resposta
id com erro 404 ou sem resposta: 830365555
Sem resposta
id com erro 404 ou sem resposta: 907158874
Sem resposta
id com erro 404 ou sem resposta: 1457433600
Sem resposta
id com erro 404 ou sem resposta: 1875773869
Sem resposta
id com erro 404 ou sem resposta: 1739300202
Sem resposta
id com erro 404 ou sem resposta: 1882145259
Sem resposta
id com erro 404 ou sem resposta: 816508536
Sem resposta
id com erro 404 ou sem resposta: 380762874
Sem resposta
id com erro 404 ou sem resposta: 1862391813
Sem resposta
id com erro 404 ou sem resposta: 1683204828
Sem resposta
id com erro 404 ou sem resposta: 820155635
Sem resposta
id com erro 404 ou sem resposta: 814853393
Sem resposta
id com erro 404 ou sem resposta: 1719197838
Sem resposta
id com erro 404 ou sem resposta: 1735842105
Sem resposta
id com erro 404 ou sem resposta: 368080962
Sem resposta
id com erro 404 ou sem resposta: 1615557126
Sem resposta
id com erro 404 ou sem resposta: 1138974461
Sem resposta
id com erro 404 ou sem resposta: 1816719366
Sem resposta
id com erro 404 ou sem resposta: 1927313273
Sem resposta
id com erro 404 ou sem resposta: 748737168
Sem resposta
id com erro 404 ou sem resposta: 832870704
Sem resposta
id com erro 404 ou sem resposta: 1548053400
Sem resposta
id com erro 404 ou sem resposta: 1536661529
Sem resposta
id com erro 404 ou sem resposta: 1146249681
Sem resposta
id com erro 404 ou sem resposta: 1856010980
Sem resposta
id com erro 404 ou sem resposta: 1921995663
Sem resposta
id com erro 404 ou sem resposta: 789942957

In [4]:
def matches(match_id):
    return realiza_request(f"https://api.opendota.com/api/matches/{match_id}")

In [13]:
res = matches(8844434282)
res

{'players': [{'account_id': 144664527,
   'player_slot': 0,
   'team_number': 0,
   'team_slot': 0,
   'hero_id': 20,
   'hero_variant': 0,
   'item_0': 40,
   'item_1': 81,
   'item_2': 931,
   'item_3': 1,
   'item_4': 232,
   'item_5': 1808,
   'backpack_0': 42,
   'backpack_1': 4204,
   'backpack_2': 260,
   'item_neutral': 837,
   'item_neutral2': 1592,
   'kills': 1,
   'deaths': 11,
   'assists': 27,
   'leaver_status': 0,
   'last_hits': 54,
   'denies': 3,
   'gold_per_min': 738,
   'xp_per_min': 1550,
   'level': 29,
   'net_worth': 25607,
   'aghanims_scepter': 1,
   'aghanims_shard': 0,
   'moonshard': 0,
   'hero_damage': 13693,
   'tower_damage': 425,
   'hero_healing': 10938,
   'gold': 3177,
   'gold_spent': 25475,
   'ability_upgrades_arr': [5124,
    5122,
    5122,
    5124,
    5122,
    5125,
    5122,
    5124,
    5124,
    5123,
    1068,
    5123,
    5125,
    5123,
    5123,
    6977,
    5125,
    6978,
    790,
    1067,
    6310,
    1197],
   'personaname': '꼬모 꾸 데 꾸리오쏘',
   'name': None,
   'last_login': '2025-06-21T16:21:14.204Z',
   'rank_tier': 64,
   'computed_mmr': 4018.46,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': True,
   'win': 0,
   'lose': 1,
   'total_gold': 30417,
   'total_xp': 63885,
   'kills_per_min': 0.02426202992317024,
   'kda': 2.33,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 738, 'pct': 0.2161849710982659},
    'xp_per_min': {'raw': 1550, 'pct': 0.2161849710982659},
    'kills_per_min': {'raw': 0.024262029923170236,
     'pct': 0.048554913294797684},
    'last_hits_per_min': {'raw': 1.3101496158511927,
     'pct': 0.19190751445086704},
    'hero_damage_per_min': {'raw': 332.21997573797006,
     'pct': 0.07745664739884393},
    'hero_healing_per_min': {'raw': 265.3780832996361,
     'pct': 0.9965317919075144},
    'tower_damage': {'raw': 425, 'pct': 0.3017341040462428}}},
  {'account_id': 164451511,
   'player_slot': 1,
   'team_number': 0,
   'team_slot': 1,
   'hero_id': 104,
   'hero_variant': 0,
   'item_0': 127,
   'item_1': 600,
   'item_2': 116,
   'item_3': 48,
   'item_4': 208,
   'item_5': 141,
   'backpack_0': 4206,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 371,
   'item_neutral2': 1596,
   'kills': 13,
   'deaths': 9,
   'assists': 9,
   'leaver_status': 0,
   'last_hits': 179,
   'denies': 5,
   'gold_per_min': 1164,
   'xp_per_min': 1508,
   'level': 29,
   'net_worth': 40551,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 45018,
   'tower_damage': 3710,
   'hero_healing': 6343,
   'gold': 6051,
   'gold_spent': 38590,
   'ability_upgrades_arr': [5595,
    5597,
    5595,
    5596,
    5595,
    5598,
    5596,
    5595,
    5597,
    5597,
    1837,
    5597,
    5598,
    5596,
    5596,
    6671,
    5598,
    1838,
    1839,
    1113,
    463,
    6526],
   'personaname': '⚡MegaZord⚡',
   'name': None,
   'last_login': None,
   'rank_tier': 75,
   'computed_mmr': 4000.87,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': True,
   'win': 0,
   'lose': 1,
   'total_gold': 47976,
   'total_xp': 62154,
   'kills_per_min': 0.3154063890012131,
   'kda': 2.2,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1164, 'pct': 0.6769087523277467},
    'xp_per_min': {'raw': 1508, 'pct': 0.24767225325884543},
    'kills_per_min': {'raw': 0.3154063890012131, 'pct': 0.6527001862197392},
    'last_hits_per_min': {'raw': 4.342903356247473, 'pct': 0.7225325884543762},
    'hero_damage_per_min': {'raw': 1092.228063081278,
     'pct': 0.7169459962756052},
    'hero_healing_per_min': {'raw': 153.89405580266882,
     'pct': 0.8677839851024208},
    'tower_damage': {'raw': 3710, 'pct': 0.776536312849162}}},
  {'player_slot': 2,
   'team_number': 0,
   'team_slot': 2,
   'hero_id': 13,
   'hero_variant': 0,
   'item_0': 110,
   'item_1': 141,
   'item_2': 135,
   'item_3': 249,
   'item_4': 133,
   'item_5': 1,
   'backpack_0': 0,
   'backpack_1': 39,
   'backpack_2': 0,
   'item_neutral': 1645,
   'item_neutral2': 0,
   'kills': 11,
   'deaths': 8,
   'assists': 9,
   'leaver_status': 0,
   'last_hits': 194,
   'denies': 4,
   'gold_per_min': 1101,
   'xp_per_min': 1996,
   'level': 30,
   'net_worth': 42619,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 1,
   'hero_damage': 46933,
   'tower_damage': 3584,
   'hero_healing': 594,
   'gold': 2669,
   'gold_spent': 44945,
   'ability_upgrades_arr': [5069,
    5072,
    5069,
    5071,
    5069,
    5073,
    5069,
    5071,
    5071,
    5072,
    5071,
    5073,
    767,
    5072,
    5072,
    407,
    5073,
    1058,
    6219,
    1057,
    348,
    6402,
    1129],
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': True,
   'win': 0,
   'lose': 1,
   'total_gold': 45379,
   'total_xp': 82268,
   'kills_per_min': 0.2668823291548726,
   'kda': 2.22,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1101, 'pct': 0.5939226519337016},
    'xp_per_min': {'raw': 1996, 'pct': 0.5220994475138122},
    'kills_per_min': {'raw': 0.2668823291548726, 'pct': 0.6104972375690608},
    'last_hits_per_min': {'raw': 4.706833805095027, 'pct': 0.6878453038674033},
    'hero_damage_per_min': {'raw': 1138.6898503841487,
     'pct': 0.7596685082872928},
    'hero_healing_per_min': {'raw': 14.411645774363123,
     'pct': 0.988950276243094},
    'tower_damage': {'raw': 3584, 'pct': 0.8149171270718232}}},
  {'account_id': 123760495,
   'player_slot': 3,
   'team_number': 0,
   'team_slot': 3,
   'hero_id': 155,
   'hero_variant': 0,
   'item_0': 226,
   'item_1': 254,
   'item_2': 229,
   'item_3': 231,
   'item_4': 0,
   'item_5': 269,
   'backpack_0': 0,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 1862,
   'item_neutral2': 1592,
   'kills': 1,
   'deaths': 11,
   'assists': 20,
   'leaver_status': 0,
   'last_hits': 97,
   'denies': 3,
   'gold_per_min': 805,
   'xp_per_min': 1519,
   'level': 29,
   'net_worth': 25723,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 16799,
   'tower_damage': 184,
   'hero_healing': 22378,
   'gold': 3048,
   'gold_spent': 25670,
   'ability_upgrades_arr': [1660,
    1659,
    1660,
    1659,
    1660,
    1662,
    1660,
    1659,
    1661,
    1659,
    1661,
    1662,
    1667,
    1661,
    1661,
    1670,
    1662,
    1674,
    1673,
    1668,
    1669,
    1672],
   'personaname': 'Pepe Kafu Dida',
   'name': None,
   'last_login': '2026-04-26T13:53:45.457Z',
   'rank_tier': 54,
   'computed_mmr': None,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': True,
   'win': 0,
   'lose': 1,
   'total_gold': 33179,
   'total_xp': 62608,
   'kills_per_min': 0.02426202992317024,
   'kda': 1.75,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 805, 'pct': 0.5521472392638037},
    'xp_per_min': {'raw': 1519, 'pct': 0.4049079754601227},
    'kills_per_min': {'raw': 0.024262029923170236, 'pct': 0.12269938650306748},
    'last_hits_per_min': {'raw': 2.3534169025475133,
     'pct': 0.7361963190184049},
    'hero_damage_per_min': {'raw': 407.5778406793368,
     'pct': 0.4723926380368098},
    'hero_healing_per_min': {'raw': 542.9357056207036,
     'pct': 0.7975460122699386},
    'tower_damage': {'raw': 184, 'pct': 0.4294478527607362}}},
  {'account_id': 887545150,
   'player_slot': 4,
   'team_number': 0,
   'team_slot': 4,
   'hero_id': 72,
   'hero_variant': 0,
   'item_0': 156,
   'item_1': 160,
   'item_2': 249,
   'item_3': 116,
   'item_4': 141,
   'item_5': 220,
   'backpack_0': 0,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 292,
   'item_neutral2': 1594,
   'kills': 6,
   'deaths': 8,
   'assists': 14,
   'leaver_status': 0,
   'last_hits': 267,
   'denies': 1,
   'gold_per_min': 1261,
   'xp_per_min': 1715,
   'level': 30,
   'net_worth': 40629,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 52110,
   'tower_damage': 2975,
   'hero_healing': 0,
   'gold': 3029,
   'gold_spent': 46700,
   'ability_upgrades_arr': [5361,
    5362,
    5361,
    5362,
    5361,
    5364,
    5361,
    5363,
    5362,
    5363,
    5902,
    5364,
    5363,
    5362,
    5363,
    1012,
    5364,
    6312,
    6654,
    1332,
    7141,
    6652,
    6216],
   'personaname': 'Alfred Hugecock',
   'name': None,
   'last_login': None,
   'rank_tier': 41,
   'computed_mmr': None,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': True,
   'win': 0,
   'lose': 1,
   'total_gold': 51974,
   'total_xp': 70686,
   'kills_per_min': 0.14557217953902143,
   'kda': 2.22,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1261, 'pct': 0.6840390879478827},
    'xp_per_min': {'raw': 1715, 'pct': 0.44299674267100975},
    'kills_per_min': {'raw': 0.14557217953902143, 'pct': 0.32247557003257327},
    'last_hits_per_min': {'raw': 6.477961989486453, 'pct': 0.749185667752443},
    'hero_damage_per_min': {'raw': 1264.294379296401,
     'pct': 0.6872964169381107},
    'hero_healing_per_min': {'raw': 0, 'pct': 0.8957654723127035},
    'tower_damage': {'raw': 2975, 'pct': 0.6351791530944625}}},
  {'player_slot': 128,
   'team_number': 1,
   'team_slot': 0,
   'hero_id': 87,
   'hero_variant': 0,
   'item_0': 231,
   'item_1': 223,
   'item_2': 100,
   'item_3': 254,
   'item_4': 235,
   'item_5': 232,
   'backpack_0': 0,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 1642,
   'item_neutral2': 1592,
   'kills': 7,
   'deaths': 3,
   'assists': 27,
   'leaver_status': 0,
   'last_hits': 97,
   'denies': 2,
   'gold_per_min': 851,
   'xp_per_min': 1750,
   'level': 30,
   'net_worth': 33738,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 20355,
   'tower_damage': 4592,
   'hero_healing': 3980,
   'gold': 7113,
   'gold_spent': 34235,
   'ability_upgrades_arr': [5459,
    5458,
    5458,
    5460,
    5458,
    5461,
    5458,
    5459,
    5459,
    1142,
    5459,
    5461,
    5460,
    5460,
    5460,
    788,
    5461,
    737,
    1832,
    5918,
    6215,
    6812,
    6630],
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': False,
   'win': 1,
   'lose': 0,
   'total_gold': 35075,
   'total_xp': 72129,
   'kills_per_min': 0.16983420946219166,
   'kda': 8.5,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 851, 'pct': 0.6605263157894737},
    'xp_per_min': {'raw': 1750, 'pct': 0.531578947368421},
    'kills_per_min': {'raw': 0.16983420946219166, 'pct': 0.7342105263157894},
    'last_hits_per_min': {'raw': 2.3534169025475133,
     'pct': 0.9157894736842105},
    'hero_damage_per_min': {'raw': 493.85361908613015,
     'pct': 0.3815789473684211},
    'hero_healing_per_min': {'raw': 96.56287909421755,
     'pct': 0.9526315789473684},
    'tower_damage': {'raw': 4592, 'pct': 0.9973684210526316}}},
  {'player_slot': 129,
   'team_number': 1,
   'team_slot': 1,
   'hero_id': 9,
   'hero_variant': 0,
   'item_0': 158,
   'item_1': 0,
   'item_2': 123,
   'item_3': 147,
   'item_4': 116,
   'item_5': 48,
   'backpack_0': 188,
   'backpack_1': 0,
   'backpack_2': 40,
   'item_neutral': 292,
   'item_neutral2': 1596,
   'kills': 10,
   'deaths': 8,
   'assists': 20,
   'leaver_status': 0,
   'last_hits': 155,
   'denies': 1,
   'gold_per_min': 1061,
   'xp_per_min': 1624,
   'level': 30,
   'net_worth': 41601,
   'aghanims_scepter': 0,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 30833,
   'tower_damage': 6184,
   'hero_healing': 1150,
   'gold': 13021,
   'gold_spent': 32515,
   'ability_upgrades_arr': [5050,
    5051,
    5051,
    5048,
    5051,
    1213,
    5051,
    5050,
    5050,
    5050,
    817,
    5048,
    5048,
    5048,
    1213,
    6013,
    1213,
    1788,
    6242,
    6397,
    702,
    823],
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': False,
   'win': 1,
   'lose': 0,
   'total_gold': 43730,
   'total_xp': 66935,
   'kills_per_min': 0.24262029923170236,
   'kda': 3.33,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1061, 'pct': 0.6112676056338028},
    'xp_per_min': {'raw': 1624, 'pct': 0.35070422535211265},
    'kills_per_min': {'raw': 0.2426202992317024, 'pct': 0.6070422535211267},
    'last_hits_per_min': {'raw': 3.7606146380913867,
     'pct': 0.5957746478873239},
    'hero_damage_per_min': {'raw': 748.071168621108,
     'pct': 0.4830985915492958},
    'hero_healing_per_min': {'raw': 27.901334411645774,
     'pct': 0.8802816901408451},
    'tower_damage': {'raw': 6184, 'pct': 0.8929577464788733}}},
  {'account_id': 98173961,
   'player_slot': 130,
   'team_number': 1,
   'team_slot': 2,
   'hero_id': 7,
   'hero_variant': 0,
   'item_0': 1,
   'item_1': 610,
   'item_2': 48,
   'item_3': 235,
   'item_4': 277,
   'item_5': 123,
   'backpack_0': 0,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 1643,
   'item_neutral2': 1592,
   'kills': 2,
   'deaths': 9,
   'assists': 26,
   'leaver_status': 0,
   'last_hits': 227,
   'denies': 11,
   'gold_per_min': 1037,
   'xp_per_min': 1667,
   'level': 30,
   'net_worth': 41042,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 30478,
   'tower_damage': 816,
   'hero_healing': 0,
   'gold': 8292,
   'gold_spent': 36370,
   'ability_upgrades_arr': [5024,
    5025,
    5024,
    5023,
    5024,
    5026,
    5024,
    5025,
    5025,
    5025,
    450,
    5026,
    5023,
    5023,
    5023,
    858,
    5026,
    6425,
    1208,
    744,
    6511,
    918,
    6035],
   'personaname': 'JPKOSTOVSKI',
   'name': None,
   'last_login': None,
   'rank_tier': 64,
   'computed_mmr': None,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': False,
   'win': 1,
   'lose': 0,
   'total_gold': 42741,
   'total_xp': 68708,
   'kills_per_min': 0.04852405984634048,
   'kda': 2.8,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1037, 'pct': 0.593127147766323},
    'xp_per_min': {'raw': 1667, 'pct': 0.384192439862543},
    'kills_per_min': {'raw': 0.04852405984634047, 'pct': 0.09759450171821306},
    'last_hits_per_min': {'raw': 5.507480792559644, 'pct': 0.8824742268041237},
    'hero_damage_per_min': {'raw': 739.4581479983825,
     'pct': 0.4041237113402062},
    'hero_healing_per_min': {'raw': 0, 'pct': 0.865979381443299},
    'tower_damage': {'raw': 816, 'pct': 0.570446735395189}}},
  {'account_id': 241827226,
   'player_slot': 131,
   'team_number': 1,
   'team_slot': 3,
   'hero_id': 67,
   'hero_variant': 0,
   'item_0': 147,
   'item_1': 1097,
   'item_2': 127,
   'item_3': 114,
   'item_4': 160,
   'item_5': 139,
   'backpack_0': 0,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 1168,
   'item_neutral2': 1588,
   'kills': 13,
   'deaths': 8,
   'assists': 23,
   'leaver_status': 0,
   'last_hits': 283,
   'denies': 3,
   'gold_per_min': 1476,
   'xp_per_min': 2135,
   'level': 30,
   'net_worth': 59307,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 126531,
   'tower_damage': 11967,
   'hero_healing': 0,
   'gold': 22407,
   'gold_spent': 40620,
   'ability_upgrades_arr': [5334,
    5336,
    5334,
    1679,
    5334,
    5337,
    5334,
    1679,
    1679,
    1679,
    6900,
    5337,
    5336,
    5336,
    5336,
    1705,
    5337,
    5993,
    6903,
    6148,
    8040,
    6901,
    6902],
   'personaname': 'C H A P I S C O',
   'name': None,
   'last_login': None,
   'rank_tier': 45,
   'computed_mmr': 3935.41,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': False,
   'win': 1,
   'lose': 0,
   'total_gold': 60835,
   'total_xp': 87997,
   'kills_per_min': 0.3154063890012131,
   'kda': 4,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1476, 'pct': 0.7465681098204857},
    'xp_per_min': {'raw': 2135, 'pct': 0.46884899683210135},
    'kills_per_min': {'raw': 0.3154063890012131, 'pct': 0.5121436114044351},
    'last_hits_per_min': {'raw': 6.866154468257178, 'pct': 0.8194297782470961},
    'hero_damage_per_min': {'raw': 3069.8989082086537,
     'pct': 0.9936642027455121},
    'hero_healing_per_min': {'raw': 0, 'pct': 0.9503695881731784},
    'tower_damage': {'raw': 11967, 'pct': 0.9693769799366421}}},
  {'account_id': 86807417,
   'player_slot': 132,
   'team_number': 1,
   'team_slot': 4,
   'hero_id': 101,
   'hero_variant': 0,
   'item_0': 1856,
   'item_1': 235,
   'item_2': 220,
   'item_3': 123,
   'item_4': 1466,
   'item_5': 610,
   'backpack_0': 4206,
   'backpack_1': 0,
   'backpack_2': 0,
   'item_neutral': 1863,
   'item_neutral2': 1592,
   'kills': 15,
   'deaths': 4,
   'assists': 20,
   'leaver_status': 0,
   'last_hits': 224,
   'denies': 11,
   'gold_per_min': 1293,
   'xp_per_min': 1814,
   'level': 30,
   'net_worth': 50044,
   'aghanims_scepter': 1,
   'aghanims_shard': 1,
   'moonshard': 0,
   'hero_damage': 59202,
   'tower_damage': 18,
   'hero_healing': 0,
   'gold': 12394,
   'gold_spent': 44040,
   'ability_upgrades_arr': [5582,
    5581,
    5583,
    5582,
    5582,
    5584,
    5582,
    5583,
    5583,
    5583,
    7132,
    5581,
    5584,
    5581,
    5581,
    1480,
    5584,
    6886,
    6921,
    411,
    6181,
    6885,
    6884],
   'personaname': 'rumo ao cruzado',
   'name': None,
   'last_login': '2021-11-29T00:04:18.853Z',
   'rank_tier': 71,
   'computed_mmr': 4506.62,
   'is_subscriber': False,
   'radiant_win': False,
   'start_time': 1780961103,
   'duration': 2473,
   'cluster': 202,
   'lobby_type': 0,
   'game_mode': 23,
   'is_contributor': False,
   'patch': 60,
   'region': 10,
   'isRadiant': False,
   'win': 1,
   'lose': 0,
   'total_gold': 53293,
   'total_xp': 74767,
   'kills_per_min': 0.36393044884755354,
   'kda': 7,
   'abandons': 0,
   'benchmarks': {'gold_per_min': {'raw': 1293, 'pct': 0.8895300906842539},
    'xp_per_min': {'raw': 1814, 'pct': 0.47155812036273703},
    'kills_per_min': {'raw': 0.3639304488475536, 'pct': 0.6924979389942292},
    'last_hits_per_min': {'raw': 5.434694702790133, 'pct': 0.9777411376751854},
    'hero_damage_per_min': {'raw': 1436.3606955115245,
     'pct': 0.8532563891178895},
    'hero_healing_per_min': {'raw': 0, 'pct': 0.8153338829348722},
    'tower_damage': {'raw': 18, 'pct': 0.25061830173124483}}}],
 'radiant_win': False,
 'duration': 2473,
 'pre_game_duration': 60,
 'start_time': 1780961103,
 'match_id': 8844434282,
 'match_seq_num': 7433210455,
 'tower_status_radiant': 6,

In [5]:
def parsear_partida(match_id):
   print(f"parseando id {match_id}")
   resposta = realiza_request(f"https://api.opendota.com/api/request/{match_id}", method='post')
   if resposta in [None, 404]:
      return resposta
   jobId = resposta['job']['jobId']
   time.sleep(1)
   job_em_andamento = True
   print("Esperando job acabar", end="")
   while job_em_andamento:
      resposta = realiza_request(f"https://api.opendota.com/api/request/{jobId}")
      if resposta and 'progress' in str(resposta):
         print(".", end="", flush=True)
         time.sleep(5)
      else:
         # Qualquer outra resposta (404, None, ou sucesso) para o job
         job_em_andamento = False
         print()

In [6]:
def get_matches(ids):
  ids_lidos = []
  ids_com_erro = []
  indice=0
  
  try:
    for id in ids:
      info = matches(id)

      if info == None:
        raise Exception()
      if info == 404:
        print("id com erro 404 ou sem resposta:", id)
        ids_com_erro.append(id)
        continue

      chat = info.get('chat')

      if chat is None:
        print(f"O chat não está disponível para a partida {id} (pode não ter sido parseada).")
        parsear_partida(id)
        info = matches(id)
        chat = info.get('chat')

      with open(f'matches/id{id}.json', 'w', encoding='utf-8') as arquivo:
        json.dump(info, arquivo, ensure_ascii=False, indent=2)
      indice+=1
      ids_lidos.append(int(id))

  except Exception as e:
    print(f"erro no id {id} de indice {indice}")
    print(e)
  finally:
    return ids_lidos, ids_com_erro

In [9]:
df_matches = pd.read_csv("onlyMatchPlayerID.csv")
dez_mil_primeiros = df_matches.sample(n=10000, random_state=42, ignore_index=True)
dez_mil_primeiros

        match_id  account_id
0     6561285015  1023238160
1     4039647129   325697153
2     7179400116   315205221
3      283613735    60943014
4      782255376    41231571
...          ...         ...
9995  4251499291    91460772
9996  7610802652  1468181918
9997  5913919589   461405753
9998   644276070   134556694
9999  4085012564   322010194

[10000 rows x 2 columns]

In [ ]:
para_coletar = list(dez_mil_primeiros["match_id"])
para_coletar

In [13]:
ultimo_id = 8735955288
ultimo_index = list(dez_mil_primeiros[dez_mil_primeiros["match_id"] == ultimo_id].index)[0]
ultimo_index
para_coletar = list(dez_mil_primeiros["match_id"])[ultimo_index+1:]
print(ultimo_index, dez_mil_primeiros["match_id"][ultimo_index], "proximo:", para_coletar[0])

1837 8735955288 proximo: 8522213972

In [ ]:

ids_lidos, ids_com_erro = get_matches(para_coletar)
ids_coletados = {"sucesso": ids_lidos, "erro": ids_com_erro}
with open('partidas_coletadas.json', 'a', encoding='utf-8') as arquivo:
      json.dump(ids_coletados, arquivo, ensure_ascii=False, indent=2)

Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/matches/8522213972

In [ ]:

def buscar_chat_partida(match_id):
    url = f"https://api.opendota.com/api/matches/{match_id}"

    try:
        print(f"Buscando detalhes da partida {match_id}...")
        response = requests.get(url)
        response.raise_for_status()

        dados_partida = response.json()
        chat = dados_partida.get('chat')

        if chat is None:
            return "O chat não está disponível para esta partida (pode não ter sido parseada)."

        if len(chat) == 0:
            return "Nenhuma mensagem de chat encontrada nesta partida."

        # Formatando as mensagens para leitura
        mensagens_formatadas = []
        for msg in chat:
            # 'type' pode ser 'chat' (texto normal) ou 'chatwheel' (roda de mensagens)
            tipo = msg.get('type')
            tempo = msg.get('time') # Tempo em segundos desde o início do jogo
            jogador = msg.get('unit', f"Jogador {msg.get('player_slot')}")
            texto = msg.get('key', '') #if tipo == 'chatwheel' else msg.get('key', '')

            # Converter tempo em formato MM:SS
            minutos = int(tempo // 60)
            segundos = int(tempo % 60)
            timestamp = f"{minutos:02d}:{segundos:02d}"

            mensagens_formatadas.append(f"[{timestamp}] {jogador}: {texto}")

        return mensagens_formatadas

    except requests.exceptions.RequestException as e:
        return f"Erro ao acessar a API: {e}"

# Exemplo de uso:
ID_PARTIDA = "8638178478" # Substitua por um ID real
historico_chat = buscar_chat_partida(ID_PARTIDA)

if isinstance(historico_chat, list):
    for linha in historico_chat:
        print(linha)
else:
    print(historico_chat)

Buscando detalhes da partida 8638178478...
[01:43] Jogador 129: 107002
[19:06] Jogador 2: 41001
[19:20] Jogador 2: 41001
[28:18] Jogador 3: 47003
[28:21] Jogador 0: wp

In [ ]:
def integrar_chats_ao_dataframe(df_partidas):
    if df_partidas is None or df_partidas.empty:
        print("DataFrame vazio ou inválido.")
        return None

    print(f"Iniciando a busca de chat para {len(df_partidas)} partidas...")

    # Criamos uma lista para armazenar os resultados temporariamente
    todos_os_chats = []

    for index, row in df_partidas.iterrows():
        match_id = row['match_id']

        # Chama a função que criamos anteriormente
        resultado_chat = buscar_chat_partida(match_id)

        # Se o resultado for uma lista (mensagens), juntamos em uma única string
        # Se for erro ou string de aviso, salvamos a mensagem de erro
        if isinstance(resultado_chat, list):
            chat_texto = " | ".join(resultado_chat)
        else:
            chat_texto = resultado_chat

        todos_os_chats.append(chat_texto)

        # Pausa de 1 segundo entre requisições para respeitar o limite da API gratuita
        time.sleep(1)
        print(f"Processado {index + 1}/{len(df_partidas)} (Match ID: {match_id})")

    # Adiciona a nova coluna ao DataFrame
    df_partidas['chat_log'] = todos_os_chats

    return df_partidas

# --- EXECUÇÃO ---

# 1. Recupera as últimas 10 partidas de um jogador
df_inicial = buscar_partidas_jogador(PLAYER_ID)

# 2. Enriquece o DataFrame com o chat
df_final = integrar_chats_ao_dataframe(df_inicial)

# 3. Exibe o resultado
print("\nDataFrame Atualizado:")
print(df_final[['match_id', 'chat_log']].head())

Buscando partidas para o ID: 123760495...
Iniciando a busca de chat para 2582 partidas...
Buscando detalhes da partida 8145780410...
Processado 1/2582 (Match ID: 8145780410)
Buscando detalhes da partida 8145745528...
Processado 2/2582 (Match ID: 8145745528)
Buscando detalhes da partida 7029360506...
Processado 3/2582 (Match ID: 7029360506)
Buscando detalhes da partida 7017477496...
Processado 4/2582 (Match ID: 7017477496)
Buscando detalhes da partida 6745498263...
Processado 5/2582 (Match ID: 6745498263)
Buscando detalhes da partida 6592914637...
Processado 6/2582 (Match ID: 6592914637)
Buscando detalhes da partida 6592592077...
Processado 7/2582 (Match ID: 6592592077)
Buscando detalhes da partida 6404838878...
Processado 8/2582 (Match ID: 6404838878)
Buscando detalhes da partida 6363488061...
Processado 9/2582 (Match ID: 6363488061)
Buscando detalhes da partida 6355846488...
Processado 10/2582 (Match ID: 6355846488)
Buscando detalhes da partida 6276423932...
Processado 11/2582 (Match ID: 6276423932)
Buscando detalhes da partida 6276246085...
Processado 12/2582 (Match ID: 6276246085)
Buscando detalhes da partida 6273544901...
Processado 13/2582 (Match ID: 6273544901)
Buscando detalhes da partida 6273508065...
Processado 14/2582 (Match ID: 6273508065)
Buscando detalhes da partida 6270051484...
Processado 15/2582 (Match ID: 6270051484)
Buscando detalhes da partida 6267071599...
Processado 16/2582 (Match ID: 6267071599)
Buscando detalhes da partida 6266283576...
Processado 17/2582 (Match ID: 6266283576)
Buscando detalhes da partida 6265469611...
Processado 18/2582 (Match ID: 6265469611)
Buscando detalhes da partida 6264551962...
Processado 19/2582 (Match ID: 6264551962)
Buscando detalhes da partida 6263957763...
Processado 20/2582 (Match ID: 6263957763)
Buscando detalhes da partida 6263934670...
Processado 21/2582 (Match ID: 6263934670)
Buscando detalhes da partida 6263886045...
Processado 22/2582 (Match ID: 6263886045)
Buscando detalhes da partida 6263814871...
Processado 23/2582 (Match ID: 6263814871)
Buscando detalhes da partida 6263783586...
Processado 24/2582 (Match ID: 6263783586)
Buscando detalhes da partida 6263746921...
Processado 25/2582 (Match ID: 6263746921)
Buscando detalhes da partida 6263703887...
Processado 26/2582 (Match ID: 6263703887)
Buscando detalhes da partida 6263600483...
Processado 27/2582 (Match ID: 6263600483)
Buscando detalhes da partida 6263509934...
Processado 28/2582 (Match ID: 6263509934)
Buscando detalhes da partida 6262137982...
Processado 29/2582 (Match ID: 6262137982)
Buscando detalhes da partida 6262098050...
Processado 30/2582 (Match ID: 6262098050)
Buscando detalhes da partida 6262073251...
Processado 31/2582 (Match ID: 6262073251)
Buscando detalhes da partida 6262027905...
Processado 32/2582 (Match ID: 6262027905)
Buscando detalhes da partida 6261673322...
Processado 33/2582 (Match ID: 6261673322)
Buscando detalhes da partida 6261582957...
Processado 34/2582 (Match ID: 6261582957)
Buscando detalhes da partida 6261511165...
Processado 35/2582 (Match ID: 6261511165)
Buscando detalhes da partida 6261439556...
Processado 36/2582 (Match ID: 6261439556)
Buscando detalhes da partida 6261327982...
Processado 37/2582 (Match ID: 6261327982)
Buscando detalhes da partida 6259764162...
Processado 38/2582 (Match ID: 6259764162)
Buscando detalhes da partida 6258444019...
Processado 39/2582 (Match ID: 6258444019)
Buscando detalhes da partida 6258387593...
Processado 40/2582 (Match ID: 6258387593)
Buscando detalhes da partida 6258326619...
Processado 41/2582 (Match ID: 6258326619)
Buscando detalhes da partida 6176814564...
Processado 42/2582 (Match ID: 6176814564)
Buscando detalhes da partida 6153501080...
Processado 43/2582 (Match ID: 6153501080)
Buscando detalhes da partida 6152250342...
Processado 44/2582 (Match ID: 6152250342)
Buscando detalhes da partida 6152189024...

KeyboardInterrupt:

In [ ]:
def constants(resource):
  return realiza_request(f"https://api.opendota.com/api/constants/{resource}")

chat_whells = constants("chat_wheel")
chat_whells

{'0': {'id': 0, 'name': 'Ok', 'label': 'Okay', 'message': 'Okay.'},
 '1': {'id': 1, 'name': 'Care', 'label': 'Care', 'message': 'Careful!'},
 '2': {'id': 2,
  'name': 'GetBack',
  'label': 'Get Back',
  'message': 'Get Back!'},
 '3': {'id': 3,
  'name': 'NeedWards',
  'label': 'Need Wards',
  'message': 'We need wards.'},
 '4': {'id': 4, 'name': 'Stun', 'label': 'Stun', 'message': 'Stun now!'},
 '5': {'id': 5, 'name': 'Help', 'label': 'Help', 'message': 'Help!'},
 '6': {'id': 6, 'name': 'Push', 'label': 'Push', 'message': 'Push now'},
 '7': {'id': 7,
  'name': 'GoodJob',
  'label': 'Well played',
  'message': 'Well played!'},
 '8': {'id': 8, 'name': 'Missing', 'label': 'Missing', 'message': 'Missing!'},
 '9': {'id': 9,
  'name': 'Missing_Top',
  'label': 'Missing top',
  'message': 'Missing top!'},
 '10': {'id': 10,
  'name': 'Missing_Mid',
  'label': 'Missing mid',
  'message': 'Missing mid!'},
 '11': {'id': 11,
  'name': 'Missing_Bottom',
  'label': 'Missing bottom',
  'message': 'Missing bottom!'},
 '12': {'id': 12, 'name': 'Go', 'label': 'Go!', 'message': 'Go!'},
 '13': {'id': 13,
  'name': 'Initiate',
  'label': 'Initiate!',
  'message': 'Initiate!'},
 '14': {'id': 14,
  'name': 'Follow',
  'label': 'Follow me',
  'message': 'Follow me'},
 '15': {'id': 15,
  'name': 'Group_Up',
  'label': 'Group up',
  'message': 'Group up'},
 '16': {'id': 16,
  'name': 'Spread_Out',
  'label': 'Spread out',
  'message': 'Spread out'},
 '17': {'id': 17,
  'name': 'Split_Farm',
  'label': 'Split farm',
  'message': 'Split up and farm'},
 '18': {'id': 18,
  'name': 'Attack',
  'label': 'Attack now!',
  'message': 'Attack now!'},
 '19': {'id': 19,
  'name': 'BRB',
  'label': 'Be right back',
  'message': 'Be right back'},
 '20': {'id': 20, 'name': 'Dive', 'label': 'Dive!', 'message': 'Dive!'},
 '21': {'id': 21, 'name': 'OMW', 'label': 'On my way', 'message': 'On my way'},
 '22': {'id': 22,
  'name': 'Get_Ready',
  'label': 'Get ready',
  'message': 'Get ready'},
 '23': {'id': 23, 'name': 'Bait', 'label': 'Bait', 'message': 'Bait'},
 '24': {'id': 24, 'name': 'Heal', 'label': 'Heal', 'message': 'Heal'},
 '25': {'id': 25, 'name': 'Mana', 'label': 'Mana', 'message': 'Mana'},
 '26': {'id': 26,
  'name': 'OOM',
  'label': 'Out of mana',
  'message': 'Out of mana'},
 '27': {'id': 27,
  'name': 'Skill_Cooldown',
  'label': 'Cooldown',
  'message': 'Skills on cooldown'},
 '28': {'id': 28,
  'name': 'Ulti_Ready',
  'label': 'Ultimate ready',
  'message': 'Ultimate ready'},
 '29': {'id': 29,
  'name': 'Enemy_Returned',
  'label': 'Returned',
  'message': 'Enemy returned'},
 '30': {'id': 30,
  'name': 'All_Missing',
  'label': 'All miss',
  'message': 'All enemy heroes missing!'},
 '31': {'id': 31,
  'name': 'Enemy_Incoming',
  'label': 'Incoming',
  'message': 'Enemy incoming!'},
 '32': {'id': 32,
  'name': 'Invis_Enemy',
  'label': 'Invisible enemy',
  'message': 'Invisible enemy nearby!'},
 '33': {'id': 33,
  'name': 'Enemy_Had_Rune',
  'label': 'Enemy has rune',
  'message': 'Enemy has rune'},
 '34': {'id': 34,
  'name': 'Split_Push',
  'label': 'Split push',
  'message': 'Split push'},
 '35': {'id': 35,
  'name': 'Coming_To_Gank',
  'label': 'Coming to gank',
  'message': 'Coming to gank'},
 '36': {'id': 36,
  'name': 'Request_Gank',
  'label': 'Request gank',
  'message': 'Requesting a gank'},
 '37': {'id': 37,
  'name': 'Fight_Under_Tower',
  'label': 'Under tower',
  'message': 'Fight under the tower'},
 '38': {'id': 38,
  'name': 'Deny_Tower',
  'label': 'Deny tower',
  'message': 'Deny the tower!'},
 '41': {'id': 41,
  'name': 'Need_Detection',
  'label': 'We need detection',
  'message': 'We need detection'},
 '42': {'id': 42,
  'name': 'They_Have_Detection',
  'label': 'They have detection',
  'message': 'They have detection'},
 '43': {'id': 43,
  'name': 'Buy_TP',
  'label': 'Buy Town Portal Scroll',
  'message': 'Buy a Town Portal Scroll'},
 '45': {'id': 45,
  'name': 'Deward',
  'label': 'Deward',
  'message': 'Deward please'},
 '46': {'id': 46,
  'name': 'Building_Mek',
  'label': 'Building Mekansm',
  'message': 'Building Mekansm'},
 '47': {'id': 47,
  'name': 'Building_Pipe',
  'label': 'Building Pipe of Insight',
  'message': 'Building Pipe of Insight'},
 '48': {'id': 48,
  'name': 'Stack_And_Pull',
  'label': 'Stack and pull',
  'message': 'Stack and pull please'},
 '49': {'id': 49,
  'name': 'Pull',
  'label': 'Pull creeps',
  'message': 'Pull creeps please'},
 '50': {'id': 50,
  'name': 'Pulling',
  'label': 'Pulling creeps',
  'message': 'Pulling creeps'},
 '51': {'id': 51,
  'name': 'Stack',
  'label': 'Stack neutrals',
  'message': 'Stack neutrals'},
 '52': {'id': 52,
  'name': 'Jungling',
  'label': 'Jungling',
  'message': 'Jungling'},
 '53': {'id': 53, 'name': 'Roshan', 'label': 'Roshan', 'message': 'Roshan'},
 '54': {'id': 54,
  'name': 'Affirmative',
  'label': 'Affirmative',
  'message': 'Affirmative'},
 '55': {'id': 55, 'name': 'Wait', 'label': 'Wait', 'message': 'Wait'},
 '56': {'id': 56,
  'name': 'Pause',
  'label': 'Pause',
  'message': 'Pause please!'},
 '57': {'id': 57,
  'name': 'Current_Time',
  'label': 'Current Time',
  'message': 'Current Game Time'},
 '58': {'id': 58,
  'name': 'Check_Runes',
  'label': 'Check runes',
  'message': 'Check runes please'},
 '59': {'id': 59,
  'name': 'Smoke_Gank',
  'label': 'Smoke gank!',
  'message': "Let's smoke gank!"},
 '60': {'id': 60,
  'name': 'GLHF',
  'label': 'Good luck',
  'message': 'Good luck, have fun'},
 '61': {'id': 61, 'name': 'Nice', 'label': 'Nice', 'message': 'Nice'},
 '62': {'id': 62, 'name': 'Thanks', 'label': 'Thanks', 'message': 'Thanks!'},
 '63': {'id': 63, 'name': 'Sorry', 'label': 'Sorry', 'message': 'Sorry'},
 '64': {'id': 64,
  'name': 'No_Give_Up',
  'label': "Don't give up",
  'message': "Don't give up!"},
 '65': {'id': 65,
  'name': 'Just_Happened',
  'label': 'That just happened',
  'message': 'That just happened'},
 '66': {'id': 66,
  'name': 'Game_Is_Hard',
  'label': 'Game is hard',
  'message': 'Game is hard'},
 '67': {'id': 67,
  'name': 'New_Meta',
  'label': 'New meta',
  'message': 'New meta'},
 '68': {'id': 68, 'name': 'My_Bad', 'label': 'My bad', 'message': 'My bad'},
 '69': {'id': 69,
  'name': 'Regret',
  'label': 'Regret',
  'message': 'I immediately regret my decision'},
 '70': {'id': 70,
  'name': 'Relax',
  'label': 'Relax',
  'message': "Relax, you're doing fine"},
 '71': {'id': 71,
  'name': 'MissingHero',
  'label': 'dota_chatwheel_label_MissingHero',
  'message': 'dota_chatwheel_message_MissingHero'},
 '72': {'id': 72,
  'name': 'ReturnedHero',
  'label': 'dota_chatwheel_label_ReturnedHero',
  'message': 'dota_chatwheel_message_ReturnedHero'},
 '73': {'id': 73, 'name': 'GG', 'label': 'GG', 'message': 'Good game'},
 '74': {'id': 74,
  'name': 'GGWP',
  'label': 'GGWP',
  'message': 'Good game, well played'},
 '75': {'id': 75,
  'name': 'All_GG',
  'all_chat': True,
  'label': 'GG',
  'message': 'Good game'},
 '76': {'id': 76,
  'name': 'All_GGWP',
  'all_chat': True,
  'label': 'GGWP',
  'message': 'Good game, well played'},
 '77': {'id': 77,
  'name': 'What_To_Buy',
  'label': 'What should I buy?',
  'message': 'What should I buy?'},
 '78': {'id': 78,
  'name': 'Im_Retreating',
  'label': "I'm retreating",
  'message': "I'm retreating"},
 '79': {'id': 79,
  'name': 'Space_Created',
  'label': 'Space created',
  'message': 'Space created'},
 '80': {'id': 80, 'name': 'Whoops', 'label': 'Whoops', 'message': 'Whoops'},
 '81': {'id': 81,
  'name': 'Tower_then_Back',
  'label': 'Tower then back',
  'message': 'Destroy the tower, then get back'},
 '82': {'id': 82,
  'name': 'Barracks_then_Back',
  'label': 'Barracks then back',
  'message': 'Destroy the barracks, then get back'},
 '83': {'id': 83,
  'name': 'Ward_Bottom_Rune',
  'label': 'Ward bot rune',
  'message': 'Ward the bottom rune'},
 '84': {'id': 84,
  'name': 'Ward_Top_Rune',
  'label': 'Ward top rune',
  'message': 'Ward the top rune'},
 '85': {'id': 85,
  'name': 'Zeus_Ult',
  'label': 'Zeus Ult',
  'message': 'Zeus Ult Now!'},
 '86': {'id': 86,
  'name': 'Rimshot',
  'label': 'Ba-dum tishh',
  'message': 'Ba-dum tishh',
  'sound_ext': 'wav'},
 '87': {'id': 87,
  'name': 'Charge',
  'label': 'Charge',
  'message': 'Charge',
  'sound_ext': 'wav'},
 '88': {'id': 88,
  'name': 'Frog',
  'label': 'Frog',
  'message': 'Frog',
  'sound_ext': 'wav'},
 '89': {'id': 89,
  'name': 'Crash_and_Burn',
  'label': 'Crash',
  'message': 'Crash and burn',
  'sound_ext': 'wav'},
 '90': {'id': 90,
  'name': 'Applause',
  'label': 'Applause',
  'message': 'Applause',
  'sound_ext': 'wav'},
 '91': {'id': 91,
  'name': 'Sad_Trombone',
  'label': 'Sad trombone',
  'message': 'Sad trombone',
  'sound_ext': 'wav'},
 '92': {'id': 92,
  'name': 'Crickets',
  'label': 'Crickets',
  'message': 'Crickets',
  'sound_ext': 'wav'},
 '93': {'id': 93,
  'name': 'Drum_Roll',
  'label': 'Drum roll',
  'message': 'Drum roll',
  'sound_ext': 'wav'},
 '94': {'id': 94,
  'name': 'Headshake',
  'label': 'Headshake',
  'message': 'Headshake',
  'sound_ext': 'wav'},
 '95': {'id': 95,
  'name': 'Crybaby',
  'label': 'Crybaby',
  'message': 'Crybaby',
  'sound_ext': 'wav'},
 '96': {'id': 96,
  'name': 'Patience',
  'label': 'Patience',
  'message': 'Patience from Zhou',
  'sound_ext': 'wav'},
 '101': {'id': 101,
  'name': 'Bozhe_Ti_Posmotri',
  'label': 'Что Происходит',
  'message': 'Боже, ты посмотри вокруг, что происходит!',
  'sound_ext': 'wav'},
 '111': {'id': 111,
  'name': 'Day_Night_Cycle',
  'label': 'Day/Night Cycle',
  'message': 'dota_chatwheel_message_Day_Night_Cycle'},
 '112': {'id': 112,
  'name': 'Thats_Playing_to_Win',
  'label': "That's Playing to Win!",
  'message': "That's playing to win, baby!",
  'sound_ext': 'wav'},
 '114': {'id': 114,
  'name': 'Absolutely_Perfect',
  'label': 'Absolutely Perfect',
  'message': 'Absolutely Perfect',
  'sound_ext': 'wav'},
 '115': {'id': 115,
  'name': 'Looking_Spicy',
  'label': 'Looking Spicy',
  'message': "It's looking Spicy!",
  'sound_ext': 'wav'},
 '116': {'id': 116,
  'name': 'No_Chill',
  'label': 'No Chill!',
  'message': 'This guy has no chill',
  'sound_ext': 'wav'},
 '117': {'id': 117,
  'name': 'Lets_Play_Dota',
  'label': "Let's Play Dota",
  'message': "Let's Play Some Dota",
  'sound_ext': 'wav'},
 '118': {'id': 118,
  'name': 'Waow',
  'all_chat': True,
  'label': 'Waow',
  'message': 'Waow',
  'sound_ext': 'wav'},
 '119': {'id': 119,
  'name': 'What_Just_Happened',
  'label': 'What Just Happened?',
  'message': "I can't believe what we're seeing. What just happened?",
  'sound_ext': 'wav'},
 '120': {'id': 120,
  'name': 'Youre_a_Hero',
  'label': "You're a Goddamn Hero!",
  'message': "You're a goddamn hero!",
  'sound_ext': 'wav'},
 '121': {'id': 121,
  'name': 'All_Dead',
  'label': 'All Dead',
  'message': "They're all dead!",
  'sound_ext': 'wav'},
 '122': {'id': 122,
  'name': 'Ding_Ding_Ding',
  'all_chat': True,
  'label': 'Ding Ding Ding!',
  'message': 'Ding Ding Ding Mother******',
  'sound_ext': 'wav'},
 '131': {'id': 131,
  'name': 'Bockbock',
  'label': 'Bock bock',
  'message': 'Bock bock',
  'sound_ext': 'wav'},
 '132': {'id': 132,
  'name': 'Kiss',
  'label': 'Kiss',
  'message': 'Kiss',
  'sound_ext': 'wav'},
 '133': {'id': 133,
  'name': 'Ow',
  'label': 'Oww',
  'message': 'Oww',
  'sound_ext': 'wav'},
 '134': {'id': 134,
  'name': 'Party_Horn',
  'label': 'Party horn',
  'message': 'Party horn',
  'sound_ext': 'wav'},
 '135': {'id': 135,
  'name': 'Snore',
  'label': 'Snore',
  'message': 'Snore',
  'sound_ext': 'wav'},
 '136': {'id': 136,
  'name': 'Yahoo',
  'label': 'Yahoo',
  'message': 'Yahoo',
  'sound_ext': 'wav'},
 '137': {'id': 137,
  'name': 'Happy_Tree',
  'image': 'sprays/liltree_happy_spray_icon.png'},
 '138': {'id': 138,
  'name': 'High_Five',
  'image': 'sprays/furbolg_highfive_spray_icon.png'},
 '139': {'id': 139,
  'name': 'Zen',
  'image': 'sprays/monkey_zen_spray_icon.png'},
 '140': {'id': 140,
  'name': 'Thumbs_Up',
  'image': 'sprays/tide_thumbsup_spray_icon.png'},
 '141': {'id': 141, 'name': 'Funny', 'image': 'sprays/lion_xd_spray_icon.png'},
 '142': {'id': 142, 'name': 'Cry', 'image': 'sprays/bear_cry_spray_icon.png'},
 '143': {'id': 143,
  'name': 'Shrug',
  'image': 'sprays/sf_shrug_spray_icon.png'},
 '144': {'id': 144,
  'name': 'Sad_Tree',
  'image': 'sprays/liltree_sad_spray_icon.png'},
 '145': {'id': 145,
  'name': 'Angry',
  'image': 'sprays/lina_angry_spray_icon.png'},
 '146': {'id': 146,
  'name': 'Question',
  'image': 'sprays/shaker_confus_spray_icon.png'},
 '147': {'id': 147,
  'name': 'Shhh',
  'image': 'sprays/mirana_shh_spray_icon.png'},
 '148': {'id': 148,
  'name': 'Nervous',
  'image': 'sprays/naturesprophet_o_o_spray_icon.png'},
 '149': {'id': 149,
  'name': 'Thinking',
  'image': 'sprays/invoker_smart_spray_icon.png'},
 '150': {'id': 150,
  'name': 'Just_Right',
  'image': 'sprays/pudge_nailedit_spray_icon.png'},
 '151': {'id': 151,
  'name': 'Whoa',
  'image': 'sprays/monkeyking_monkeychamp_spray_icon.png'},
 '152': {'id': 152,
  'name': 'Easiest_Money',
  'all_chat': True,
  'label': 'Easiest Money',
  'message': 'Easiest money of my life!',
  'sound_ext': 'wav'},
 '153': {'id': 153,
  'name': 'Echo_Slama_Jama',
  'all_chat': True,
  'label': 'Echo Slamma Jamma',
  'message': 'Echo Slamma Jamma!',
  'sound_ext': 'wav'},
 '154': {'id': 154,
  'name': 'Next_Level',
  'all_chat': True,
  'label': 'Next Level',
  'message': 'The next level play!',
  'sound_ext': 'wav'},
 '155': {'id': 155,
  'name': 'Oy_Oy_Oy',
  'all_chat': True,
  'label': 'Oyoy oy oy',
  'message': 'Oyoy oy oy, oy, oy, oy Oy OY!',
  'sound_ext': 'wav'},
 '156': {'id': 156,
  'name': 'Lakad_Matataaaag',
  'all_chat': True,
  'label': 'Lakad Matataaaag!',
  'message': 'Lakad Matataaaag! Normalin Normalin.',
  'sound_ext': 'wav'},
 '157': {'id': 157,
  'name': 'FavoriteTeam',
  'label': 'Favorite Team Spray',
  'image': 'sprays/favorite_team_%d.png'},
 '158': {'id': 158,
  'name': 'Greevil_Laughter',
  'all_chat': True,
  'label': 'Greevil Laughter',
  'message': 'Greevil Laughter',
  'sound_ext': 'wav'},
 '159': {'id': 159,
  'name': 'Sparkling_Celebration',
  'label': 'Sparkling Celebration',
  'message': 'Sparkling Celebration',
  'sound_ext': 'wav'},
 '160': {'id': 160,
  'name': 'Frostivus_Magic',
  'all_chat': True,
  'label': 'Frostivus Magic',
  'message': 'Frostivus Magic',
  'sound_ext': 'wav'},
 '161': {'id': 161,
  'name': 'Sleighbells',
  'label': 'Sleighbells',
  'message': 'Sleighbells',
  'sound_ext': 'wav'},
 '162': {'id': 162,
  'name': 'NewBloom_Ceremonial_Drums',
  'label': 'Ceremonial Drums',
  'message': 'Ceremonial Drums',
  'sound_ext': 'wav'},
 '163': {'id': 163,
  'name': 'NewBloom_Oink_Oink',
  'label': 'Oink Oink!',
  'message': 'Oink Oink!',
  'sound_ext': 'wav'},
 '164': {'id': 164,
  'name': 'NewBloom_Celebratory_Gong',
  'all_chat': True,
  'label': 'Celebratory Gong',
  'message': 'Celebratory Gong',
  'sound_ext': 'wav'},
 '165': {'id': 165,
  'name': 'Kooka_Laugh',
  'label': 'Kookaburra Laugh',
  'message': 'Kookaburra Laugh',
  'sound_ext': 'wav'},
 '166': {'id': 166,
  'name': 'Monkey_Business',
  'label': 'Monkey Business',
  'message': 'Monkey Business',
  'sound_ext': 'wav'},
 '167': {'id': 167,
  'name': 'Orangutan_Kiss',
  'label': 'Sloppy Orangutan Kiss',
  'message': 'Sloppy Orangutan Kiss',
  'sound_ext': 'wav'},
 '168': {'id': 168,
  'name': 'Mosquito_Buzz',
  'label': 'Mosquito Buzz',
  'message': 'Mosquito Buzz',
  'sound_ext': 'wav'},
 '169': {'id': 169,
  'name': 'Crowd_Groan',
  'label': 'Crowd Groan',
  'message': 'Crowd Groan',
  'sound_ext': 'wav'},
 '170': {'id': 170,
  'name': 'Head_Bonk',
  'label': 'Head Bonk',
  'message': 'Head Bonk',
  'sound_ext': 'wav'},
 '171': {'id': 171,
  'name': 'Record_Scratch',
  'label': 'Record Scratch',
  'message': 'Record Scratch',
  'sound_ext': 'wav'},
 '172': {'id': 172,
  'name': 'Ta_Daaaaaa',
  'label': 'Ta Daaaaaa',
  'message': 'Ta Daaaaaa',
  'sound_ext': 'wav'},
 '173': {'id': 173,
  'name': 'Ay_Ay_Ay',
  'label': 'Ай-ай-ай-ай-ай',
  'message': 'Ай-ай-ай-ай-ай, что сейчас произошло',
  'sound_ext': 'wav'},
 '174': {'id': 174,
  'name': 'Ehto_G_G',
  'label': 'Это ГГ',
  'message': 'Это ГГ',
  'sound_ext': 'wav'},
 '175': {'id': 175,
  'name': 'Oy_Oy_Bezhat',
  'label': 'Ой-ой-ой-ой-ой, бежать!',
  'message': 'Ой-ой-ой-ой-ой, бежать!',
  'sound_ext': 'wav'},
 '176': {'id': 176,
  'name': 'Eto_Sochno',
  'all_chat': True,
  'label': 'Как же это сочно, ах!',
  'message': 'Как же это сочно, ах!',
  'sound_ext': 'wav'},
 '177': {'id': 177,
  'name': 'Da_Da_Da_Nyet',
  'all_chat': True,
  'label': 'Да? Да? Да? Нет.',
  'message': 'Да? Да? Да? Нет.',
  'sound_ext': 'wav'},
 '178': {'id': 178,
  'name': 'Wot_Eto_Bru',
  'label': 'Вот Это Врыв!',
  'message': 'Вот Это Врыв!',
  'sound_ext': 'wav'},
 '179': {'id': 179,
  'name': 'Kreasa_Kreasa',
  'label': 'Резать Резать Резать Резать',
  'message': 'Резать Резать Резать Резать',
  'sound_ext': 'wav'},
 '180': {'id': 180,
  'name': 'Eto_Nenormalno',
  'label': 'Это ненормально, это нечестно!',
  'message': 'Это ненормально, это нечестно!',
  'sound_ext': 'wav'},
 '181': {'id': 181,
  'name': 'Krasavchik',
  'label': 'Красавчик!',
  'message': 'Красавчик!',
  'sound_ext': 'wav'},
 '182': {'id': 182,
  'name': 'Eto_Prosto_Netchto',
  'all_chat': True,
  'label': 'Это. Просто. Нечто.',
  'message': 'Это. Просто. Нечто.',
  'sound_ext': 'wav'},
 '183': {'id': 183,
  'name': 'Zhil_Do_Konsta',
  'label': 'Как Герой',
  'message': 'Жил до конца, умер как герой',
  'sound_ext': 'wav'},
 '190': {'id': 190,
  'name': 'Goodness_Gracious',
  'all_chat': True,
  'label': 'Goodness Gracious',
  'message': 'Sir Chief. Goodness Gracious Papable.',
  'sound_ext': 'wav'},
 '191': {'id': 191,
  'name': 'Nakupuuu',
  'all_chat': True,
  'label': 'NAKUPUU',
  'message': 'NAKUPUU',
  'sound_ext': 'wav'},
 '192': {'id': 192,
  'name': 'Whats_Cooking',
  'all_chat': True,
  'label': "What's Cooking",
  'message': "You know what's cooking? BOOM!",
  'sound_ext': 'wav'},
 '193': {'id': 193,
  'name': 'Eughahaha_Aah_Ha_Ha_Ha_Ha',
  'all_chat': True,
  'label': 'Eughahaha Aah Ha Ha Ha Ha',
  'message': 'Eughahaha Aah Ha Ha Ha Ha',
  'sound_ext': 'wav'},
 '194': {'id': 194,
  'name': 'TI9_GlaDOS_Estimate_99',
  'all_chat': True,
  'label': '99% Probability of Winning.',
  'message': '99% Probability of Winning.',
  'sound_ext': 'wav'},
 '195': {'id': 195,
  'name': 'TI9_GlaDOS_Disappointed',
  'label': "I'm Just Disappointed",
  'message': "I'm not angry, I'm Just Disappointed",
  'sound_ext': 'wav'},
 '196': {'id': 196,
  'name': 'TI9_GlaDOS_Estimate_1',
  'all_chat': True,
  'label': '1% Probability of Winning.',
  'message': '1% Probability of Winning.',
  'sound_ext': 'wav'},
 '197': {'id': 197,
  'name': 'TI9_GlaDOS_Estimate_17',
  'all_chat': True,
  'label': '17% Probability of Winning.',
  'message': '17% Probability of Winning.',
  'sound_ext': 'wav'},
 '199': {'id': 199,
  'name': 'TI9_GlaDOS_Excellent_Work',
  'all_chat': True,
  'label': 'Excellent Work',
  'message': 'Once again, excellent work',
  'sound_ext': 'wav'},
 '200': {'id': 200,
  'name': 'TI9_GlaDOS_The_Point',
  'all_chat': True,
  'label': 'The Point',
  'message': "I'm not sure what the point of that was",
  'sound_ext': 'wav'},
 '202': {'id': 202,
  'name': 'Commend_This_Man',
  'label': 'Commend this man',
  'message': 'Commend this man, immediately.',
  'sound_ext': 'wav'},
 '203': {'id': 203,
  'name': 'Slacks_OMG',
  'all_chat': True,
  'label': 'Oh My God',
  'message': 'Oh My God! Never in all my years as a caster',
  'sound_ext': 'wav'},
 '204': {'id': 204,
  'name': 'TI9_GlaDOS_That_Happened',
  'all_chat': True,
  'label': 'That Just Happened',
  'message': 'That Just Happened',
  'sound_ext': 'wav'},
 '211': {'id': 211,
  'name': 'Ni_Qi_Bu_Qi',
  'all_chat': True,
  'label': '你气不气?',
  'message': '你气不气?',
  'sound_ext': 'wav'},
 '212': {'id': 212,
  'name': 'Zai_Jian_Le_Bao_Bei',
  'all_chat': True,

In [ ]:
def parsear_partida(match_id):
  job = realiza_request(f"https://api.opendota.com/api/request/{match_id}", method='post')
  jobId = job['job']['jobId']
  acabou = realiza_request(f"https://api.opendota.com/api/request/{jobId}")
  return acabou

In [ ]:
parsear_partida(8840133635)

{'id': 362558313,
 'type': 'parse',
 'timestamp': '2026-06-07T18:49:09.357Z',
 'attempts': 1,
 'data': {'match_id': 8840133635},
 'next_attempt_time': '2026-06-07T18:49:09.357Z',
 'priority': -2,
 'job_key': 'parse:8840133635',
 'jobId': 362558313}

In [ ]:
parsear_partida(8840152578)

{'id': 362558326,
 'type': 'parse',
 'timestamp': '2026-06-07T18:49:11.657Z',
 'attempts': 1,
 'data': {'match_id': 8840152578},
 'next_attempt_time': '2026-06-07T18:49:11.657Z',
 'priority': -2,
 'job_key': 'parse:8840152578',
 'jobId': 362558326}

In [10]:
def consolidar_json_players(caminho_pasta="info_players"):
    # Lista para armazenar os dados de cada jogador
    lista_dados = []
    
    # Verifica se a pasta existe
    if not os.path.exists(caminho_pasta):
        print(f"Erro: A pasta '{caminho_pasta}' não foi encontrada.")
        return None

    # Lista todos os arquivos dentro da pasta
    arquivos = os.listdir(caminho_pasta)
    
    # Filtra apenas os arquivos que terminam com .json
    arquivos_json = [f for f in arquivos if f.endswith('.json')]
    
    print(f"Encontrados {len(arquivos_json)} arquivos JSON na pasta '{caminho_pasta}'.")

    # Loop para ler arquivo por arquivo
    for nome_arquivo in arquivos_json:
        caminho_completo = os.path.join(caminho_pasta, nome_arquivo)
        
        try:
            with open(caminho_completo, 'r', encoding='utf-8') as arquivo:
                dados_jogador = json.load(arquivo)
                
                # Se o JSON for um dicionário único (um jogador por arquivo)
                if isinstance(dados_jogador, dict):
                    lista_dados.append(dados_jogador)
                # Se o JSON já for uma lista de dicionários dentro do arquivo
                elif isinstance(dados_jogador, list):
                    lista_dados.extend(dados_jogador)
                    
        except Exception as e:
            print(f"Erro ao ler o arquivo {nome_arquivo}: {e}")

    # Cria o DataFrame a partir da lista consolidada
    if lista_dados:
        df = pd.DataFrame(lista_dados)
        print("DataFrame gerado com sucesso!")
        return df
    else:
        print("Nenhum dado válido foi extraído.")
        return pd.DataFrame()

In [16]:

df_players = consolidar_json_players()

df_players

Encontrados 4465 arquivos JSON na pasta 'info_players'.
DataFrame gerado com sucesso!

,profile,rank_tier,leaderboard_rank,computed_mmr,computed_mmr_turbo,aliases
0,"{'account_id': 1455598719, 'personaname': 'dis...",24.0,NaN,3960.16,3975.22,"[{'personaname': '<3', 'name_since': '2025-12-..."
1,"{'account_id': 1674581159, 'personaname': 'тру...",34.0,NaN,3910.13,3998.99,"[{'personaname': 'dantezz prime蜘蛛', 'name_sinc..."
2,"{'account_id': 1097934237, 'personaname': 'Dum...",73.0,NaN,3794.48,NaN,"[{'personaname': '1110100011111000000110111', ..."
3,"{'account_id': 1600007774, 'personaname': 'Лоб...",24.0,NaN,3842.28,3993.91,"[{'personaname': '69 |dekty', 'name_since': '2..."
4,"{'account_id': 114374024, 'personaname': 'Calm...",80.0,2989.0,3863.99,4071.09,"[{'personaname': '1 BY 1', 'name_since': '2025..."
...,...,...,...,...,...,...
4460,"{'account_id': 408562539, 'personaname': 'Moty...",42.0,NaN,4016.85,3949.21,[]
4461,"{'account_id': 187123736, 'personaname': 'six-...",80.0,132.0,NaN,NaN,"[{'personaname': '0pen', 'name_since': '2026-0..."
4462,"{'account_id': 1255505146, 'personaname': 'iwa...",73.0,NaN,4322.15,NaN,"[{'personaname': 'full lock in', 'name_since':..."
4463,"{'account_id': 1919826264, 'personaname': 'све...",43.0,NaN,3877.62,NaN,[]
4464,"{'account_id': 1463561231, 'personaname': 'Sai...",63.0,NaN,4119.05,3980.69,"[{'personaname': '123', 'name_since': '2025-02..."

In [17]:
df_profile_expandido = pd.json_normalize(df_players['profile'])

# 3. Junta o novo DataFrame expandido com o original e remove a coluna de dicionários original
df_players = pd.concat([df_profile_expandido, df_players.drop(columns=['profile'])], axis=1)

# Visualizando o resultado
df_players

,account_id,personaname,name,plus,cheese,steamid,avatar,avatarmedium,avatarfull,profileurl,...,loccountrycode,status,fh_unavailable,is_contributor,is_subscriber,rank_tier,leaderboard_rank,computed_mmr,computed_mmr_turbo,aliases
0,1455598719,dissmilateq,dissmilateq,False,0,76561199415864447,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://steamcommunity.com/id/dissmilateqq/,...,JP,NaN,False,False,False,24.0,NaN,3960.16,3975.22,"[{'personaname': '<3', 'name_since': '2025-12-..."
1,1674581159,трусики мерксли,whydantezzcry,True,0,76561199634846887,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://steamcommunity.com/profiles/7656119963...,...,ES,NaN,False,False,False,34.0,NaN,3910.13,3998.99,"[{'personaname': 'dantezz prime蜘蛛', 'name_sinc..."
2,1097934237,Dummheit,vetmo,False,0,76561199058199965,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://steamcommunity.com/id/fuckfuckfuckxdx/,...,JP,NaN,False,False,False,73.0,NaN,3794.48,NaN,"[{'personaname': '1110100011111000000110111', ..."
3,1600007774,Лобанов,Dekty,False,0,76561199560273502,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://steamcommunity.com/profiles/7656119956...,...,US,NaN,False,False,False,24.0,NaN,3842.28,3993.91,"[{'personaname': '69 |dekty', 'name_since': '2..."
4,114374024,Calm,AN****❧,False,0,76561198074639752,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://steamcommunity.com/profiles/7656119807...,...,PE,NaN,False,False,False,80.0,2989.0,3863.99,4071.09,"[{'personaname': '1 BY 1', 'name_since': '2025..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4460,408562539,MotyaRolla,MotyaRolla,False,0,76561198368828267,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://steamcommunity.com/id/motyarolla/,...,AR,NaN,False,False,False,42.0,NaN,4016.85,3949.21,[]
4461,187123736,six-six-sick,Norma,True,0,76561198147389464,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://steamcommunity.com/id/NeeNorma/,...,UA,NaN,False,False,False,80.0,132.0,NaN,NaN,"[{'personaname': '0pen', 'name_since': '2026-0..."
4462,1255505146,iwalkwhenitalk</3,w1lfychyo,True,0,76561199215770874,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://steamcommunity.com/profiles/7656119921...,...,CA,NaN,False,False,False,73.0,NaN,4322.15,NaN,"[{'personaname': 'full lock in', 'name_since':..."
4463,1919826264,светящийся пацан - он светит,footballist,False,0,76561199880091992,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://steamcommunity.com/profiles/7656119988...,...,NaN,NaN,False,False,False,43.0,NaN,3877.62,NaN,[]
4464,1463561231,Saint-Saëns,saintsaens,False,0,76561199423826959,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://steamcommunity.com/profiles/7656119942...,...,LC,NaN,False,False,False,63.0,NaN,4119.05,3980.69,"[{'personaname': '123', 'name_since': '2025-02..."

In [18]:
df_players.to_csv("info_players/topPlayersInfo.csv", index=False)

In [19]:
#full_history_time,last_match_time,profile_time,rank_tier_time,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
#status,is_contributor,is_subscriber,rank_tier,leaderboard_rank,computed_mmr,computed_mmr_turbo,aliases

colunas_desejadas = [
    'account_id', 
    'full_history_time', 
    'last_match_time', 
    'profile_time', 
    'rank_tier_time', 
    'country_code', 
    'fantasy_role', 
    'team_id', 
    'team_name', 
    'team_tag', 
    'is_locked', 
    'is_pro', 
    'locked_until'
]

df_players_all_info = pd.merge(
    df_players, 
    topPlayers[colunas_desejadas], 
    on='account_id', 
    how='left'
)
df_players_all_info

,account_id,personaname,name,plus,cheese,steamid,avatar,avatarmedium,avatarfull,profileurl,...,profile_time,rank_tier_time,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,1455598719,dissmilateq,dissmilateq,False,0,76561199415864447,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://avatars.steamstatic.com/e0bced287c6c0a...,https://steamcommunity.com/id/dissmilateqq/,...,2026-05-14T22:53:53.444Z,2026-05-26T04:59:59.067Z,NaN,1.0,9834639.0,I Hate Women,IHW,NaN,NaN,NaN
1,1674581159,трусики мерксли,whydantezzcry,True,0,76561199634846887,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://avatars.steamstatic.com/8d97764078705b...,https://steamcommunity.com/profiles/7656119963...,...,2026-05-11T00:19:52.865Z,2026-06-07T13:43:04.511Z,ru,1.0,9383049.0,98squad,98,NaN,NaN,NaN
2,1097934237,Dummheit,vetmo,False,0,76561199058199965,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://avatars.steamstatic.com/e00771fb3aac63...,https://steamcommunity.com/id/fuckfuckfuckxdx/,...,2026-05-24T14:25:49.611Z,2026-06-01T22:44:34.227Z,by,1.0,0.0,paris x gen,PXG,NaN,NaN,NaN
3,1600007774,Лобанов,Dekty,False,0,76561199560273502,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://avatars.steamstatic.com/2c87825b3025b6...,https://steamcommunity.com/profiles/7656119956...,...,2026-05-10T11:55:51.654Z,2026-05-29T14:25:03.812Z,NaN,1.0,10136414.0,Team Nakurilis,BRUD999,NaN,NaN,NaN
4,114374024,Calm,AN****❧,False,0,76561198074639752,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://avatars.steamstatic.com/8d7bd0ec0879dd...,https://steamcommunity.com/profiles/7656119807...,...,2026-05-19T21:48:56.558Z,2026-04-13T02:31:17.485Z,pe,2.0,8318424.0,COCHLEA,CH,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4460,408562539,MotyaRolla,MotyaRolla,False,0,76561198368828267,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://avatars.steamstatic.com/f4f2fc58620a76...,https://steamcommunity.com/id/motyarolla/,...,2026-05-18T16:12:17.413Z,2026-06-06T01:09:29.106Z,us,3.0,10145397.0,Makoto,MKT,NaN,NaN,NaN
4461,187123736,six-six-sick,Norma,True,0,76561198147389464,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://avatars.steamstatic.com/dca546d8912151...,https://steamcommunity.com/id/NeeNorma/,...,2026-05-19T16:47:50.849Z,2026-05-07T18:56:38.657Z,ua,1.0,10150889.0,Team Jazz,Jazz,NaN,NaN,NaN
4462,1255505146,iwalkwhenitalk</3,w1lfychyo,True,0,76561199215770874,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://avatars.steamstatic.com/d639c0fc7bc89f...,https://steamcommunity.com/profiles/7656119921...,...,2026-05-23T22:19:11.886Z,2026-05-31T16:41:32.119Z,NaN,1.0,10144048.0,Averiour,AV3,NaN,NaN,NaN
4463,1919826264,светящийся пацан - он светит,footballist,False,0,76561199880091992,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://avatars.steamstatic.com/648b9749a14b9e...,https://steamcommunity.com/profiles/7656119988...,...,2026-05-07T15:51:23.592Z,2026-04-13T23:40:35.390Z,NaN,1.0,9938641.0,спортсмены,SPORT,NaN,NaN,NaN
4464,1463561231,Saint-Saëns,saintsaens,False,0,76561199423826959,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://avatars.steamstatic.com/399ac1d7ca5e8e...,https://steamcommunity.com/profiles/7656119942...,...,2026-05-17T22:53:18.752Z,2026-06-06T21:35:25.788Z,ru,1.0,9616402.0,rakov,Allah,NaN,NaN,NaN

In [20]:
df_players_all_info.to_csv("topPlayersAllInfo.csv", index=False)

In [ ]:
def consolidar_partidas_com_id(caminho_pasta="match_players"):
    lista_dados = []
    
    # Verifica se a pasta existe
    if not os.path.exists(caminho_pasta):
        print(f"Erro: A pasta '{caminho_pasta}' não foi encontrada.")
        return None

    arquivos = os.listdir(caminho_pasta)
    arquivos_json = [f for f in arquivos if f.endswith('.json')]
    
    print(f"Encontrados {len(arquivos_json)} arquivos JSON na pasta '{caminho_pasta}'.")

    for nome_arquivo in arquivos_json:
        # Extração do ID do jogador a partir do nome do arquivo
        # Pega "id1922332243.json", remove "id" e remove ".json", sobrando apenas "1922332243"
        player_id_str = nome_arquivo.replace("id", "").replace(".json", "")
        
        caminho_completo = os.path.join(caminho_pasta, nome_arquivo)
        
        try:
            with open(caminho_completo, 'r', encoding='utf-8') as arquivo:
                partidas = json.load(arquivo)
                
                # Garante que o JSON lido é de fato uma lista de partidas
                if isinstance(partidas, list):
                    for partida in partidas:
                        # Injeta o ID do jogador dentro do dicionário da partida atual
                        partida['account_id'] = player_id_str
                        
                        # Adiciona o dicionário modificado na nossa lista principal
                        lista_dados.append(partida)
                        
        except Exception as e:
            print(f"Erro ao ler o arquivo {nome_arquivo}: {e}")

    # Cria o DataFrame
    if lista_dados:
        df_partidas = pd.DataFrame(lista_dados)
        
        # Converte a coluna account_id para numérico (inteiro)
        # Isso é crucial para bater certinho na hora de fazer o "merge" com os outros dados depois
        df_partidas['account_id'] = pd.to_numeric(df_partidas['account_id'])
        
        print("DataFrame de partidas gerado com sucesso!")
        return df_partidas
    else:
        print("Nenhum dado válido foi extraído.")
        return pd.DataFrame()

In [ ]:
df_match_history = consolidar_partidas_com_id()
df_match_history

In [ ]:
df_match_history.to_csv("partidas_jogador.csv", index=False)

In [ ]:
df_matches = pd.read_csv("PlayerMatch.csv")
df_matches

,match_id,player_slot,radiant_win,duration,game_mode,lobby_type,hero_id,start_time,version,kills,deaths,assists,average_rank,leaver_status,party_size,hero_variant,account_id
0,8743154424,4,False,2747,22,7,81,1774439876,NaN,11,11,13,24.0,0,3.0,0.0,1455598719
1,8743073787,4,False,3043,22,7,104,1774435740,NaN,23,5,12,23.0,0,3.0,0.0,1455598719
2,8664375730,128,True,3187,22,7,17,1769363965,NaN,15,8,13,23.0,0,NaN,2.0,1455598719
3,8664307275,132,True,2405,22,7,17,1769360910,NaN,7,6,7,22.0,0,1.0,2.0,1455598719
4,8664244435,131,True,2141,22,7,126,1769358225,NaN,7,7,2,23.0,0,1.0,1.0,1455598719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089038,7766877401,129,False,2494,4,0,94,1717073073,NaN,6,5,10,NaN,0,NaN,NaN,1463561231
13089039,7766784981,129,False,2605,4,0,13,1717070142,NaN,12,8,13,NaN,0,NaN,NaN,1463561231
13089040,7766690139,129,False,2787,4,0,106,1717066784,NaN,10,6,12,25.0,0,NaN,NaN,1463561231
13089041,7766603163,132,False,2009,4,0,10,1717063177,NaN,21,1,9,NaN,0,NaN,NaN,1463561231
13089042,7752130946,129,False,2001,22,0,41,1716481525,NaN,13,6,12,31.0,0,NaN,NaN,1463561231

In [ ]:
df_matches = df_matches[["match_id", "account_id"]]
df_matches.to_csv("onlyMatchPlayerID.csv", index=False)

In [11]:
match_id = 6772043743
res = realiza_request(f"https://api.opendota.com/api/matches/{match_id}")

In [12]:
res

{'match_id': 6772043743,
 'barracks_status_dire': 51,
 'barracks_status_radiant': 63,
 'chat': [{'time': -86,
   'type': 'chatwheel',
   'key': '71',
   'slot': 8,
   'player_slot': 131},
  {'time': -80,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': -79,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': -75,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': -75,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': -67, 'type': 'chat', 'key': 'SEC', 'slot': 3, 'player_slot': 3},
  {'time': -67, 'type': 'chat', 'key': 'fps', 'slot': 3, 'player_slot': 3},
  {'time': -67,
   'type': 'chatwheel',
   'key': '136001',
   'slot': 1,
   'player_slot': 1},
  {'time': -67,
   'type': 'chatwheel',
   'key': '136001',
   'slot': 1,
   'player_slot': 1},
  {'time': -67, 'type': 'chat', 'key': 'g', 'slot': 3, 'player_slot': 3},
  {'time': -67, 'type': 'chat', 'key': 'g', 'slot': 8, 'player_slot': 131},
  {'time': -52,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': -52,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': -42,
   'type': 'chatwheel',
   'key': '71',
   'slot': 8,
   'player_slot': 131},
  {'time': -42,
   'type': 'chatwheel',
   'key': '71',
   'slot': 8,
   'player_slot': 131},
  {'time': -37,
   'type': 'chatwheel',
   'key': '444',
   'slot': 9,
   'player_slot': 132},
  {'time': -36,
   'type': 'chatwheel',
   'key': '444',
   'slot': 9,
   'player_slot': 132},
  {'time': 6,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 6,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 27,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': 27,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': 32,
   'type': 'chatwheel',
   'key': '71',
   'slot': 7,
   'player_slot': 130},
  {'time': 116,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': 116,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': 213,
   'type': 'chatwheel',
   'key': '23007',
   'slot': 7,
   'player_slot': 130},
  {'time': 279,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': 279,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': 364,
   'type': 'chatwheel',
   'key': '491',
   'slot': 6,
   'player_slot': 129},
  {'time': 574,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 575,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 602,
   'type': 'chatwheel',
   'key': '459',
   'slot': 3,
   'player_slot': 3},
  {'time': 603,
   'type': 'chatwheel',
   'key': '453',
   'slot': 1,
   'player_slot': 1},
  {'time': 677,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 677,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 1091,
   'type': 'chatwheel',
   'key': '66002',
   'slot': 0,
   'player_slot': 0},
  {'time': 1109,
   'type': 'chatwheel',
   'key': '25005',
   'slot': 9,
   'player_slot': 132},
  {'time': 1109,
   'type': 'chatwheel',
   'key': '25006',
   'slot': 9,
   'player_slot': 132},
  {'time': 1111,
   'type': 'chatwheel',
   'key': '458',
   'slot': 1,
   'player_slot': 1},
  {'time': 1272,
   'type': 'chatwheel',
   'key': '444',
   'slot': 9,
   'player_slot': 132},
  {'time': 1294,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 1295,
   'type': 'chatwheel',
   'key': '25001',
   'slot': 9,
   'player_slot': 132},
  {'time': 1390,
   'type': 'chatwheel',
   'key': '71',
   'slot': 6,
   'player_slot': 129},
  {'time': 1391,
   'type': 'chatwheel',
   'key': '71',
   'slot': 6,
   'player_slot': 129},
  {'time': 1407,
   'type': 'chatwheel',
   'key': '71',
   'slot': 6,
   'player_slot': 129},
  {'time': 1549,
   'type': 'chatwheel',
   'key': '453',
   'slot': 1,
   'player_slot': 1},
  {'time': 1551,
   'type': 'chatwheel',
   'key': '453',
   'slot': 1,
   'player_slot': 1},
  {'time': 1575, 'type': 'chat', 'key': 'gg', 'slot': 6, 'player_slot': 129},
  {'time': 1578, 'type': 'chat', 'key': 'gg', 'slot': 8, 'player_slot': 131},
  {'time': 1579, 'type': 'chat', 'key': 'gg', 'slot': 1, 'player_slot': 1},
  {'time': 1581, 'type': 'chat', 'key': 'gg', 'slot': 0, 'player_slot': 0},
  {'time': 1589, 'type': 'chat', 'key': 'gg', 'slot': 2, 'player_slot': 2}],
 'cluster': 151,
 'cosmetics': {'647': 130,
  '684': 131,
  '4648': 2,
  '4794': 132,
  '4885': 2,
  '4887': 2,
  '4998': 132,
  '5256': 130,
  '5533': 131,
  '5534': 131,
  '5734': 128,
  '5735': 128,
  '5736': 128,
  '5737': 128,
  '5738': 128,
  '7240': 2,
  '7741': 132,
  '7814': 2,
  '7938': 129,
  '8630': 129,
  '8679': 129,
  '9214': 130,
  '9318': 3,
  '9558': 131,
  '10098': 0,
  '10144': 4,
  '10147': 129,
  '11341': 129,
  '11368': 131,
  '12147': 128,
  '12540': 3,
  '13122': 130,
  '13539': 3,
  '13772': 3,
  '13775': 1,
  '13810': 1,
  '13816': 132,
  '14442': 130,
  '14443': 130,
  '14444': 130,
  '14445': 130,
  '14446': 130,
  '14447': 130,
  '14448': 130,
  '14752': 3,
  '14994': 129,
  '17664': 0,
  '18496': 129,
  '18498': 129,
  '18499': 129,
  '18509': 2,
  '18684': 1,
  '19264': 131,
  '19328': 2,
  '19347': 0,
  '19349': 0,
  '19350': 0,
  '19351': 0,
  '19522': 132,
  '22847': 131,
  '23237': 132,
  '23715': 3},
 'dire_score': 11,
 'dire_team_id': 8169775,
 'draft_timings': [{'order': 1,
   'pick': False,
   'active_team': 3,
   'hero_id': 61,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 2,
   'pick': False,
   'active_team': 2,
   'hero_id': 77,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 3,
   'pick': False,
   'active_team': 2,
   'hero_id': 58,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 4,
   'pick': False,
   'active_team': 2,
   'hero_id': 65,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 5,
   'pick': True,
   'active_team': 2,
   'hero_id': 66,
   'player_slot': 0,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 6,
   'pick': True,
   'active_team': 2,
   'hero_id': 85,
   'player_slot': 6,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 7,
   'pick': True,
   'active_team': 2,
   'hero_id': 25,
   'player_slot': 9,
   'extra_time': 130,
   'total_time_taken': 0},
  {'order': 8,
   'pick': True,
   'active_team': 2,
   'hero_id': 136,
   'player_slot': 1,
   'extra_time': 117,
   'total_time_taken': 14},
  {'order': 9,
   'pick': False,
   'active_team': 2,
   'hero_id': 11,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 4},
  {'order': 10,
   'pick': False,
   'active_team': 3,
   'hero_id': 41,
   'player_slot': None,
   'extra_time': 117,
   'total_time_taken': 11},
  {'order': 11,
   'pick': False,
   'active_team': 2,
   'hero_id': 68,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 1},
  {'order': 12,
   'pick': False,
   'active_team': 3,
   'hero_id': 10,
   'player_slot': None,
   'extra_time': 117,
   'total_time_taken': 1},
  {'order': 13,
   'pick': False,
   'active_team': 2,
   'hero_id': 109,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 5},
  {'order': 14,
   'pick': False,
   'active_team': 3,
   'hero_id': 43,
   'player_slot': None,
   'extra_time': 113,
   'total_time_taken': 47},
  {'order': 15,
   'pick': True,
   'active_team': 3,
   'hero_id': 5,
   'player_slot': 5,
   'extra_time': 117,
   'total_time_taken': 15},
  {'order': 16,
   'pick': True,
   'active_team': 2,
   'hero_id': 46,
   'player_slot': 3,
   'extra_time': 117,
   'total_time_taken': 3},
  {'order': 17,
   'pick': True,
   'active_team': 2,
   'hero_id': 38,
   'player_slot': 2,
   'extra_time': 113,
   'total_time_taken': 50},
  {'order': 18,
   'pick': True,
   'active_team': 3,
   'hero_id': 23,
   'player_slot': 7,
   'extra_time': 97,
   'total_time_taken': 94},
  {'order': 19,
   'pick': False,
   'active_team': 2,
   'hero_id': 47,
   'player_slot': None,
   'extra_time': 50,
   'total_time_taken': 14},
  {'order': 20,
   'pick': False,
   'active_team': 3,
   'hero_id': 106,
   'player_slot': None,
   'extra_time': 97,
   'total_time_taken': 8},
  {'order': 21,
   'pick': False,
   'active_team': 2,
   'hero_id': 98,
   'player_slot': None,
   'extra_time': 50,
   'total_time_taken': 23},
  {'order': 22,
   'pick': False,
   'active_team': 3,
   'hero_id': 74,
   'player_slot': None,
   'extra_time': 97,
   'total_time_taken': 3},
  {'order': 23,
   'pick': True,
   'active_team': 2,
   'hero_id': 70,
   'player_slot': 4,
   'extra_time': 50,
   'total_time_taken': 44},
  {'order': 24,
   'pick': True,
   'active_team': 3,
   'hero_id': 40,
   'player_slot': 8,
   'extra_time': 12,
   'total_time_taken': 68}],
 'duration': 1585,
 'engine': 1,
 'first_blood_time': 0,
 'game_mode': 2,
 'human_players': 10,
 'leagueid': 14552,
 'lobby_type': 1,
 'match_seq_num': 5668428961,
 'negative_votes': 0,
 'objectives': [{'time': -25,
   'type': 'CHAT_MESSAGE_FIRSTBLOOD',
   'slot': 0,
   'key': 5,
   'player_slot': 0},
  {'time': 527, 'type': 'CHAT_MESSAGE_COURIER_LOST', 'team': 0},
  {'time': 679,
   'type': 'building_kill',
   'unit': 'npc_dota_goodguys_siege',
   'key': 'npc_dota_badguys_tower1_bot'},
  {'time': 737,
   'type': 'building_kill',
   'unit': 'npc_dota_creep_goodguys_melee',
   'key': 'npc_dota_badguys_tower1_top'},
  {'time': 818, 'type': 'CHAT_MESSAGE_ROSHAN_KILL', 'team': 2},
  {'time': 819, 'type': 'CHAT_MESSAGE_AEGIS', 'slot': 4, 'player_slot': 4},
  {'time': 910,
   'type': 'building_kill',
   'unit': 'npc_dota_creep_goodguys_ranged',
   'key': 'npc_dota_badguys_tower1_mid'},
  {'time': 973,
   'type': 'building_kill',
   'unit': 'npc_dota_creep_badguys_ranged',
   'key': 'npc_dota_goodguys_tower1_bot'},
  {'time': 1016, 'type': 'CHAT_MESSAGE_COURIER_LOST', 'team': -1},
  {'time': 1027,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_templar_assassin',
   'key': 'npc_dota_badguys_tower2_top',
   'slot': 3,
   'player_slot': 3},
  {'time': 1224,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_chen',
   'key': 'npc_dota_badguys_tower2_mid',
   'slot': 0,
   'player_slot': 0},
  {'time': 1259, 'type': 'CHAT_MESSAGE_COURIER_LOST', 'team': 8},
  {'time': 1448, 'type': 'CHAT_MESSAGE_ROSHAN_KILL', 'team': 2},
  {'time': 1448,
   'type': 'CHAT_MESSAGE_AEGIS_STOLEN',
   'slot': 8,
   'player_slot': 131},
  {'time': 1547, 'type': 'CHAT_MESSAGE_COURIER_LOST', 'team': 3},
  {'time': 1570,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_beastmaster',
   'key': 'npc_dota_badguys_tower3_mid',
   'slot': 2,
   'player_slot': 2},
  {'time': 1576,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_marci',
   'key': 'npc_dota_badguys_melee_rax_mid',
   'slot': 1,
   'player_slot': 1},
  {'time': 1576,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_templar_assassin',
   'key': 'npc_dota_badguys_range_rax_mid',
   'slot': 3,
   'player_slot': 3},
  {'time': 1582,
   'type': 'building_kill',
   'unit': 'npc_dota_hero_beastmaster',
   'key': 'npc_dota_badguys_tower3_top',
   'slot': 2,
   'player_slot': 2},
  {'time': 1585,
   'type': 'building_kill',
   'unit': 'dota_unknown',
   'key': 'npc_dota_badguys_fort'}],
 'picks_bans': [{'is_pick': False, 'hero_id': 61, 'team': 0, 'order': 0},
  {'is_pick': False, 'hero_id': 58, 'team': 1, 'order': 1},
  {'is_pick': False, 'hero_id': 77, 'team': 0, 'order': 2},
  {'is_pick': False, 'hero_id': 65, 'team': 1, 'order': 3},
  {'is_pick': True, 'hero_id': 66, 'team': 0, 'order': 4},
  {'is_pick': True, 'hero_id': 85, 'team': 1, 'order': 5},
  {'is_pick': True, 'hero_id': 25, 'team': 1, 'order': 6},
  {'is_pick': True, 'hero_id': 136, 'team': 0, 'order': 7},
  {'is_pick': False, 'hero_id': 11, 'team': 0, 'order': 8},
  {'is_pick': False, 'hero_id': 41, 'team': 1, 'order': 9},
  {'is_pick': False, 'hero_id': 68, 'team': 0, 'order': 10},
  {'is_pick': False, 'hero_id': 10, 'team': 1, 'order': 11},
  {'is_pick': False, 'hero_id': 109, 'team': 0, 'order': 12},
  {'is_pick': False, 'hero_id': 43, 'team': 1, 'order': 13},
  {'is_pick': True, 'hero_id': 5, 'team': 1, 'order': 14},
  {'is_pick': True, 'hero_id': 46, 'team': 0, 'order': 15},
  {'is_pick': True, 'hero_id': 38, 'team': 0, 'order': 16},
  {'is_pick': True, 'hero_id': 23, 'team': 1, 'order': 17},
  {'is_pick': False, 'hero_id': 47, 'team': 0, 'order': 18},
  {'is_pick': False, 'hero_id': 106, 'team': 1, 'order': 19},
  {'is_pick': False, 'hero_id': 98, 'team': 0, 'order': 20},
  {'is_pick': False, 'hero_id': 74, 'team': 1, 'order': 21},
  {'is_pick': True, 'hero_id': 70, 'team': 0, 'order': 22},
  {'is_pick': True, 'hero_id': 40, 'team': 1, 'order': 23}],
 'positive_votes': 0,
 'radiant_gold_adv': [381,
  66,
  -389,
  -619,
  -684,
  -574,
  -182,
  92,
  662,
  1136,
  2354,
  2507,
  3056,
  3449,
  4424,
  4817,
  5793,
  4621,
  6418,
  5872,
  5049,
  5567,
  3832,
  4016,
  4721,
  7756,
  10967],
 'radiant_score': 30,
 'radiant_team_id': 8360138,
 'radiant_win': True,
 'radiant_xp_adv': [152,
  -62,
  -552,
  -567,
  -685,
  -988,
  -598,
  -414,
  384,
  997,
  2634,
  3066,
  3377,
  3479,
  4601,
  5681,
  6781,
  6874,
  7792,
  5947,
  5215,
  4734,
  3115,
  2406,
  4003,
  9614,
  17510],
 'skill': None,
 'start_time': 1663934110,
 'teamfights': [{'start': -40,
   'end': 22,
   'last_death': 7,
   'deaths': 4,
   'players': [{'deaths_pos': {},
     'ability_uses': {'chen_penitence': 3},
     'ability_targets': {},
     'item_uses': {'ward_sentry': 1},
     'killed': {'npc_dota_hero_crystal_maiden': 1, 'npc_dota_hero_lina': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 510,
     'healing': 0,
     'gold_delta': 511,
     'xp_delta': 73},
    {'deaths_pos': {'142': {'142': 1}},
     'ability_uses': {'marci_companion_run': 2},
     'ability_targets': {},
     'item_uses': {'tango': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 624,
     'healing': 90,
     'gold_delta': 91,
     'xp_delta': 73},
    {'deaths_pos': {'130': {'176': 1}},
     'ability_uses': {'beastmaster_wild_axes': 4},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 2},
     'killed': {'npc_dota_hero_venomancer': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 655,
     'healing': 0,
     'gold_delta': 219,
     'xp_delta': 73},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 56,
     'healing': 0,
     'gold_delta': 96,
     'xp_delta': 40},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 2, 'tango': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 480,
     'healing': 112,
     'gold_delta': 96,
     'xp_delta': 40},
    {'deaths_pos': {},
     'ability_uses': {'crystal_maiden_crystal_nova': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 291,
     'healing': 0,
     'gold_delta': 92,
     'xp_delta': 0},
    {'deaths_pos': {},
     'ability_uses': {'undying_decay': 3},
     'ability_targets': {},
     'item_uses': {'ward_sentry': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 53,
     'healing': 0,
     'gold_delta': 206,
     'xp_delta': 16},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 407,
     'healing': 0,
     'gold_delta': 174,
     'xp_delta': 125},
    {'deaths_pos': {},
     'ability_uses': {'venomancer_venomous_gale': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 317,
     'healing': 0,
     'gold_delta': 157,
     'xp_delta': 16},
    {'deaths_pos': {'138': {'136': 1}},
     'ability_uses': {'seasonal_ti11_conga_line': 2,
      'lina_light_strike_array': 1},
     'ability_targets': {},
     'item_uses': {'ward_observer': 1,
      'faerie_fire': 1,
      'tango': 1,
      'tpscroll': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 280,
     'healing': 98,
     'gold_delta': 158,
     'xp_delta': 0}]},
  {'start': 885,
   'end': 928,
   'last_death': 913,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'chen_hand_of_god': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 2, 'ward_sentry': 3},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 751,
     'gold_delta': 199,
     'xp_delta': 485,
     'xp_start': 3196,
     'xp_end': 3681},
    {'deaths_pos': {'128': {'150': 1}},
     'ability_uses': {'marci_companion_run': 2,
      'marci_grapple': 1,
      'marci_guardian': 1},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1, 'ward_dispenser': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 219,
     'healing': 248,
     'gold_delta': 62,
     'xp_delta': 30,
     'xp_start': 4847,
     'xp_end': 4877},
    {'deaths_pos': {},
     'ability_uses': {'beastmaster_wild_axes': 2,
      'beastmaster_call_of_the_wild_hawk': 1,
      'beastmaster_call_of_the_wild_boar': 1},
     'ability_targets': {},
     'item_uses': {'helm_of_the_dominator': 1, 'magic_wand': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 676,
     'healing': 271,
     'gold_delta': 251,
     'xp_delta': 692,
     'xp_start': 6839,
     'xp_end': 7531},
    {'deaths_pos': {},
     'ability_uses': {'templar_assassin_refraction': 3,
      'templar_assassin_meld': 2,
      'templar_assassin_psionic_trap': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 13, 'arcane_ring': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 595,
     'xp_delta': 580,
     'xp_start': 8353,
     'xp_end': 8932},
    {'deaths_pos': {},
     'ability_uses': {'ursa_overpower': 3,
      'ursa_enrage': 1,
      'ursa_earthshock': 2},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'diffusal_blade': 2},
     'killed': {'npc_dota_hero_venomancer': 1,
      'npc_dota_hero_crystal_maiden': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2322,
     'healing': 263,
     'gold_delta': 561,
     'xp_delta': 611,
     'xp_start': 7619,
     'xp_end': 8230},
    {'deaths_pos': {'146': {'148': 1}},
     'ability_uses': {'crystal_maiden_crystal_nova': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 484,
     'healing': 0,
     'gold_delta': 187,
     'xp_delta': 278,
     'xp_start': 3329,
     'xp_end': 3530},
    {'deaths_pos': {},
     'ability_uses': {'undying_decay': 2, 'undying_soul_rip': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 45,
     'healing': 45,
     'gold_delta': 111,
     'xp_delta': 482,
     'xp_start': 2963,
     'xp_end': 3445},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_x_marks_the_spot': 3,
      'kunkka_torrent': 2,
      'kunkka_ghostship': 1,
      'kunkka_return': 2,
      'plus_high_five': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'armlet': 6},

In [ ]:
def get_top_players_matches(ids):
  ids_lidos = []
  ids_com_erro = []
  indice=0
  try:
    for id in ids:

      info = player_matches(id)

      if info == None:
        raise Exception()
      if info == 404:
        print("id com erro 404 ou sem resposta:", id)
        ids_com_erro.append(id)
        continue
      
      with open(f'match_players/id{id}.json', 'w', encoding='utf-8') as arquivo:
        json.dump(info, arquivo, ensure_ascii=False, indent=2)
      indice+=1
      ids_lidos.append(int(id))

  except Exception as e:
    print(f"erro no id {id} de indice {indice}")
    print(e)
  finally:
    return ids_lidos, ids_com_erro