In [5]:
%pip install requests
%pip install pandas

Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.4 MB/s eta 0:00:00 MB/s eta 0:00:01
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 10.5 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 13.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [6]:
#@title Imports
from IPython.core.display import json
import requests
import pandas as pd
import time
import datetime
import json

In [7]:
topPlayers = pd.read_csv('topPlayers.csv')
topPlayers

,account_id,steamid,avatar,avatarmedium,avatarfull,profileurl,personaname,last_login,full_history_time,cheese,...,rank_tier_time,name,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,1111506,7.656120e+16,https://avatars.steamstatic.com/8c540801f27f13...,https://avatars.steamstatic.com/8c540801f27f13...,https://avatars.steamstatic.com/8c540801f27f13...,https://steamcommunity.com/id/Line/,LineDOTA2,2026-02-16T09:18:34.196Z,2026-01-20T09:07:01.351Z,0.0,...,2026-06-07T18:45:10.966Z,LINE,us,2.0,9885271.0,TRIES,TRIES,NaN,NaN,NaN
1,1296625,7.656120e+16,https://avatars.steamstatic.com/2db6b65f1ba032...,https://avatars.steamstatic.com/2db6b65f1ba032...,https://avatars.steamstatic.com/2db6b65f1ba032...,https://steamcommunity.com/id/Newsham/,Newsham,2025-10-23T08:31:29.662Z,2026-05-22T18:28:46.036Z,0.0,...,2026-05-22T18:28:42.508Z,Newsham,NaN,2.0,8944221.0,Fart Studios,FRT,True,True,NaN
2,2029214,7.656120e+16,https://avatars.steamstatic.com/c26f88d781e1a2...,https://avatars.steamstatic.com/c26f88d781e1a2...,https://avatars.steamstatic.com/c26f88d781e1a2...,https://steamcommunity.com/id/shindvqq/,АНИМЕ ПСИХОЗ,2024-04-18T15:33:18.532Z,2026-04-08T13:09:41.476Z,0.0,...,2026-04-14T08:57:16.501Z,Shindaqq,ax,1.0,9928877.0,SHADOW GOVERNMENT,SG,NaN,NaN,NaN
3,2503633,7.656120e+16,https://avatars.steamstatic.com/a717da8d029408...,https://avatars.steamstatic.com/a717da8d029408...,https://avatars.steamstatic.com/a717da8d029408...,https://steamcommunity.com/profiles/7656119796...,是打不过啊,NaN,2026-05-02T17:29:26.601Z,0.0,...,2026-06-03T16:05:26.587Z,还不错,NaN,0.0,9717978.0,bilibili,bilibili,NaN,NaN,NaN
4,3035021,7.656120e+16,https://avatars.steamstatic.com/c63bb771a7cec4...,https://avatars.steamstatic.com/c63bb771a7cec4...,https://avatars.steamstatic.com/c63bb771a7cec4...,https://steamcommunity.com/id/Snoowiee/,Snowie,NaN,2026-05-22T20:07:17.282Z,0.0,...,2026-05-22T20:07:17.394Z,Snowie,NaN,0.0,9531587.0,SOG,SOG,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4471,1927313273,7.656120e+16,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://avatars.steamstatic.com/ecf58d3f2ce222...,https://steamcommunity.com/profiles/7656119988...,linglaiofficial,NaN,2026-02-26T05:54:51.639Z,0.0,...,2026-05-18T07:00:45.548Z,Linglai,cn,1.0,9855678.0,This Not Smurf,Smurf,NaN,NaN,NaN
4472,1928064793,7.656120e+16,https://avatars.steamstatic.com/c56aa36c56064c...,https://avatars.steamstatic.com/c56aa36c56064c...,https://avatars.steamstatic.com/c56aa36c56064c...,https://steamcommunity.com/profiles/7656119988...,наруто,NaN,2026-04-19T11:59:29.690Z,0.0,...,2026-04-26T02:11:57.231Z,67,NaN,2.0,10142777.0,TeamPidors2010,PidrTeam,NaN,NaN,NaN
4473,1929726323,7.656120e+16,https://avatars.steamstatic.com/bdee3be4086251...,https://avatars.steamstatic.com/bdee3be4086251...,https://avatars.steamstatic.com/bdee3be4086251...,https://steamcommunity.com/id/kyowadoto/,Kane`,NaN,2026-04-24T15:09:19.677Z,0.0,...,2026-05-11T01:21:13.895Z,Kyowa,pe,1.0,10041049.0,Awa Team,LFT,NaN,NaN,NaN
4474,1930115322,7.656120e+16,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://avatars.steamstatic.com/d21fa1cd1189ee...,https://steamcommunity.com/profiles/7656119989...,прив,NaN,2026-05-20T03:27:03.351Z,0.0,...,2026-05-30T21:11:53.589Z,Pink Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4475,1930918551,7.656120e+16,https://avatars.steamstatic.com/3d598f847cb0ab...,https://avatars.steamstatic.com/3d598f847cb0ab...,https://avatars.steamstatic.com/3d598f847cb0ab...,https://steamcommunity.com/profiles/7656119989...,Сосу за деньги,NaN,2026-01-28T12:21:29.953Z,0.0,...,2026-05-23T09:26:10.526Z,y0nd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
def realiza_request(url, method='get'):
  try:
    match method.lower():
      case 'get':
        response = requests.get(url)
      case 'post':
        response = requests.post(url)

    # Verifica se a requisição foi bem sucedida (Status 200)
    response.raise_for_status()
    json_response = response.json()

    if not json_response:
        print("Sem resposta")
        return None
    return json_response
  except requests.exceptions.RequestException as e:
    if e.response.status_code == 404:
      print(f"Erro ao acessar a API: {e}")
      return 404

    if e.response.status_code == 429:
      print(f"Erro ao acessar a API: {e}")
      time.sleep(65)
      return realiza_request(url)
    else:
      print(f"Erro ao acessar a API: {e}")
      return None

In [9]:
def player_info(account_id):
  return realiza_request(f"https://api.opendota.com/api/players/{account_id}")

In [15]:
def get_top_players_info(ids):
  ids_lidos = []
  ids_com_erro = []
  indice=0
  try:
    for id in ids:

      info = player_info(id)

      if info == None:
        raise Exception()
      if info == 404:
        ids_com_erro.append(id)
        continue
      
      with open(f'info_players/id{id}.json', 'w', encoding='utf-8') as arquivo:
        json.dump(info, arquivo, ensure_ascii=False, indent=2)
      indice+=1
      ids_lidos.append(int(id))

  except Exception as e:
    print(f"erro no id {id} de indice {indice}")
    print(e)
  finally:
    return ids_lidos, ids_com_erro

In [34]:
ultimo_id = 140411011
ultimo_index = list(topPlayers[topPlayers["account_id"] == ultimo_id].index)[0]
ultimo_index

482

In [39]:
para_coletar = list(topPlayers["account_id"])[ultimo_index+1:]
para_coletar[0]

140437312

In [40]:

ids_lidos, ids_com_erro = get_top_players_info(para_coletar)
ids_coletados = {"sucesso": ids_lidos, "erro": ids_com_erro}
with open('ids_coletados.json', 'w', encoding='utf-8') as arquivo:
      json.dump(ids_coletados, arquivo, ensure_ascii=False, indent=2)

Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/150141191
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/158747754
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/177776667
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/194106874
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/202904153
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/202904153
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/218367241
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/233940074
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/247899957
Erro ao acessar a API: 429 Client Error: Too Many Requests for url: https://api.opendota.com/api/players/269946072
Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/players/283494184
erro no id 283494184 de indice 670

In [10]:
p1 = player_info(topPlayers["account_id"].iloc[0])
p1

{'profile': {'account_id': 1111506,
  'personaname': 'LineDOTA2',
  'name': 'LINE',
  'plus': True,
  'cheese': 0,
  'steamid': '76561197961377234',
  'avatar': 'https://avatars.steamstatic.com/8c540801f27f1305565addc352ea6471a960e3c9.jpg',
  'avatarmedium': 'https://avatars.steamstatic.com/8c540801f27f1305565addc352ea6471a960e3c9_medium.jpg',
  'avatarfull': 'https://avatars.steamstatic.com/8c540801f27f1305565addc352ea6471a960e3c9_full.jpg',
  'profileurl': 'https://steamcommunity.com/id/Line/',
  'last_login': '2026-02-16T09:18:34.196Z',
  'loccountrycode': 'US',
  'status': None,
  'fh_unavailable': False,
  'is_contributor': False,
  'is_subscriber': False},
 'rank_tier': 15,
 'leaderboard_rank': None,
 'computed_mmr': 3952.82,
 'computed_mmr_turbo': None,
 'aliases': [{'personaname': 'LINE', 'name_since': '2021-11-27T19:22:07.000Z'},
  {'personaname': 'LineDOTA2', 'name_since': '2026-04-06T23:52:38.000Z'}]}

In [ ]:
import json
from IPython.display import JSON

#display(topPlayers)

topPlayers[0]

{'account_id': 249970979,
 'computed_mmr': 5423.53,
 'delta': 6.18853,
 'match_id': 8816070432,
 'steamid': '76561198210236707',
 'avatar': 'https://avatars.steamstatic.com/7d3a845488b9be24cc8cc968719154785b10ba26.jpg',
 'avatarmedium': 'https://avatars.steamstatic.com/7d3a845488b9be24cc8cc968719154785b10ba26_medium.jpg',
 'avatarfull': 'https://avatars.steamstatic.com/7d3a845488b9be24cc8cc968719154785b10ba26_full.jpg',
 'profileurl': 'https://steamcommunity.com/profiles/76561198210236707/',
 'personaname': 'Jin woo',
 'last_login': None,
 'full_history_time': '2026-02-10T00:48:06.885Z',
 'cheese': 0,
 'fh_unavailable': False,
 'loccountrycode': None,
 'last_match_time': '2026-05-18T16:06:02.000Z',
 'plus': False,
 'profile_time': '2026-06-02T05:34:15.273Z',
 'rank_tier_time': '2026-05-18T17:31:09.597Z',
 'name': None,
 'country_code': None,
 'fantasy_role': None,
 'team_id': None,
 'team_name': None,
 'team_tag': None,
 'is_locked': None,
 'is_pro': None,
 'locked_until': None,
 'rating': 71,
 'rank_tier': 71}

In [ ]:

def ranking_jogador(player_id) -> json:
  # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/players/{player_id}/ratings"

    try:
        print(f"Buscando ranking para o ID: {player_id}...")
        response = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        response.raise_for_status()

        ranking = response.json()

        if not ranking:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização

        return ranking

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

# Substitua pelo ID real do jogador (Account ID do Dota 2)
PLAYER_ID = "123760495"
resultado = ranking_jogador(PLAYER_ID)
resultado

Buscando ranking para o ID: 123760495...

In [ ]:
def api_ta_on()-> json:
  # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/metadata"

    try:
        print(f"Buscando esquema...")
        esquemas = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        esquemas.raise_for_status()

        esquemas = esquemas.json()

        if not esquemas:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização

        return esquemas

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

resultado = api_ta_on()
display(resultado)

Buscando esquema...

{'scenarios': {'itemCost': 1400,
  'timings': [450, 600, 720, 900, 1200, 1500, 1800],
  'gameDurationBucket': [900, 1800, 2700, 3600, 5400],
  'teamScenariosQueryParams': ['pos_chat_1min',
   'neg_chat_1min',
   'courier_kill',
   'first_blood']},
 'isSubscriber': False,
 'freeCallLimit': 3000,
 'freeRateLimit': 60,
 'premRateLimit': 3000,
 'beta': False}

In [ ]:

def buscar_esquema() -> json:
  # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/schema"

    try:
        print(f"Buscando esquema...")
        esquemas = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        esquemas.raise_for_status()

        esquemas = esquemas.json()

        if not esquemas:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização

        return esquemas

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

resultado = buscar_esquema()
display(resultado)
with open('esquema.json', 'w', encoding='utf-8') as arquivo:
    json.dump(resultado, arquivo, indent=4)

Buscando esquema...

[{'table_name': 'aliases', 'column_name': 'account_id', 'data_type': 'bigint'},
 {'table_name': 'aliases', 'column_name': 'personaname', 'data_type': 'text'},
 {'table_name': 'aliases',
  'column_name': 'name_since',
  'data_type': 'timestamp with time zone'},
 {'table_name': 'api_key_usage',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'api_key_usage',
  'column_name': 'customer_id',
  'data_type': 'text'},
 {'table_name': 'api_key_usage',
  'column_name': 'api_key',
  'data_type': 'uuid'},
 {'table_name': 'api_key_usage',
  'column_name': 'usage_count',
  'data_type': 'bigint'},
 {'table_name': 'api_key_usage', 'column_name': 'ip', 'data_type': 'text'},
 {'table_name': 'api_key_usage',
  'column_name': 'timestamp',
  'data_type': 'timestamp without time zone'},
 {'table_name': 'api_keys',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'api_keys', 'column_name': 'api_key', 'data_type': 'uuid'},
 {'table_name': 'api_keys', 'column_name': 'customer_id', 'data_type': 'text'},
 {'table_name': 'api_keys',
  'column_name': 'subscription_id',
  'data_type': 'text'},
 {'table_name': 'api_keys',
  'column_name': 'is_canceled',
  'data_type': 'boolean'},
 {'table_name': 'competitive_rank',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'competitive_rank',
  'column_name': 'rating',
  'data_type': 'integer'},
 {'table_name': 'cosmetics', 'column_name': 'item_id', 'data_type': 'integer'},
 {'table_name': 'cosmetics', 'column_name': 'name', 'data_type': 'text'},
 {'table_name': 'cosmetics', 'column_name': 'prefab', 'data_type': 'text'},
 {'table_name': 'cosmetics',
  'column_name': 'creation_date',
  'data_type': 'timestamp with time zone'},
 {'table_name': 'cosmetics',
  'column_name': 'image_inventory',
  'data_type': 'text'},
 {'table_name': 'cosmetics', 'column_name': 'image_path', 'data_type': 'text'},
 {'table_name': 'cosmetics',
  'column_name': 'item_description',
  'data_type': 'text'},
 {'table_name': 'cosmetics', 'column_name': 'item_name', 'data_type': 'text'},
 {'table_name': 'cosmetics',
  'column_name': 'item_rarity',
  'data_type': 'text'},
 {'table_name': 'cosmetics',
  'column_name': 'item_type_name',
  'data_type': 'text'},
 {'table_name': 'cosmetics',
  'column_name': 'used_by_heroes',
  'data_type': 'text'},
 {'table_name': 'hero_ranking',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'hero_ranking',
  'column_name': 'hero_id',
  'data_type': 'integer'},
 {'table_name': 'hero_ranking',
  'column_name': 'score',
  'data_type': 'double precision'},
 {'table_name': 'heroes', 'column_name': 'id', 'data_type': 'integer'},
 {'table_name': 'heroes', 'column_name': 'name', 'data_type': 'text'},
 {'table_name': 'heroes',
  'column_name': 'localized_name',
  'data_type': 'text'},
 {'table_name': 'heroes', 'column_name': 'primary_attr', 'data_type': 'text'},
 {'table_name': 'heroes', 'column_name': 'attack_type', 'data_type': 'text'},
 {'table_name': 'heroes', 'column_name': 'roles', 'data_type': 'ARRAY'},
 {'table_name': 'heroes', 'column_name': 'legs', 'data_type': 'integer'},
 {'table_name': 'insert_queue',
  'column_name': 'match_seq_num',
  'data_type': 'bigint'},
 {'table_name': 'insert_queue', 'column_name': 'data', 'data_type': 'json'},
 {'table_name': 'insert_queue',
  'column_name': 'processed',
  'data_type': 'boolean'},
 {'table_name': 'items', 'column_name': 'id', 'data_type': 'integer'},
 {'table_name': 'items', 'column_name': 'name', 'data_type': 'text'},
 {'table_name': 'items', 'column_name': 'cost', 'data_type': 'integer'},
 {'table_name': 'items',
  'column_name': 'secret_shop',
  'data_type': 'smallint'},
 {'table_name': 'items', 'column_name': 'side_shop', 'data_type': 'smallint'},
 {'table_name': 'items', 'column_name': 'recipe', 'data_type': 'smallint'},
 {'table_name': 'items', 'column_name': 'localized_name', 'data_type': 'text'},
 {'table_name': 'leaderboard_rank',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'leaderboard_rank',
  'column_name': 'rating',
  'data_type': 'integer'},
 {'table_name': 'league_match',
  'column_name': 'leagueid',
  'data_type': 'integer'},
 {'table_name': 'league_match',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'leagues', 'column_name': 'leagueid', 'data_type': 'bigint'},
 {'table_name': 'leagues', 'column_name': 'ticket', 'data_type': 'text'},
 {'table_name': 'leagues', 'column_name': 'banner', 'data_type': 'text'},
 {'table_name': 'leagues', 'column_name': 'tier', 'data_type': 'text'},
 {'table_name': 'leagues', 'column_name': 'name', 'data_type': 'text'},
 {'table_name': 'match_patch',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'match_patch', 'column_name': 'patch', 'data_type': 'text'},
 {'table_name': 'matches', 'column_name': 'match_id', 'data_type': 'bigint'},
 {'table_name': 'matches',
  'column_name': 'match_seq_num',
  'data_type': 'bigint'},
 {'table_name': 'matches',
  'column_name': 'radiant_win',
  'data_type': 'boolean'},
 {'table_name': 'matches', 'column_name': 'start_time', 'data_type': 'bigint'},
 {'table_name': 'matches', 'column_name': 'duration', 'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'tower_status_radiant',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'tower_status_dire',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'barracks_status_radiant',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'barracks_status_dire',
  'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'cluster', 'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'first_blood_time',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'lobby_type',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'human_players',
  'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'leagueid', 'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'positive_votes',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'negative_votes',
  'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'game_mode', 'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'engine', 'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'picks_bans', 'data_type': 'ARRAY'},
 {'table_name': 'matches',
  'column_name': 'radiant_team_id',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'dire_team_id',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'radiant_team_name',
  'data_type': 'text'},
 {'table_name': 'matches',
  'column_name': 'dire_team_name',
  'data_type': 'text'},
 {'table_name': 'matches',
  'column_name': 'radiant_team_complete',
  'data_type': 'smallint'},
 {'table_name': 'matches',
  'column_name': 'dire_team_complete',
  'data_type': 'smallint'},
 {'table_name': 'matches',
  'column_name': 'radiant_captain',
  'data_type': 'bigint'},
 {'table_name': 'matches',
  'column_name': 'dire_captain',
  'data_type': 'bigint'},
 {'table_name': 'matches', 'column_name': 'chat', 'data_type': 'ARRAY'},
 {'table_name': 'matches', 'column_name': 'objectives', 'data_type': 'ARRAY'},
 {'table_name': 'matches',
  'column_name': 'radiant_gold_adv',
  'data_type': 'ARRAY'},
 {'table_name': 'matches',
  'column_name': 'radiant_xp_adv',
  'data_type': 'ARRAY'},
 {'table_name': 'matches', 'column_name': 'teamfights', 'data_type': 'ARRAY'},
 {'table_name': 'matches', 'column_name': 'version', 'data_type': 'integer'},
 {'table_name': 'matches', 'column_name': 'cosmetics', 'data_type': 'json'},
 {'table_name': 'matches',
  'column_name': 'radiant_score',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'dire_score',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'draft_timings',
  'data_type': 'ARRAY'},
 {'table_name': 'matches', 'column_name': 'series_id', 'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'series_type',
  'data_type': 'integer'},
 {'table_name': 'matches',
  'column_name': 'replay_salt',
  'data_type': 'integer'},
 {'table_name': 'notable_players',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'notable_players', 'column_name': 'name', 'data_type': 'text'},
 {'table_name': 'notable_players',
  'column_name': 'country_code',
  'data_type': 'text'},
 {'table_name': 'notable_players',
  'column_name': 'fantasy_role',
  'data_type': 'integer'},
 {'table_name': 'notable_players',
  'column_name': 'team_id',
  'data_type': 'integer'},
 {'table_name': 'notable_players',
  'column_name': 'team_name',
  'data_type': 'text'},
 {'table_name': 'notable_players',
  'column_name': 'team_tag',
  'data_type': 'text'},
 {'table_name': 'notable_players',
  'column_name': 'is_locked',
  'data_type': 'boolean'},
 {'table_name': 'notable_players',
  'column_name': 'is_pro',
  'data_type': 'boolean'},
 {'table_name': 'notable_players',
  'column_name': 'locked_until',
  'data_type': 'integer'},
 {'table_name': 'parsed_matches',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'parsed_matches',
  'column_name': 'is_archived',
  'data_type': 'boolean'},
 {'table_name': 'picks_bans',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'picks_bans',
  'column_name': 'is_pick',
  'data_type': 'boolean'},
 {'table_name': 'picks_bans',
  'column_name': 'hero_id',
  'data_type': 'integer'},
 {'table_name': 'picks_bans', 'column_name': 'team', 'data_type': 'smallint'},
 {'table_name': 'picks_bans', 'column_name': 'ord', 'data_type': 'smallint'},
 {'table_name': 'player_computed_mmr',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'player_computed_mmr',
  'column_name': 'computed_mmr',
  'data_type': 'real'},
 {'table_name': 'player_computed_mmr',
  'column_name': 'delta',
  'data_type': 'real'},
 {'table_name': 'player_computed_mmr',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'player_computed_mmr_turbo',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'player_computed_mmr_turbo',
  'column_name': 'computed_mmr',
  'data_type': 'real'},
 {'table_name': 'player_computed_mmr_turbo',
  'column_name': 'delta',
  'data_type': 'real'},
 {'table_name': 'player_computed_mmr_turbo',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'player_match_history',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'player_match_history',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'player_match_history',
  'column_name': 'player_slot',
  'data_type': 'integer'},
 {'table_name': 'player_match_history',
  'column_name': 'retries',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'player_matches',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'player_matches',
  'column_name': 'player_slot',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'hero_id',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_0',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_1',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_2',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_3',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_4',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_5',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'kills',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'deaths',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'assists',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'leaver_status',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'gold',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'last_hits',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'denies',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'gold_per_min',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'xp_per_min',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'gold_spent',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'hero_damage',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'tower_damage',
  'data_type': 'bigint'},
 {'table_name': 'player_matches',
  'column_name': 'hero_healing',
  'data_type': 'bigint'},
 {'table_name': 'player_matches',
  'column_name': 'level',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'additional_units',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches', 'column_name': 'stuns', 'data_type': 'real'},
 {'table_name': 'player_matches',
  'column_name': 'max_hero_hit',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'times',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'gold_t',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches', 'column_name': 'lh_t', 'data_type': 'ARRAY'},
 {'table_name': 'player_matches', 'column_name': 'xp_t', 'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'obs_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'sen_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'purchase_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'kills_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'buyback_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'lane_pos',
  'data_type': 'json'},
 {'table_name': 'player_matches', 'column_name': 'obs', 'data_type': 'json'},
 {'table_name': 'player_matches', 'column_name': 'sen', 'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'actions',
  'data_type': 'json'},
 {'table_name': 'player_matches', 'column_name': 'pings', 'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'purchase',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'gold_reasons',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'xp_reasons',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'killed',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'item_uses',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'ability_uses',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'hero_hits',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'damage',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'damage_taken',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'damage_inflictor',
  'data_type': 'json'},
 {'table_name': 'player_matches', 'column_name': 'runes', 'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'killed_by',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'kill_streaks',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'multi_kills',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'life_state',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'damage_inflictor_received',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'obs_placed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'sen_placed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'creeps_stacked',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'camps_stacked',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'rune_pickups',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'obs_left_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'sen_left_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'ability_upgrades_arr',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'party_id',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'permanent_buffs',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'backpack_0',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'backpack_1',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'backpack_2',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'runes_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'lane',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'lane_role',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'is_roaming',
  'data_type': 'boolean'},
 {'table_name': 'player_matches',
  'column_name': 'firstblood_claimed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'teamfight_participation',
  'data_type': 'real'},
 {'table_name': 'player_matches',
  'column_name': 'towers_killed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'roshans_killed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'observers_placed',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'party_size',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'ability_targets',
  'data_type': 'json'},
 {'table_name': 'player_matches',
  'column_name': 'damage_targets',
  'data_type': 'json'},
 {'table_name': 'player_matches', 'column_name': 'dn_t', 'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'connection_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'backpack_3',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'item_neutral',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'net_worth',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'hero_variant',
  'data_type': 'integer'},
 {'table_name': 'player_matches',
  'column_name': 'neutral_tokens_log',
  'data_type': 'ARRAY'},
 {'table_name': 'player_matches',
  'column_name': 'neutral_item_history',
  'data_type': 'ARRAY'},
 {'table_name': 'player_ratings',
  'column_name': 'account_id',
  'data_type': 'bigint'},
 {'table_name': 'player_ratings',
  'column_name': 'match_id',
  'data_type': 'bigint'},
 {'table_name': 'player_ratings',
  'column_name': 'solo_competitive_rank',
  'data_type': 'integer'},
 {'table_name': 'player_ratings',
  'column_name': 'competitive_rank',
  'data_type': 'integer'},
 {'table_name': 'player_ratings',
  'column_name': 'time',
  'data_type': 'timestamp with time zone'},
 {'table_name': 'players', 'column_name': 'account_id', 'data_type': 'bigint'},
 {'table_name': 'players', 'column_name': 'steamid', 'data_type': 'text'},
 {'table_name': 'players', 'column_name': 'avatar', 'data_type': 'text'},
 {'table_name': 'players', 'column_name': 'avatarmedium', 'data_type': 'text'},
 {'table_name': 'players', 'column_name': 'avatarfull', 'data_type': 'text'},
 {'table_name': 'players', 'column_name': 'profileurl', 'data_type': 'text'},

In [ ]:
def buscar_jogador(player_id) -> json:
  # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/players/{player_id}"

    try:
        print(f"Buscando partidas para o ID: {player_id}...")
        response = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        response.raise_for_status()

        partidas = response.json()

        if not partidas:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização

        return partidas

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

# Substitua pelo ID real do jogador (Account ID do Dota 2)
PLAYER_ID = "123760495"
resultado = buscar_jogador(PLAYER_ID)
resultado

Buscando partidas para o ID: 123760495...

{'profile': {'account_id': 123760495,
  'personaname': 'Pepe Kafu Dida',
  'name': None,
  'plus': False,
  'cheese': 0,
  'steamid': '76561198084026223',
  'avatar': 'https://avatars.steamstatic.com/16424555e1195122023a1264d5a4f65b8a0bbd37.jpg',
  'avatarmedium': 'https://avatars.steamstatic.com/16424555e1195122023a1264d5a4f65b8a0bbd37_medium.jpg',
  'avatarfull': 'https://avatars.steamstatic.com/16424555e1195122023a1264d5a4f65b8a0bbd37_full.jpg',
  'profileurl': 'https://steamcommunity.com/profiles/76561198084026223/',
  'last_login': '2026-04-26T13:53:45.457Z',
  'loccountrycode': None,
  'status': None,
  'fh_unavailable': False,
  'is_contributor': False,
  'is_subscriber': False},
 'rank_tier': 54,
 'leaderboard_rank': None,
 'computed_mmr': None,
 'computed_mmr_turbo': 3979.46,
 'aliases': [{'personaname': 'Almirante Miro',
   'name_since': '2024-06-25T22:12:25.000Z'},
  {'personaname': 'Athos', 'name_since': '2024-08-30T03:09:33.000Z'},
  {'personaname': 'Busão do CAPS', 'name_since': '2025-04-26T17:30:57.000Z'},
  {'personaname': 'Capitão Brocha', 'name_since': '2024-06-25T22:42:28.000Z'},
  {'personaname': 'Coronel Brocha', 'name_since': '2024-06-25T22:42:25.000Z'},
  {'personaname': 'Coronel Uku Cossa',
   'name_since': '2024-05-27T23:11:23.000Z'},
  {'personaname': 'Eu do Marley e Eu',
   'name_since': '2024-07-25T18:45:12.000Z'},
  {'personaname': 'Mijar na Pia é o meta',
   'name_since': '2023-08-20T20:09:50.000Z'},
  {'personaname': 'Min Fuh Ji', 'name_since': '2025-07-09T02:08:39.000Z'},
  {'personaname': 'Pepe + Kafu + Dida',
   'name_since': '2025-12-28T21:53:51.000Z'},
  {'personaname': 'Pepe Kafu Dida', 'name_since': '2025-12-28T22:18:15.000Z'},
  {'personaname': 'Raitocan', 'name_since': '2023-08-20T21:43:31.000Z'}]}

In [ ]:
def buscar_partidas_jogador(player_id) -> json:
  # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/players/{player_id}/matches"

    try:
        print(f"Buscando partidas para o ID: {player_id}...")
        response = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        response.raise_for_status()

        partidas = response.json()

        if not partidas:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização

        return partidas

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

# Substitua pelo ID real do jogador (Account ID do Dota 2)
PLAYER_ID = "123760495"
resultado = buscar_partidas_jogador(PLAYER_ID)
display(resultado)
with open('partidas_jogador.json', 'w', encoding='utf-8') as arquivo:
    json.dump(resultado, arquivo, indent=4)

Buscando partidas para o ID: 123760495...

[{'match_id': 8145780410,
  'player_slot': 129,
  'radiant_win': False,
  'duration': 1486,
  'game_mode': 4,
  'lobby_type': 0,
  'hero_id': 53,
  'start_time': 1737850880,
  'version': None,
  'kills': 10,
  'deaths': 5,
  'assists': 21,
  'average_rank': 63,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': 2},
 {'match_id': 8145745528,
  'player_slot': 2,
  'radiant_win': False,
  'duration': 2133,
  'game_mode': 4,
  'lobby_type': 0,
  'hero_id': 14,
  'start_time': 1737847960,
  'version': None,
  'kills': 10,
  'deaths': 13,
  'assists': 12,
  'average_rank': 62,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': 2},
 {'match_id': 7029360506,
  'player_slot': 0,
  'radiant_win': False,
  'duration': 2404,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 47,
  'start_time': 1677102579,
  'version': None,
  'kills': 3,
  'deaths': 15,
  'assists': 16,
  'average_rank': 51,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 7017477496,
  'player_slot': 132,
  'radiant_win': True,
  'duration': 1542,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 113,
  'start_time': 1676413728,
  'version': None,
  'kills': 4,
  'deaths': 5,
  'assists': 2,
  'average_rank': 61,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6745498263,
  'player_slot': 129,
  'radiant_win': False,
  'duration': 2604,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 26,
  'start_time': 1662556629,
  'version': None,
  'kills': 8,
  'deaths': 10,
  'assists': 23,
  'average_rank': 51,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6592914637,
  'player_slot': 132,
  'radiant_win': False,
  'duration': 2096,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1653846334,
  'version': 21,
  'kills': 8,
  'deaths': 6,
  'assists': 25,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6592592077,
  'player_slot': 2,
  'radiant_win': True,
  'duration': 2516,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1653834069,
  'version': None,
  'kills': 8,
  'deaths': 12,
  'assists': 24,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6404838878,
  'player_slot': 1,
  'radiant_win': False,
  'duration': 1847,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1643494511,
  'version': None,
  'kills': 1,
  'deaths': 8,
  'assists': 13,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6363488061,
  'player_slot': 2,
  'radiant_win': False,
  'duration': 2303,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 62,
  'start_time': 1641516938,
  'version': 21,
  'kills': 2,
  'deaths': 12,
  'assists': 6,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': None},
 {'match_id': 6355846488,
  'player_slot': 132,
  'radiant_win': True,
  'duration': 2352,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 44,
  'start_time': 1641149241,
  'version': None,
  'kills': 4,
  'deaths': 14,
  'assists': 7,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6276423932,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 2991,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636996194,
  'version': None,
  'kills': 4,
  'deaths': 15,
  'assists': 21,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6276246085,
  'player_slot': 1,
  'radiant_win': False,
  'duration': 2025,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636989409,
  'version': None,
  'kills': 5,
  'deaths': 9,
  'assists': 16,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6273544901,
  'player_slot': 3,
  'radiant_win': True,
  'duration': 1949,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636847720,
  'version': None,
  'kills': 4,
  'deaths': 9,
  'assists': 23,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6273508065,
  'player_slot': 2,
  'radiant_win': True,
  'duration': 2184,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1636844873,
  'version': None,
  'kills': 3,
  'deaths': 13,
  'assists': 25,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6270051484,
  'player_slot': 1,
  'radiant_win': False,
  'duration': 2936,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636670542,
  'version': None,
  'kills': 6,
  'deaths': 8,
  'assists': 23,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6267071599,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 3204,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636506696,
  'version': None,
  'kills': 9,
  'deaths': 16,
  'assists': 16,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6266283576,
  'player_slot': 3,
  'radiant_win': True,
  'duration': 2850,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636466871,
  'version': None,
  'kills': 14,
  'deaths': 9,
  'assists': 14,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6265469611,
  'player_slot': 129,
  'radiant_win': True,
  'duration': 2740,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 67,
  'start_time': 1636417805,
  'version': 21,
  'kills': 12,
  'deaths': 5,
  'assists': 19,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': None},
 {'match_id': 6264551962,
  'player_slot': 1,
  'radiant_win': False,
  'duration': 2475,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636375442,
  'version': None,
  'kills': 4,
  'deaths': 16,
  'assists': 27,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263957763,
  'player_slot': 4,
  'radiant_win': True,
  'duration': 2069,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636336384,
  'version': None,
  'kills': 6,
  'deaths': 13,
  'assists': 22,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263934670,
  'player_slot': 0,
  'radiant_win': True,
  'duration': 1796,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 68,
  'start_time': 1636334114,
  'version': None,
  'kills': 2,
  'deaths': 10,
  'assists': 11,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263886045,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 3975,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 84,
  'start_time': 1636329351,
  'version': None,
  'kills': 6,
  'deaths': 11,
  'assists': 29,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263814871,
  'player_slot': 0,
  'radiant_win': True,
  'duration': 1895,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636323410,
  'version': None,
  'kills': 10,
  'deaths': 10,
  'assists': 23,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263783586,
  'player_slot': 4,
  'radiant_win': True,
  'duration': 1770,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636321246,
  'version': None,
  'kills': 13,
  'deaths': 9,
  'assists': 18,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263746921,
  'player_slot': 2,
  'radiant_win': True,
  'duration': 1735,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 68,
  'start_time': 1636318881,
  'version': None,
  'kills': 5,
  'deaths': 6,
  'assists': 20,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263703887,
  'player_slot': 128,
  'radiant_win': True,
  'duration': 1841,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636316467,
  'version': None,
  'kills': 1,
  'deaths': 11,
  'assists': 6,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263600483,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 4081,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636311453,
  'version': None,
  'kills': 13,
  'deaths': 8,
  'assists': 26,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6263509934,
  'player_slot': 131,
  'radiant_win': False,
  'duration': 3064,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 84,
  'start_time': 1636307715,
  'version': None,
  'kills': 4,
  'deaths': 12,
  'assists': 21,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6262137982,
  'player_slot': 131,
  'radiant_win': False,
  'duration': 2493,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636249067,
  'version': None,
  'kills': 8,
  'deaths': 7,
  'assists': 23,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6262098050,
  'player_slot': 128,
  'radiant_win': False,
  'duration': 2932,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 84,
  'start_time': 1636245693,
  'version': None,
  'kills': 3,
  'deaths': 9,
  'assists': 33,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6262073251,
  'player_slot': 129,
  'radiant_win': False,
  'duration': 1761,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636243588,
  'version': None,
  'kills': 4,
  'deaths': 4,
  'assists': 11,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6262027905,
  'player_slot': 128,
  'radiant_win': False,
  'duration': 2737,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1636240132,
  'version': None,
  'kills': 2,
  'deaths': 13,
  'assists': 19,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6261673322,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 4057,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 84,
  'start_time': 1636222766,
  'version': None,
  'kills': 16,
  'deaths': 19,
  'assists': 40,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6261582957,
  'player_slot': 2,
  'radiant_win': True,
  'duration': 2871,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 87,
  'start_time': 1636219520,
  'version': None,
  'kills': 2,
  'deaths': 8,
  'assists': 20,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6261511165,
  'player_slot': 1,
  'radiant_win': True,
  'duration': 2047,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636217062,
  'version': None,
  'kills': 2,
  'deaths': 11,
  'assists': 27,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6261439556,
  'player_slot': 132,
  'radiant_win': True,
  'duration': 1903,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636214685,
  'version': None,
  'kills': 4,
  'deaths': 11,
  'assists': 8,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6261327982,
  'player_slot': 1,
  'radiant_win': True,
  'duration': 2384,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 136,
  'start_time': 1636211209,
  'version': None,
  'kills': 6,
  'deaths': 15,
  'assists': 19,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6259764162,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 2688,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636133435,
  'version': None,
  'kills': 5,
  'deaths': 12,
  'assists': 18,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6258444019,
  'player_slot': 131,
  'radiant_win': True,
  'duration': 1785,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636063772,
  'version': None,
  'kills': 2,
  'deaths': 10,
  'assists': 9,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6258387593,
  'player_slot': 4,
  'radiant_win': True,
  'duration': 2353,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636060476,
  'version': None,
  'kills': 5,
  'deaths': 8,
  'assists': 15,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6258326619,
  'player_slot': 131,
  'radiant_win': True,
  'duration': 2689,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 119,
  'start_time': 1636057400,
  'version': None,
  'kills': 2,
  'deaths': 15,
  'assists': 19,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6176814564,
  'player_slot': 0,
  'radiant_win': False,
  'duration': 2720,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 45,
  'start_time': 1631412753,
  'version': None,
  'kills': 2,
  'deaths': 21,
  'assists': 24,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 6153501080,
  'player_slot': 2,
  'radiant_win': False,
  'duration': 2103,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 2,
  'start_time': 1630013364,
  'version': None,
  'kills': 2,
  'deaths': 17,
  'assists': 6,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6152250342,
  'player_slot': 130,
  'radiant_win': False,
  'duration': 2876,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 16,
  'start_time': 1629943851,
  'version': None,
  'kills': 9,
  'deaths': 17,
  'assists': 24,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 3,
  'hero_variant': None},
 {'match_id': 6152189024,
  'player_slot': 2,
  'radiant_win': True,
  'duration': 2048,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 99,
  'start_time': 1629937045,
  'version': None,
  'kills': 5,
  'deaths': 4,
  'assists': 11,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 3,
  'hero_variant': None},
 {'match_id': 6144615862,
  'player_slot': 132,
  'radiant_win': False,
  'duration': 3083,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 129,
  'start_time': 1629505950,
  'version': None,
  'kills': 9,
  'deaths': 10,
  'assists': 36,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': None},
 {'match_id': 6144585199,
  'player_slot': 132,
  'radiant_win': True,
  'duration': 2188,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 2,
  'start_time': 1629502883,
  'version': None,
  'kills': 5,
  'deaths': 11,
  'assists': 5,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': None},
 {'match_id': 6143199553,
  'player_slot': 131,
  'radiant_win': False,
  'duration': 2048,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 26,
  'start_time': 1629427086,
  'version': None,
  'kills': 1,
  'deaths': 11,
  'assists': 15,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6143160119,
  'player_slot': 3,
  'radiant_win': True,
  'duration': 3049,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 121,
  'start_time': 1629423329,
  'version': None,
  'kills': 7,
  'deaths': 8,
  'assists': 22,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6141720673,
  'player_slot': 132,
  'radiant_win': True,
  'duration': 2038,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1629337143,
  'version': None,
  'kills': 3,
  'deaths': 15,
  'assists': 6,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6122041424,
  'player_slot': 4,
  'radiant_win': False,
  'duration': 2168,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1628214430,
  'version': None,
  'kills': 5,
  'deaths': 13,
  'assists': 17,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6111584279,
  'player_slot': 4,
  'radiant_win': True,
  'duration': 2828,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 37,
  'start_time': 1627612063,
  'version': None,
  'kills': 4,
  'deaths': 9,
  'assists': 23,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6111553499,
  'player_slot': 132,
  'radiant_win': False,
  'duration': 2295,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1627609183,
  'version': None,
  'kills': 5,
  'deaths': 9,
  'assists': 25,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 5,
  'hero_variant': None},
 {'match_id': 6057126686,
  'player_slot': 130,
  'radiant_win': True,
  'duration': 2208,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 111,
  'start_time': 1624561337,
  'version': None,
  'kills': 2,
  'deaths': 14,
  'assists': 14,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 5988502330,
  'player_slot': 3,
  'radiant_win': False,
  'duration': 2541,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 135,
  'start_time': 1620682089,
  'version': None,
  'kills': 2,
  'deaths': 10,
  'assists': 16,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 5818272999,
  'player_slot': 132,
  'radiant_win': False,
  'duration': 4319,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1612487539,
  'version': None,
  'kills': 8,
  'deaths': 20,
  'assists': 37,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 1,
  'hero_variant': None},
 {'match_id': 5812781209,
  'player_slot': 128,
  'radiant_win': True,
  'duration': 2100,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 29,
  'start_time': 1612144376,
  'version': None,
  'kills': 10,
  'deaths': 15,
  'assists': 15,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 3,
  'hero_variant': None},
 {'match_id': 5812751592,
  'player_slot': 2,
  'radiant_win': False,
  'duration': 2359,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 84,
  'start_time': 1612141415,
  'version': None,
  'kills': 5,
  'deaths': 8,
  'assists': 10,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 3,
  'hero_variant': None},
 {'match_id': 5812724084,
  'player_slot': 128,
  'radiant_win': True,
  'duration': 2499,
  'game_mode': 22,
  'lobby_type': 7,
  'hero_id': 86,
  'start_time': 1612138530,
  'version': None,
  'kills': 2,
  'deaths': 10,
  'assists': 20,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 3,
  'hero_variant': None},
 {'match_id': 5806982220,
  'player_slot': 129,
  'radiant_win': True,
  'duration': 2946,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 123,
  'start_time': 1611846675,
  'version': None,
  'kills': 8,
  'deaths': 13,
  'assists': 10,
  'average_rank': None,
  'leaver_status': 0,
  'party_size': 2,
  'hero_variant': None},
 {'match_id': 5806143194,
  'player_slot': 1,
  'radiant_win': True,
  'duration': 1884,
  'game_mode': 22,
  'lobby_type': 0,
  'hero_id': 84,
  'start_time': 1611800677,
  'version': None,
  'kills': 4,
  'deaths': 3,
  'assists': 15,

In [ ]:
MATCH_ID = 8145780410

In [ ]:
def buscar_partidas_jogador(player_id):
    # Endpoint para recuperar as partidas de um jogador específico
    url = f"https://api.opendota.com/api/players/{player_id}/matches"

    try:
        print(f"Buscando partidas para o ID: {player_id}...")
        response = requests.get(url)

        # Verifica se a requisição foi bem sucedida (Status 200)
        response.raise_for_status()

        partidas = response.json()

        if not partidas:
            print("Nenhuma partida encontrada ou o perfil é privado.")
            return None

        # Transformando em um DataFrame para facilitar a visualização
        df = pd.DataFrame(partidas)

        # Selecionando apenas algumas colunas relevantes para o exemplo
        #colunas_interesse = ['match_id', 'player_slot', 'radiant_win', 'duration', 'hero_id', 'kills', 'deaths', 'assists']
        #df_resumo = df[colunas_interesse].copy()

        # Lógica simples para determinar se o jogador venceu
        # (Se player_slot < 128 ele é Radiant. Se radiant_win for True, ele venceu)
        #df_resumo['win'] = df_resumo.apply(
        #    lambda row: row['radiant_win'] if row['player_slot'] < 128 else not row['radiant_win'],
        #    axis=1
        #)

        return df

    except requests.exceptions.RequestException as e:
        print(f"Erro ao acessar a API: {e}")
        return None

# Substitua pelo ID real do jogador (Account ID do Dota 2)
PLAYER_ID = "123760495"
resultado = buscar_partidas_jogador(PLAYER_ID)

if resultado is not None:
    print(f"\nTotal de partidas encontradas: {len(resultado)}")
    print(resultado.head(10)) # Exibe as 10 primeiras

Buscando partidas para o ID: 123760495...

Total de partidas encontradas: 2582
     match_id  player_slot  radiant_win  duration  game_mode  lobby_type  \
0  8145780410          129        False      1486          4           0
1  8145745528            2        False      2133          4           0
2  7029360506            0        False      2404         22           0
3  7017477496          132         True      1542         22           0
4  6745498263          129        False      2604         22           0
5  6592914637          132        False      2096         22           7
6  6592592077            2         True      2516         22           7
7  6404838878            1        False      1847         22           7
8  6363488061            2        False      2303         22           0
9  6355846488          132         True      2352         22           0

   hero_id  start_time  version  kills  deaths  assists  average_rank  \
0       53  1737850880      NaN     10       5       21          63.0
1       14  1737847960      NaN     10      13       12          62.0
2       47  1677102579      NaN      3      15       16          51.0
3      113  1676413728      NaN      4       5        2          61.0
4       26  1662556629      NaN      8      10       23          51.0
5       86  1653846334     21.0      8       6       25           NaN
6       86  1653834069      NaN      8      12       24           NaN
7      136  1643494511      NaN      1       8       13           NaN
8       62  1641516938     21.0      2      12        6           NaN
9       44  1641149241      NaN      4      14        7           NaN

   leaver_status  party_size  hero_variant
0              0         2.0           2.0
1              0         2.0           2.0
2              0         1.0           NaN
3              0         1.0           NaN
4              0         1.0           NaN
5              0         1.0           NaN
6              0         1.0           NaN
7              0         1.0           NaN
8              0         2.0           NaN
9              0         1.0           NaN

In [ ]:
resultado

,match_id,player_slot,radiant_win,duration,game_mode,lobby_type,hero_id,start_time,version,kills,deaths,assists,average_rank,leaver_status,party_size,hero_variant
0,8145780410,129,False,1486,4,0,53,1737850880,NaN,10,5,21,63.0,0,2.0,2.0
1,8145745528,2,False,2133,4,0,14,1737847960,NaN,10,13,12,62.0,0,2.0,2.0
2,7029360506,0,False,2404,22,0,47,1677102579,NaN,3,15,16,51.0,0,1.0,NaN
3,7017477496,132,True,1542,22,0,113,1676413728,NaN,4,5,2,61.0,0,1.0,NaN
4,6745498263,129,False,2604,22,0,26,1662556629,NaN,8,10,23,51.0,0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2577,131138525,4,False,2441,1,0,74,1361392280,NaN,4,6,8,NaN,0,NaN,NaN
2578,130956278,4,False,2511,1,0,100,1361378767,NaN,1,14,7,NaN,0,NaN,NaN
2579,130085763,129,False,2886,1,0,35,1361290386,NaN,11,10,12,NaN,0,NaN,NaN
2580,127676306,1,False,2664,4,0,78,1361059203,NaN,3,14,16,NaN,0,NaN,NaN
2581,127657122,1,True,1527,1,0,35,1361057030,NaN,10,2,18,NaN,0,10.0,0.0

In [ ]:
resultado.columns

Index(['match_id', 'player_slot', 'radiant_win', 'duration', 'game_mode',
       'lobby_type', 'hero_id', 'start_time', 'version', 'kills', 'deaths',
       'assists', 'average_rank', 'leaver_status', 'party_size',
       'hero_variant'],
      dtype='object')

In [ ]:
datetime.datetime.fromtimestamp(1361057030)

datetime.datetime(2013, 2, 16, 23, 23, 50)

In [ ]:
url = f"https://api.opendota.com/api/matches/8145780410"

response = requests.get(url)
response.raise_for_status()

dados_partida = response.json()

In [ ]:
dados_partida['players']

[{'account_id': 100712620,
  'player_slot': 0,
  'party_id': 0,
  'permanent_buffs': [],
  'party_size': 1,
  'team_number': 0,
  'team_slot': 0,
  'hero_id': 42,
  'hero_variant': 2,
  'item_0': 0,
  'item_1': 0,
  'item_2': 0,
  'item_3': 0,
  'item_4': 0,
  'item_5': 0,
  'backpack_0': 0,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 2091,
  'kills': 0,
  'deaths': 9,
  'assists': 3,
  'leaver_status': 2,
  'last_hits': 34,
  'denies': 1,
  'gold_per_min': 221,
  'xp_per_min': 229,
  'level': 9,
  'net_worth': 102,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 2380,
  'tower_damage': 0,
  'hero_healing': 0,
  'gold': 0,
  'gold_spent': 1785,
  'ability_upgrades_arr': [5088, 5086, 1282, 1282],
  'personaname': 'NINE FINGER',
  'name': None,
  'last_login': None,
  'rank_tier': 51,
  'computed_mmr': None,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': True,
  'win': 0,
  'lose': 1,
  'total_gold': 5473,
  'total_xp': 5671,
  'kda': 0.3,
  'abandons': 1,
  'benchmarks': {'gold_per_min': {'raw': 221, 'pct': 0.014510278113663845},
   'xp_per_min': {'raw': 229, 'pct': 0.022370012091898428},
   'kills_per_min': {'raw': 0, 'pct': 0.022370012091898428},
   'last_hits_per_min': {'raw': 1.3728129205921937,
    'pct': 0.024788391777509067},
   'hero_damage_per_min': {'raw': 96.09690444145356,
    'pct': 0.005441354292623942},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.9540507859733979},
   'tower_damage': {'raw': 0, 'pct': 0.045949214026602174}}},
 {'account_id': 101134312,
  'player_slot': 1,
  'party_id': 1,
  'permanent_buffs': [{'permanent_buff': 12,
    'stack_count': 0,
    'grant_time': 1157}],
  'party_size': 3,
  'team_number': 0,
  'team_slot': 1,
  'hero_id': 129,
  'hero_variant': 2,
  'item_0': 0,
  'item_1': 0,
  'item_2': 0,
  'item_3': 0,
  'item_4': 0,
  'item_5': 0,
  'backpack_0': 0,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 0,
  'kills': 1,
  'deaths': 10,
  'assists': 5,
  'leaver_status': 1,
  'last_hits': 56,
  'denies': 5,
  'gold_per_min': 322,
  'xp_per_min': 310,
  'level': 11,
  'net_worth': 1502,
  'aghanims_scepter': 0,
  'aghanims_shard': 1,
  'moonshard': 0,
  'hero_damage': 7742,
  'tower_damage': 51,
  'hero_healing': 0,
  'gold': 0,
  'gold_spent': 4335,
  'ability_upgrades_arr': [6583,
   6495,
   6583,
   6582,
   6583,
   1416,
   6495,
   6583,
   6495],
  'personaname': 'Belo Roxeda',
  'name': None,
  'last_login': '2023-11-15T01:07:26.847Z',
  'rank_tier': 80,
  'computed_mmr': 3911.75,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': True,
  'win': 0,
  'lose': 1,
  'total_gold': 7974,
  'total_xp': 7677,
  'kills_per_min': 0.04037685060565276,
  'kda': 0.55,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 322, 'pct': 0.12368421052631579},
   'xp_per_min': {'raw': 310, 'pct': 0.062280701754385964},
   'kills_per_min': {'raw': 0.040376850605652756, 'pct': 0.10526315789473684},
   'last_hits_per_min': {'raw': 2.2611036339165547,
    'pct': 0.08421052631578947},
   'hero_damage_per_min': {'raw': 312.5975773889637,
    'pct': 0.13771929824561405},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.7859649122807018},
   'tower_damage': {'raw': 51, 'pct': 0.21052631578947367}}},
 {'account_id': 116511110,
  'player_slot': 2,
  'party_id': 1,
  'permanent_buffs': [],
  'party_size': 3,
  'team_number': 0,
  'team_slot': 2,
  'hero_id': 16,
  'hero_variant': 1,
  'item_0': 0,
  'item_1': 29,
  'item_2': 218,
  'item_3': 188,
  'item_4': 39,
  'item_5': 34,
  'backpack_0': 38,
  'backpack_1': 16,
  'backpack_2': 0,
  'item_neutral': 0,
  'kills': 1,
  'deaths': 11,
  'assists': 5,
  'leaver_status': 1,
  'last_hits': 12,
  'denies': 3,
  'gold_per_min': 314,
  'xp_per_min': 305,
  'level': 11,
  'net_worth': 1152,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 4754,
  'tower_damage': 0,
  'hero_healing': 0,
  'gold': 0,
  'gold_spent': 2105,
  'ability_upgrades_arr': [5102, 1229, 5102, 5103, 5103, 5105, 5103],
  'personaname': 'Skark',
  'name': None,
  'last_login': None,
  'rank_tier': None,
  'computed_mmr': None,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': True,
  'win': 0,
  'lose': 1,
  'total_gold': 7776,
  'total_xp': 7553,
  'kills_per_min': 0.04037685060565276,
  'kda': 0.5,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 314, 'pct': 0.09758656873032528},
   'xp_per_min': {'raw': 305, 'pct': 0.06715634837355719},
   'kills_per_min': {'raw': 0.040376850605652756, 'pct': 0.05771248688352571},
   'last_hits_per_min': {'raw': 0.4845222072678331,
    'pct': 0.005246589716684155},
   'hero_damage_per_min': {'raw': 191.9515477792732,
    'pct': 0.02833158447009444},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.8866736621196223},
   'tower_damage': {'raw': 0, 'pct': 0.22560335781741866}}},
 {'account_id': 98957904,
  'player_slot': 3,
  'party_id': 1,
  'permanent_buffs': [{'permanent_buff': 7,
    'stack_count': 4,
    'grant_time': 559}],
  'party_size': 3,
  'team_number': 0,
  'team_slot': 3,
  'hero_id': 26,
  'hero_variant': 2,
  'item_0': 0,
  'item_1': 0,
  'item_2': 0,
  'item_3': 0,
  'item_4': 0,
  'item_5': 0,
  'backpack_0': 0,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 0,
  'kills': 4,
  'deaths': 10,
  'assists': 6,
  'leaver_status': 1,
  'last_hits': 58,
  'denies': 10,
  'gold_per_min': 376,
  'xp_per_min': 366,
  'level': 12,
  'net_worth': 102,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 10861,
  'tower_damage': 161,
  'hero_healing': 0,
  'gold': 0,
  'gold_spent': 6390,
  'ability_upgrades_arr': [5044,
   5046,
   5044,
   5046,
   5044,
   5047,
   5044,
   5045,
   5046,
   6600],
  'personaname': 'Rubick Dentista',
  'name': None,
  'last_login': None,
  'rank_tier': 80,
  'computed_mmr': 3881.87,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': True,
  'win': 0,
  'lose': 1,
  'total_gold': 9312,
  'total_xp': 9064,
  'kills_per_min': 0.16150740242261105,
  'kda': 0.91,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 376, 'pct': 0.637324809441849},
   'xp_per_min': {'raw': 366, 'pct': 0.12121957216621589},
   'kills_per_min': {'raw': 0.16150740242261102, 'pct': 0.5529874600442587},
   'last_hits_per_min': {'raw': 2.34185733512786, 'pct': 0.7750184411113843},
   'hero_damage_per_min': {'raw': 438.53297442799465,
    'pct': 0.6837964101303172},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.7656749446766659},
   'tower_damage': {'raw': 161, 'pct': 0.39168920580280303}}},
 {'player_slot': 4,
  'party_id': None,
  'permanent_buffs': [],
  'party_size': 0,
  'team_number': 0,
  'team_slot': 4,
  'hero_id': 41,
  'hero_variant': 3,
  'item_0': 26,
  'item_1': 116,
  'item_2': 147,
  'item_3': 166,
  'item_4': 149,
  'item_5': 63,
  'backpack_0': 6,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 945,
  'kills': 12,
  'deaths': 8,
  'assists': 1,
  'leaver_status': 0,
  'last_hits': 98,
  'denies': 3,
  'gold_per_min': 1430,
  'xp_per_min': 822,
  'level': 19,
  'net_worth': 30517,
  'aghanims_scepter': 1,
  'aghanims_shard': 1,
  'moonshard': 0,
  'hero_damage': 21635,
  'tower_damage': 0,
  'hero_healing': 0,
  'gold': 6392,
  'gold_spent': 25360,
  'ability_upgrades_arr': [5182,
   5691,
   5182,
   5184,
   5184,
   1281,
   5182,
   5182,
   5691,
   5184,
   5691,
   1281,
   5184,
   5691,
   6807,
   867,
   1281],
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': True,
  'win': 0,
  'lose': 1,
  'total_gold': 35416,
  'total_xp': 20358,
  'kills_per_min': 0.4845222072678331,
  'kda': 1.44,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 1430, 'pct': 1},
   'xp_per_min': {'raw': 822, 'pct': 0.5029617662897146},
   'kills_per_min': {'raw': 0.4845222072678331, 'pct': 0.9606892837910609},
   'last_hits_per_min': {'raw': 3.95693135935397, 'pct': 0.11039310716208939},
   'hero_damage_per_min': {'raw': 873.5531628532974,
    'pct': 0.8352180936995154},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.9375336564351104},
   'tower_damage': {'raw': 0, 'pct': 0.17932148626817448}}},
 {'account_id': 116181903,
  'player_slot': 128,
  'party_id': 3,
  'permanent_buffs': [{'permanent_buff': 12,
    'stack_count': 0,
    'grant_time': 1525}],
  'party_size': 1,
  'team_number': 1,
  'team_slot': 0,
  'hero_id': 63,
  'hero_variant': 1,
  'item_0': 166,
  'item_1': 168,
  'item_2': 596,
  'item_3': 75,
  'item_4': 23,
  'item_5': 36,
  'backpack_0': 205,
  'backpack_1': 1565,
  'backpack_2': 0,
  'item_neutral': 946,
  'kills': 13,
  'deaths': 2,
  'assists': 21,
  'leaver_status': 0,
  'last_hits': 68,
  'denies': 9,
  'gold_per_min': 528,
  'xp_per_min': 645,
  'level': 17,
  'net_worth': 12759,
  'aghanims_scepter': 0,
  'aghanims_shard': 1,
  'moonshard': 0,
  'hero_damage': 22962,
  'tower_damage': 3312,
  'hero_healing': 0,
  'gold': 929,
  'gold_spent': 12220,
  'ability_upgrades_arr': [5290,
   5291,
   5289,
   5290,
   5290,
   5292,
   5290,
   5291,
   5291,
   5291,
   5289,
   5292,
   5289,
   5289,
   6200,
   6987],
  'personaname': 'gemelli',
  'name': None,
  'last_login': None,
  'rank_tier': 72,
  'computed_mmr': 4226.62,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': False,
  'win': 1,
  'lose': 0,
  'total_gold': 13076,
  'total_xp': 15974,
  'kills_per_min': 0.5248990578734859,
  'kda': 11.33,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 528, 'pct': 0.5746031746031746},
   'xp_per_min': {'raw': 645, 'pct': 0.3468253968253968},
   'kills_per_min': {'raw': 0.5248990578734858, 'pct': 0.9507936507936507},
   'last_hits_per_min': {'raw': 2.7456258411843875,
    'pct': 0.18968253968253967},
   'hero_damage_per_min': {'raw': 927.1332436069987,
    'pct': 0.8150793650793651},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.8031746031746032},
   'tower_damage': {'raw': 3312, 'pct': 0.5301587301587302}}},
 {'account_id': 123760495,
  'player_slot': 129,
  'party_id': 4,
  'permanent_buffs': [],
  'party_size': 2,
  'team_number': 1,
  'team_slot': 1,
  'hero_id': 53,
  'hero_variant': 2,
  'item_0': 98,
  'item_1': 77,
  'item_2': 534,
  'item_3': 158,
  'item_4': 77,
  'item_5': 63,
  'backpack_0': 44,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 2097,
  'kills': 10,
  'deaths': 5,
  'assists': 21,
  'leaver_status': 0,
  'last_hits': 142,
  'denies': 1,
  'gold_per_min': 645,
  'xp_per_min': 629,
  'level': 16,
  'net_worth': 15069,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 19738,
  'tower_damage': 18736,
  'hero_healing': 0,
  'gold': 1019,
  'gold_spent': 14550,
  'ability_upgrades_arr': [5247,
   5245,
   5247,
   5246,
   5247,
   5248,
   5247,
   5246,
   5246,
   5246,
   926,
   5248,
   5245,
   5245,
   6500,
   5245],
  'personaname': 'Pepe Kafu Dida',
  'name': None,
  'last_login': '2026-04-26T13:53:45.457Z',
  'rank_tier': 54,
  'computed_mmr': None,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': False,
  'win': 1,
  'lose': 0,
  'total_gold': 15974,
  'total_xp': 15578,
  'kills_per_min': 0.4037685060565276,
  'kda': 5.17,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 645, 'pct': 0.7139282735613011},
   'xp_per_min': {'raw': 629, 'pct': 0.4353628023352794},
   'kills_per_min': {'raw': 0.4037685060565276, 'pct': 0.902418682235196},
   'last_hits_per_min': {'raw': 5.733512786002692, 'pct': 0.38365304420350294},
   'hero_damage_per_min': {'raw': 796.9582772543741,
    'pct': 0.6655546288573811},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.749791492910759},
   'tower_damage': {'raw': 18736, 'pct': 0.97581317764804}}},
 {'account_id': 1721437523,
  'player_slot': 130,
  'party_id': 4,
  'permanent_buffs': [{'permanent_buff': 12,
    'stack_count': 0,
    'grant_time': 1701}],
  'party_size': 2,
  'team_number': 1,
  'team_slot': 2,
  'hero_id': 97,
  'hero_variant': 2,
  'item_0': 73,
  'item_1': 63,
  'item_2': 1,
  'item_3': 223,
  'item_4': 252,
  'item_5': 36,
  'backpack_0': 43,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 946,
  'kills': 9,
  'deaths': 4,
  'assists': 16,
  'leaver_status': 0,
  'last_hits': 113,
  'denies': 10,
  'gold_per_min': 519,
  'xp_per_min': 471,
  'level': 14,
  'net_worth': 11985,
  'aghanims_scepter': 0,
  'aghanims_shard': 1,
  'moonshard': 0,
  'hero_damage': 14687,
  'tower_damage': 2956,
  'hero_healing': 0,
  'gold': 280,
  'gold_spent': 12410,
  'ability_upgrades_arr': [5518,
   5520,
   5518,
   5520,
   5518,
   5521,
   5518,
   5520,
   5520,
   5519,
   525,
   5521,
   5519,
   5519],
  'personaname': 'HELLO',
  'name': None,
  'last_login': None,
  'rank_tier': 53,
  'computed_mmr': None,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': False,
  'win': 1,
  'lose': 0,
  'total_gold': 12853,
  'total_xp': 11665,
  'kills_per_min': 0.3633916554508749,
  'kda': 5,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 519, 'pct': 0.7656157049375372},
   'xp_per_min': {'raw': 471, 'pct': 0.18143961927424151},
   'kills_per_min': {'raw': 0.3633916554508748, 'pct': 0.9417013682331945},
   'last_hits_per_min': {'raw': 4.562584118438762, 'pct': 0.6400951814396193},
   'hero_damage_per_min': {'raw': 593.0148048452221,
    'pct': 0.7590719809637121},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.8007138607971446},
   'tower_damage': {'raw': 2956, 'pct': 0.8304580606781677}}},
 {'account_id': 370032141,
  'player_slot': 131,
  'party_id': 5,
  'permanent_buffs': [],
  'party_size': 1,
  'team_number': 1,
  'team_slot': 3,
  'hero_id': 31,
  'hero_variant': 1,
  'item_0': 180,
  'item_1': 36,
  'item_2': 218,
  'item_3': 102,
  'item_4': 254,
  'item_5': 39,
  'backpack_0': 216,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 356,
  'kills': 5,
  'deaths': 5,
  'assists': 25,
  'leaver_status': 0,
  'last_hits': 12,
  'denies': 1,
  'gold_per_min': 367,
  'xp_per_min': 534,
  'level': 15,
  'net_worth': 7917,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 15012,
  'tower_damage': 1267,
  'hero_healing': 0,
  'gold': 1352,
  'gold_spent': 7950,
  'ability_upgrades_arr': [5134,
   5136,
   5134,
   7325,
   5134,
   5137,
   5134,
   7325,
   7325,
   7325,
   5136,
   5137,
   5136,
   5136],
  'personaname': 'EG. Peluchin',
  'name': None,
  'last_login': None,
  'rank_tier': 65,
  'computed_mmr': 4051.33,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': False,
  'win': 1,
  'lose': 0,
  'total_gold': 9089,
  'total_xp': 13225,
  'kills_per_min': 0.2018842530282638,
  'kda': 5,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 367, 'pct': 0.559678416821274},
   'xp_per_min': {'raw': 534, 'pct': 0.4131106988249845},
   'kills_per_min': {'raw': 0.2018842530282638, 'pct': 0.7983920841063699},
   'last_hits_per_min': {'raw': 0.4845222072678331,
    'pct': 0.02350030921459493},
   'hero_damage_per_min': {'raw': 606.1372812920592,
    'pct': 0.7470624613481757},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.6567717996289425},
   'tower_damage': {'raw': 1267, 'pct': 0.8942486085343229}}},
 {'account_id': 149793379,
  'player_slot': 132,
  'party_id': 6,
  'permanent_buffs': [],
  'party_size': 1,
  'team_number': 1,
  'team_slot': 4,
  'hero_id': 123,
  'hero_variant': 2,
  'item_0': 55,
  'item_1': 25,
  'item_2': 149,
  'item_3': 180,
  'item_4': 25,
  'item_5': 166,
  'backpack_0': 0,
  'backpack_1': 0,
  'backpack_2': 0,
  'item_neutral': 945,
  'kills': 9,
  'deaths': 6,
  'assists': 15,
  'leaver_status': 0,
  'last_hits': 73,
  'denies': 5,
  'gold_per_min': 470,
  'xp_per_min': 453,
  'level': 14,
  'net_worth': 9794,
  'aghanims_scepter': 0,
  'aghanims_shard': 0,
  'moonshard': 0,
  'hero_damage': 18532,
  'tower_damage': 3781,
  'hero_healing': 0,
  'gold': 444,
  'gold_spent': 10430,
  'ability_upgrades_arr': [8429,
   8158,
   8158,
   8429,
   8158,
   8106,
   8429,
   8429,
   8158,
   9510,
   9501,
   8106,
   9501,
   9501],
  'personaname': 'Astro~',
  'name': None,
  'last_login': '2017-04-28T22:11:15.758Z',
  'rank_tier': 61,
  'computed_mmr': 4147.69,
  'is_subscriber': False,
  'radiant_win': False,
  'start_time': 1737850880,
  'duration': 1486,
  'cluster': 202,
  'lobby_type': 0,
  'game_mode': 4,
  'is_contributor': False,
  'patch': 56,
  'region': 10,
  'isRadiant': False,
  'win': 1,
  'lose': 0,
  'total_gold': 11640,
  'total_xp': 11219,
  'kills_per_min': 0.3633916554508749,
  'kda': 3.43,
  'abandons': 0,
  'benchmarks': {'gold_per_min': {'raw': 470, 'pct': 0.8233970753655793},
   'xp_per_min': {'raw': 453, 'pct': 0.21484814398200225},
   'kills_per_min': {'raw': 0.3633916554508748, 'pct': 0.9516310461192351},
   'last_hits_per_min': {'raw': 2.9475100942126513, 'pct': 0.6636670416197975},
   'hero_damage_per_min': {'raw': 748.2637954239569, 'pct': 0.904949381327334},
   'hero_healing_per_min': {'raw': 0, 'pct': 0.6344206974128234},
   'tower_damage': {'raw': 3781, 'pct': 0.9302587176602924}}}]

In [ ]:
dados_partida.get("start_time")

1361057030

In [ ]:
chat = dados_partida.get("metadata")
chat

In [ ]:

def buscar_chat_partida(match_id):
    url = f"https://api.opendota.com/api/matches/{match_id}"

    try:
        print(f"Buscando detalhes da partida {match_id}...")
        response = requests.get(url)
        response.raise_for_status()

        dados_partida = response.json()
        chat = dados_partida.get('chat')

        if chat is None:
            return "O chat não está disponível para esta partida (pode não ter sido parseada)."

        if len(chat) == 0:
            return "Nenhuma mensagem de chat encontrada nesta partida."

        # Formatando as mensagens para leitura
        mensagens_formatadas = []
        for msg in chat:
            # 'type' pode ser 'chat' (texto normal) ou 'chatwheel' (roda de mensagens)
            tipo = msg.get('type')
            tempo = msg.get('time') # Tempo em segundos desde o início do jogo
            jogador = msg.get('unit', f"Jogador {msg.get('player_slot')}")
            texto = msg.get('key', '') #if tipo == 'chatwheel' else msg.get('key', '')

            # Converter tempo em formato MM:SS
            minutos = int(tempo // 60)
            segundos = int(tempo % 60)
            timestamp = f"{minutos:02d}:{segundos:02d}"

            mensagens_formatadas.append(f"[{timestamp}] {jogador}: {texto}")

        return mensagens_formatadas

    except requests.exceptions.RequestException as e:
        return f"Erro ao acessar a API: {e}"

# Exemplo de uso:
ID_PARTIDA = "8638178478" # Substitua por um ID real
historico_chat = buscar_chat_partida(ID_PARTIDA)

if isinstance(historico_chat, list):
    for linha in historico_chat:
        print(linha)
else:
    print(historico_chat)

Buscando detalhes da partida 8638178478...
[01:43] Jogador 129: 107002
[19:06] Jogador 2: 41001
[19:20] Jogador 2: 41001
[28:18] Jogador 3: 47003
[28:21] Jogador 0: wp

In [ ]:
buscar_chat_partida(8840176834)

Buscando detalhes da partida 8840176834...

'Erro ao acessar a API: 500 Server Error: Internal Server Error for url: https://api.opendota.com/api/matches/8840176834'

In [ ]:
def integrar_chats_ao_dataframe(df_partidas):
    if df_partidas is None or df_partidas.empty:
        print("DataFrame vazio ou inválido.")
        return None

    print(f"Iniciando a busca de chat para {len(df_partidas)} partidas...")

    # Criamos uma lista para armazenar os resultados temporariamente
    todos_os_chats = []

    for index, row in df_partidas.iterrows():
        match_id = row['match_id']

        # Chama a função que criamos anteriormente
        resultado_chat = buscar_chat_partida(match_id)

        # Se o resultado for uma lista (mensagens), juntamos em uma única string
        # Se for erro ou string de aviso, salvamos a mensagem de erro
        if isinstance(resultado_chat, list):
            chat_texto = " | ".join(resultado_chat)
        else:
            chat_texto = resultado_chat

        todos_os_chats.append(chat_texto)

        # Pausa de 1 segundo entre requisições para respeitar o limite da API gratuita
        time.sleep(1)
        print(f"Processado {index + 1}/{len(df_partidas)} (Match ID: {match_id})")

    # Adiciona a nova coluna ao DataFrame
    df_partidas['chat_log'] = todos_os_chats

    return df_partidas

# --- EXECUÇÃO ---

# 1. Recupera as últimas 10 partidas de um jogador
df_inicial = buscar_partidas_jogador(PLAYER_ID)

# 2. Enriquece o DataFrame com o chat
df_final = integrar_chats_ao_dataframe(df_inicial)

# 3. Exibe o resultado
print("\nDataFrame Atualizado:")
print(df_final[['match_id', 'chat_log']].head())

Buscando partidas para o ID: 123760495...
Iniciando a busca de chat para 2582 partidas...
Buscando detalhes da partida 8145780410...
Processado 1/2582 (Match ID: 8145780410)
Buscando detalhes da partida 8145745528...
Processado 2/2582 (Match ID: 8145745528)
Buscando detalhes da partida 7029360506...
Processado 3/2582 (Match ID: 7029360506)
Buscando detalhes da partida 7017477496...
Processado 4/2582 (Match ID: 7017477496)
Buscando detalhes da partida 6745498263...
Processado 5/2582 (Match ID: 6745498263)
Buscando detalhes da partida 6592914637...
Processado 6/2582 (Match ID: 6592914637)
Buscando detalhes da partida 6592592077...
Processado 7/2582 (Match ID: 6592592077)
Buscando detalhes da partida 6404838878...
Processado 8/2582 (Match ID: 6404838878)
Buscando detalhes da partida 6363488061...
Processado 9/2582 (Match ID: 6363488061)
Buscando detalhes da partida 6355846488...
Processado 10/2582 (Match ID: 6355846488)
Buscando detalhes da partida 6276423932...
Processado 11/2582 (Match ID: 6276423932)
Buscando detalhes da partida 6276246085...
Processado 12/2582 (Match ID: 6276246085)
Buscando detalhes da partida 6273544901...
Processado 13/2582 (Match ID: 6273544901)
Buscando detalhes da partida 6273508065...
Processado 14/2582 (Match ID: 6273508065)
Buscando detalhes da partida 6270051484...
Processado 15/2582 (Match ID: 6270051484)
Buscando detalhes da partida 6267071599...
Processado 16/2582 (Match ID: 6267071599)
Buscando detalhes da partida 6266283576...
Processado 17/2582 (Match ID: 6266283576)
Buscando detalhes da partida 6265469611...
Processado 18/2582 (Match ID: 6265469611)
Buscando detalhes da partida 6264551962...
Processado 19/2582 (Match ID: 6264551962)
Buscando detalhes da partida 6263957763...
Processado 20/2582 (Match ID: 6263957763)
Buscando detalhes da partida 6263934670...
Processado 21/2582 (Match ID: 6263934670)
Buscando detalhes da partida 6263886045...
Processado 22/2582 (Match ID: 6263886045)
Buscando detalhes da partida 6263814871...
Processado 23/2582 (Match ID: 6263814871)
Buscando detalhes da partida 6263783586...
Processado 24/2582 (Match ID: 6263783586)
Buscando detalhes da partida 6263746921...
Processado 25/2582 (Match ID: 6263746921)
Buscando detalhes da partida 6263703887...
Processado 26/2582 (Match ID: 6263703887)
Buscando detalhes da partida 6263600483...
Processado 27/2582 (Match ID: 6263600483)
Buscando detalhes da partida 6263509934...
Processado 28/2582 (Match ID: 6263509934)
Buscando detalhes da partida 6262137982...
Processado 29/2582 (Match ID: 6262137982)
Buscando detalhes da partida 6262098050...
Processado 30/2582 (Match ID: 6262098050)
Buscando detalhes da partida 6262073251...
Processado 31/2582 (Match ID: 6262073251)
Buscando detalhes da partida 6262027905...
Processado 32/2582 (Match ID: 6262027905)
Buscando detalhes da partida 6261673322...
Processado 33/2582 (Match ID: 6261673322)
Buscando detalhes da partida 6261582957...
Processado 34/2582 (Match ID: 6261582957)
Buscando detalhes da partida 6261511165...
Processado 35/2582 (Match ID: 6261511165)
Buscando detalhes da partida 6261439556...
Processado 36/2582 (Match ID: 6261439556)
Buscando detalhes da partida 6261327982...
Processado 37/2582 (Match ID: 6261327982)
Buscando detalhes da partida 6259764162...
Processado 38/2582 (Match ID: 6259764162)
Buscando detalhes da partida 6258444019...
Processado 39/2582 (Match ID: 6258444019)
Buscando detalhes da partida 6258387593...
Processado 40/2582 (Match ID: 6258387593)
Buscando detalhes da partida 6258326619...
Processado 41/2582 (Match ID: 6258326619)
Buscando detalhes da partida 6176814564...
Processado 42/2582 (Match ID: 6176814564)
Buscando detalhes da partida 6153501080...
Processado 43/2582 (Match ID: 6153501080)
Buscando detalhes da partida 6152250342...
Processado 44/2582 (Match ID: 6152250342)
Buscando detalhes da partida 6152189024...

KeyboardInterrupt:

In [ ]:
#url = f"https://api.opendota.com/api/players/{player_id}/matches"
url = f"https://api.opendota.com/api/matches/{8145780410}"
response = requests.get(url)

# Verifica se a requisição foi bem sucedida (Status 200)
response.raise_for_status()

detalhePartida = response.json()
detalhesPartida

NameError: name 'detalhesPartida' is not defined

In [ ]:
def solicitar_parse_partida(match_id):
    # O endpoint para POST é /requests/{match_id}
    url = f"https://api.opendota.com/api/requests/{match_id}"


    try:
        print(f"Enviando solicitação de parse para a partida {match_id}...")

        # Note que usamos requests.post() em vez de get()
        response = requests.post(url)

        # Verifica se a API aceitou a requisição (Status 200 ou 201)
        response.raise_for_status()

        dados = response.json()

        # A API retorna um objeto confirmando que a partida entrou na fila
        if 'job' in dados:
            job_id = dados['job'].get('jobId')
            print(f"Sucesso! Partida colocada na fila de processamento.")
            print(f"ID do Trabalho (Job ID): {job_id}")
            return dados
        else:
            return "A resposta foi recebida, mas o formato foi inesperado."

    except requests.exceptions.RequestException as e:
        # Erro 429 geralmente significa que você atingiu o limite de parses gratuitos
        return f"Erro ao solicitar parse: {e}"

# Exemplo de uso
resultado = solicitar_parse_partida(match_id)
print(resultado)

NameError: name 'match_id' is not defined

In [ ]:
historico_chat

In [ ]:
constants("")

Erro ao acessar a API: 404 Client Error: Not Found for url: https://api.opendota.com/api/constants/

In [ ]:
def constants(resource):
  return realiza_request(f"https://api.opendota.com/api/constants/{resource}")

chat_whells = constants("chat_wheel")
chat_whells

{'0': {'id': 0, 'name': 'Ok', 'label': 'Okay', 'message': 'Okay.'},
 '1': {'id': 1, 'name': 'Care', 'label': 'Care', 'message': 'Careful!'},
 '2': {'id': 2,
  'name': 'GetBack',
  'label': 'Get Back',
  'message': 'Get Back!'},
 '3': {'id': 3,
  'name': 'NeedWards',
  'label': 'Need Wards',
  'message': 'We need wards.'},
 '4': {'id': 4, 'name': 'Stun', 'label': 'Stun', 'message': 'Stun now!'},
 '5': {'id': 5, 'name': 'Help', 'label': 'Help', 'message': 'Help!'},
 '6': {'id': 6, 'name': 'Push', 'label': 'Push', 'message': 'Push now'},
 '7': {'id': 7,
  'name': 'GoodJob',
  'label': 'Well played',
  'message': 'Well played!'},
 '8': {'id': 8, 'name': 'Missing', 'label': 'Missing', 'message': 'Missing!'},
 '9': {'id': 9,
  'name': 'Missing_Top',
  'label': 'Missing top',
  'message': 'Missing top!'},
 '10': {'id': 10,
  'name': 'Missing_Mid',
  'label': 'Missing mid',
  'message': 'Missing mid!'},
 '11': {'id': 11,
  'name': 'Missing_Bottom',
  'label': 'Missing bottom',
  'message': 'Missing bottom!'},
 '12': {'id': 12, 'name': 'Go', 'label': 'Go!', 'message': 'Go!'},
 '13': {'id': 13,
  'name': 'Initiate',
  'label': 'Initiate!',
  'message': 'Initiate!'},
 '14': {'id': 14,
  'name': 'Follow',
  'label': 'Follow me',
  'message': 'Follow me'},
 '15': {'id': 15,
  'name': 'Group_Up',
  'label': 'Group up',
  'message': 'Group up'},
 '16': {'id': 16,
  'name': 'Spread_Out',
  'label': 'Spread out',
  'message': 'Spread out'},
 '17': {'id': 17,
  'name': 'Split_Farm',
  'label': 'Split farm',
  'message': 'Split up and farm'},
 '18': {'id': 18,
  'name': 'Attack',
  'label': 'Attack now!',
  'message': 'Attack now!'},
 '19': {'id': 19,
  'name': 'BRB',
  'label': 'Be right back',
  'message': 'Be right back'},
 '20': {'id': 20, 'name': 'Dive', 'label': 'Dive!', 'message': 'Dive!'},
 '21': {'id': 21, 'name': 'OMW', 'label': 'On my way', 'message': 'On my way'},
 '22': {'id': 22,
  'name': 'Get_Ready',
  'label': 'Get ready',
  'message': 'Get ready'},
 '23': {'id': 23, 'name': 'Bait', 'label': 'Bait', 'message': 'Bait'},
 '24': {'id': 24, 'name': 'Heal', 'label': 'Heal', 'message': 'Heal'},
 '25': {'id': 25, 'name': 'Mana', 'label': 'Mana', 'message': 'Mana'},
 '26': {'id': 26,
  'name': 'OOM',
  'label': 'Out of mana',
  'message': 'Out of mana'},
 '27': {'id': 27,
  'name': 'Skill_Cooldown',
  'label': 'Cooldown',
  'message': 'Skills on cooldown'},
 '28': {'id': 28,
  'name': 'Ulti_Ready',
  'label': 'Ultimate ready',
  'message': 'Ultimate ready'},
 '29': {'id': 29,
  'name': 'Enemy_Returned',
  'label': 'Returned',
  'message': 'Enemy returned'},
 '30': {'id': 30,
  'name': 'All_Missing',
  'label': 'All miss',
  'message': 'All enemy heroes missing!'},
 '31': {'id': 31,
  'name': 'Enemy_Incoming',
  'label': 'Incoming',
  'message': 'Enemy incoming!'},
 '32': {'id': 32,
  'name': 'Invis_Enemy',
  'label': 'Invisible enemy',
  'message': 'Invisible enemy nearby!'},
 '33': {'id': 33,
  'name': 'Enemy_Had_Rune',
  'label': 'Enemy has rune',
  'message': 'Enemy has rune'},
 '34': {'id': 34,
  'name': 'Split_Push',
  'label': 'Split push',
  'message': 'Split push'},
 '35': {'id': 35,
  'name': 'Coming_To_Gank',
  'label': 'Coming to gank',
  'message': 'Coming to gank'},
 '36': {'id': 36,
  'name': 'Request_Gank',
  'label': 'Request gank',
  'message': 'Requesting a gank'},
 '37': {'id': 37,
  'name': 'Fight_Under_Tower',
  'label': 'Under tower',
  'message': 'Fight under the tower'},
 '38': {'id': 38,
  'name': 'Deny_Tower',
  'label': 'Deny tower',
  'message': 'Deny the tower!'},
 '41': {'id': 41,
  'name': 'Need_Detection',
  'label': 'We need detection',
  'message': 'We need detection'},
 '42': {'id': 42,
  'name': 'They_Have_Detection',
  'label': 'They have detection',
  'message': 'They have detection'},
 '43': {'id': 43,
  'name': 'Buy_TP',
  'label': 'Buy Town Portal Scroll',
  'message': 'Buy a Town Portal Scroll'},
 '45': {'id': 45,
  'name': 'Deward',
  'label': 'Deward',
  'message': 'Deward please'},
 '46': {'id': 46,
  'name': 'Building_Mek',
  'label': 'Building Mekansm',
  'message': 'Building Mekansm'},
 '47': {'id': 47,
  'name': 'Building_Pipe',
  'label': 'Building Pipe of Insight',
  'message': 'Building Pipe of Insight'},
 '48': {'id': 48,
  'name': 'Stack_And_Pull',
  'label': 'Stack and pull',
  'message': 'Stack and pull please'},
 '49': {'id': 49,
  'name': 'Pull',
  'label': 'Pull creeps',
  'message': 'Pull creeps please'},
 '50': {'id': 50,
  'name': 'Pulling',
  'label': 'Pulling creeps',
  'message': 'Pulling creeps'},
 '51': {'id': 51,
  'name': 'Stack',
  'label': 'Stack neutrals',
  'message': 'Stack neutrals'},
 '52': {'id': 52,
  'name': 'Jungling',
  'label': 'Jungling',
  'message': 'Jungling'},
 '53': {'id': 53, 'name': 'Roshan', 'label': 'Roshan', 'message': 'Roshan'},
 '54': {'id': 54,
  'name': 'Affirmative',
  'label': 'Affirmative',
  'message': 'Affirmative'},
 '55': {'id': 55, 'name': 'Wait', 'label': 'Wait', 'message': 'Wait'},
 '56': {'id': 56,
  'name': 'Pause',
  'label': 'Pause',
  'message': 'Pause please!'},
 '57': {'id': 57,
  'name': 'Current_Time',
  'label': 'Current Time',
  'message': 'Current Game Time'},
 '58': {'id': 58,
  'name': 'Check_Runes',
  'label': 'Check runes',
  'message': 'Check runes please'},
 '59': {'id': 59,
  'name': 'Smoke_Gank',
  'label': 'Smoke gank!',
  'message': "Let's smoke gank!"},
 '60': {'id': 60,
  'name': 'GLHF',
  'label': 'Good luck',
  'message': 'Good luck, have fun'},
 '61': {'id': 61, 'name': 'Nice', 'label': 'Nice', 'message': 'Nice'},
 '62': {'id': 62, 'name': 'Thanks', 'label': 'Thanks', 'message': 'Thanks!'},
 '63': {'id': 63, 'name': 'Sorry', 'label': 'Sorry', 'message': 'Sorry'},
 '64': {'id': 64,
  'name': 'No_Give_Up',
  'label': "Don't give up",
  'message': "Don't give up!"},
 '65': {'id': 65,
  'name': 'Just_Happened',
  'label': 'That just happened',
  'message': 'That just happened'},
 '66': {'id': 66,
  'name': 'Game_Is_Hard',
  'label': 'Game is hard',
  'message': 'Game is hard'},
 '67': {'id': 67,
  'name': 'New_Meta',
  'label': 'New meta',
  'message': 'New meta'},
 '68': {'id': 68, 'name': 'My_Bad', 'label': 'My bad', 'message': 'My bad'},
 '69': {'id': 69,
  'name': 'Regret',
  'label': 'Regret',
  'message': 'I immediately regret my decision'},
 '70': {'id': 70,
  'name': 'Relax',
  'label': 'Relax',
  'message': "Relax, you're doing fine"},
 '71': {'id': 71,
  'name': 'MissingHero',
  'label': 'dota_chatwheel_label_MissingHero',
  'message': 'dota_chatwheel_message_MissingHero'},
 '72': {'id': 72,
  'name': 'ReturnedHero',
  'label': 'dota_chatwheel_label_ReturnedHero',
  'message': 'dota_chatwheel_message_ReturnedHero'},
 '73': {'id': 73, 'name': 'GG', 'label': 'GG', 'message': 'Good game'},
 '74': {'id': 74,
  'name': 'GGWP',
  'label': 'GGWP',
  'message': 'Good game, well played'},
 '75': {'id': 75,
  'name': 'All_GG',
  'all_chat': True,
  'label': 'GG',
  'message': 'Good game'},
 '76': {'id': 76,
  'name': 'All_GGWP',
  'all_chat': True,
  'label': 'GGWP',
  'message': 'Good game, well played'},
 '77': {'id': 77,
  'name': 'What_To_Buy',
  'label': 'What should I buy?',
  'message': 'What should I buy?'},
 '78': {'id': 78,
  'name': 'Im_Retreating',
  'label': "I'm retreating",
  'message': "I'm retreating"},
 '79': {'id': 79,
  'name': 'Space_Created',
  'label': 'Space created',
  'message': 'Space created'},
 '80': {'id': 80, 'name': 'Whoops', 'label': 'Whoops', 'message': 'Whoops'},
 '81': {'id': 81,
  'name': 'Tower_then_Back',
  'label': 'Tower then back',
  'message': 'Destroy the tower, then get back'},
 '82': {'id': 82,
  'name': 'Barracks_then_Back',
  'label': 'Barracks then back',
  'message': 'Destroy the barracks, then get back'},
 '83': {'id': 83,
  'name': 'Ward_Bottom_Rune',
  'label': 'Ward bot rune',
  'message': 'Ward the bottom rune'},
 '84': {'id': 84,
  'name': 'Ward_Top_Rune',
  'label': 'Ward top rune',
  'message': 'Ward the top rune'},
 '85': {'id': 85,
  'name': 'Zeus_Ult',
  'label': 'Zeus Ult',
  'message': 'Zeus Ult Now!'},
 '86': {'id': 86,
  'name': 'Rimshot',
  'label': 'Ba-dum tishh',
  'message': 'Ba-dum tishh',
  'sound_ext': 'wav'},
 '87': {'id': 87,
  'name': 'Charge',
  'label': 'Charge',
  'message': 'Charge',
  'sound_ext': 'wav'},
 '88': {'id': 88,
  'name': 'Frog',
  'label': 'Frog',
  'message': 'Frog',
  'sound_ext': 'wav'},
 '89': {'id': 89,
  'name': 'Crash_and_Burn',
  'label': 'Crash',
  'message': 'Crash and burn',
  'sound_ext': 'wav'},
 '90': {'id': 90,
  'name': 'Applause',
  'label': 'Applause',
  'message': 'Applause',
  'sound_ext': 'wav'},
 '91': {'id': 91,
  'name': 'Sad_Trombone',
  'label': 'Sad trombone',
  'message': 'Sad trombone',
  'sound_ext': 'wav'},
 '92': {'id': 92,
  'name': 'Crickets',
  'label': 'Crickets',
  'message': 'Crickets',
  'sound_ext': 'wav'},
 '93': {'id': 93,
  'name': 'Drum_Roll',
  'label': 'Drum roll',
  'message': 'Drum roll',
  'sound_ext': 'wav'},
 '94': {'id': 94,
  'name': 'Headshake',
  'label': 'Headshake',
  'message': 'Headshake',
  'sound_ext': 'wav'},
 '95': {'id': 95,
  'name': 'Crybaby',
  'label': 'Crybaby',
  'message': 'Crybaby',
  'sound_ext': 'wav'},
 '96': {'id': 96,
  'name': 'Patience',
  'label': 'Patience',
  'message': 'Patience from Zhou',
  'sound_ext': 'wav'},
 '101': {'id': 101,
  'name': 'Bozhe_Ti_Posmotri',
  'label': 'Что Происходит',
  'message': 'Боже, ты посмотри вокруг, что происходит!',
  'sound_ext': 'wav'},
 '111': {'id': 111,
  'name': 'Day_Night_Cycle',
  'label': 'Day/Night Cycle',
  'message': 'dota_chatwheel_message_Day_Night_Cycle'},
 '112': {'id': 112,
  'name': 'Thats_Playing_to_Win',
  'label': "That's Playing to Win!",
  'message': "That's playing to win, baby!",
  'sound_ext': 'wav'},
 '114': {'id': 114,
  'name': 'Absolutely_Perfect',
  'label': 'Absolutely Perfect',
  'message': 'Absolutely Perfect',
  'sound_ext': 'wav'},
 '115': {'id': 115,
  'name': 'Looking_Spicy',
  'label': 'Looking Spicy',
  'message': "It's looking Spicy!",
  'sound_ext': 'wav'},
 '116': {'id': 116,
  'name': 'No_Chill',
  'label': 'No Chill!',
  'message': 'This guy has no chill',
  'sound_ext': 'wav'},
 '117': {'id': 117,
  'name': 'Lets_Play_Dota',
  'label': "Let's Play Dota",
  'message': "Let's Play Some Dota",
  'sound_ext': 'wav'},
 '118': {'id': 118,
  'name': 'Waow',
  'all_chat': True,
  'label': 'Waow',
  'message': 'Waow',
  'sound_ext': 'wav'},
 '119': {'id': 119,
  'name': 'What_Just_Happened',
  'label': 'What Just Happened?',
  'message': "I can't believe what we're seeing. What just happened?",
  'sound_ext': 'wav'},
 '120': {'id': 120,
  'name': 'Youre_a_Hero',
  'label': "You're a Goddamn Hero!",
  'message': "You're a goddamn hero!",
  'sound_ext': 'wav'},
 '121': {'id': 121,
  'name': 'All_Dead',
  'label': 'All Dead',
  'message': "They're all dead!",
  'sound_ext': 'wav'},
 '122': {'id': 122,
  'name': 'Ding_Ding_Ding',
  'all_chat': True,
  'label': 'Ding Ding Ding!',
  'message': 'Ding Ding Ding Mother******',
  'sound_ext': 'wav'},
 '131': {'id': 131,
  'name': 'Bockbock',
  'label': 'Bock bock',
  'message': 'Bock bock',
  'sound_ext': 'wav'},
 '132': {'id': 132,
  'name': 'Kiss',
  'label': 'Kiss',
  'message': 'Kiss',
  'sound_ext': 'wav'},
 '133': {'id': 133,
  'name': 'Ow',
  'label': 'Oww',
  'message': 'Oww',
  'sound_ext': 'wav'},
 '134': {'id': 134,
  'name': 'Party_Horn',
  'label': 'Party horn',
  'message': 'Party horn',
  'sound_ext': 'wav'},
 '135': {'id': 135,
  'name': 'Snore',
  'label': 'Snore',
  'message': 'Snore',
  'sound_ext': 'wav'},
 '136': {'id': 136,
  'name': 'Yahoo',
  'label': 'Yahoo',
  'message': 'Yahoo',
  'sound_ext': 'wav'},
 '137': {'id': 137,
  'name': 'Happy_Tree',
  'image': 'sprays/liltree_happy_spray_icon.png'},
 '138': {'id': 138,
  'name': 'High_Five',
  'image': 'sprays/furbolg_highfive_spray_icon.png'},
 '139': {'id': 139,
  'name': 'Zen',
  'image': 'sprays/monkey_zen_spray_icon.png'},
 '140': {'id': 140,
  'name': 'Thumbs_Up',
  'image': 'sprays/tide_thumbsup_spray_icon.png'},
 '141': {'id': 141, 'name': 'Funny', 'image': 'sprays/lion_xd_spray_icon.png'},
 '142': {'id': 142, 'name': 'Cry', 'image': 'sprays/bear_cry_spray_icon.png'},
 '143': {'id': 143,
  'name': 'Shrug',
  'image': 'sprays/sf_shrug_spray_icon.png'},
 '144': {'id': 144,
  'name': 'Sad_Tree',
  'image': 'sprays/liltree_sad_spray_icon.png'},
 '145': {'id': 145,
  'name': 'Angry',
  'image': 'sprays/lina_angry_spray_icon.png'},
 '146': {'id': 146,
  'name': 'Question',
  'image': 'sprays/shaker_confus_spray_icon.png'},
 '147': {'id': 147,
  'name': 'Shhh',
  'image': 'sprays/mirana_shh_spray_icon.png'},
 '148': {'id': 148,
  'name': 'Nervous',
  'image': 'sprays/naturesprophet_o_o_spray_icon.png'},
 '149': {'id': 149,
  'name': 'Thinking',
  'image': 'sprays/invoker_smart_spray_icon.png'},
 '150': {'id': 150,
  'name': 'Just_Right',
  'image': 'sprays/pudge_nailedit_spray_icon.png'},
 '151': {'id': 151,
  'name': 'Whoa',
  'image': 'sprays/monkeyking_monkeychamp_spray_icon.png'},
 '152': {'id': 152,
  'name': 'Easiest_Money',
  'all_chat': True,
  'label': 'Easiest Money',
  'message': 'Easiest money of my life!',
  'sound_ext': 'wav'},
 '153': {'id': 153,
  'name': 'Echo_Slama_Jama',
  'all_chat': True,
  'label': 'Echo Slamma Jamma',
  'message': 'Echo Slamma Jamma!',
  'sound_ext': 'wav'},
 '154': {'id': 154,
  'name': 'Next_Level',
  'all_chat': True,
  'label': 'Next Level',
  'message': 'The next level play!',
  'sound_ext': 'wav'},
 '155': {'id': 155,
  'name': 'Oy_Oy_Oy',
  'all_chat': True,
  'label': 'Oyoy oy oy',
  'message': 'Oyoy oy oy, oy, oy, oy Oy OY!',
  'sound_ext': 'wav'},
 '156': {'id': 156,
  'name': 'Lakad_Matataaaag',
  'all_chat': True,
  'label': 'Lakad Matataaaag!',
  'message': 'Lakad Matataaaag! Normalin Normalin.',
  'sound_ext': 'wav'},
 '157': {'id': 157,
  'name': 'FavoriteTeam',
  'label': 'Favorite Team Spray',
  'image': 'sprays/favorite_team_%d.png'},
 '158': {'id': 158,
  'name': 'Greevil_Laughter',
  'all_chat': True,
  'label': 'Greevil Laughter',
  'message': 'Greevil Laughter',
  'sound_ext': 'wav'},
 '159': {'id': 159,
  'name': 'Sparkling_Celebration',
  'label': 'Sparkling Celebration',
  'message': 'Sparkling Celebration',
  'sound_ext': 'wav'},
 '160': {'id': 160,
  'name': 'Frostivus_Magic',
  'all_chat': True,
  'label': 'Frostivus Magic',
  'message': 'Frostivus Magic',
  'sound_ext': 'wav'},
 '161': {'id': 161,
  'name': 'Sleighbells',
  'label': 'Sleighbells',
  'message': 'Sleighbells',
  'sound_ext': 'wav'},
 '162': {'id': 162,
  'name': 'NewBloom_Ceremonial_Drums',
  'label': 'Ceremonial Drums',
  'message': 'Ceremonial Drums',
  'sound_ext': 'wav'},
 '163': {'id': 163,
  'name': 'NewBloom_Oink_Oink',
  'label': 'Oink Oink!',
  'message': 'Oink Oink!',
  'sound_ext': 'wav'},
 '164': {'id': 164,
  'name': 'NewBloom_Celebratory_Gong',
  'all_chat': True,
  'label': 'Celebratory Gong',
  'message': 'Celebratory Gong',
  'sound_ext': 'wav'},
 '165': {'id': 165,
  'name': 'Kooka_Laugh',
  'label': 'Kookaburra Laugh',
  'message': 'Kookaburra Laugh',
  'sound_ext': 'wav'},
 '166': {'id': 166,
  'name': 'Monkey_Business',
  'label': 'Monkey Business',
  'message': 'Monkey Business',
  'sound_ext': 'wav'},
 '167': {'id': 167,
  'name': 'Orangutan_Kiss',
  'label': 'Sloppy Orangutan Kiss',
  'message': 'Sloppy Orangutan Kiss',
  'sound_ext': 'wav'},
 '168': {'id': 168,
  'name': 'Mosquito_Buzz',
  'label': 'Mosquito Buzz',
  'message': 'Mosquito Buzz',
  'sound_ext': 'wav'},
 '169': {'id': 169,
  'name': 'Crowd_Groan',
  'label': 'Crowd Groan',
  'message': 'Crowd Groan',
  'sound_ext': 'wav'},
 '170': {'id': 170,
  'name': 'Head_Bonk',
  'label': 'Head Bonk',
  'message': 'Head Bonk',
  'sound_ext': 'wav'},
 '171': {'id': 171,
  'name': 'Record_Scratch',
  'label': 'Record Scratch',
  'message': 'Record Scratch',
  'sound_ext': 'wav'},
 '172': {'id': 172,
  'name': 'Ta_Daaaaaa',
  'label': 'Ta Daaaaaa',
  'message': 'Ta Daaaaaa',
  'sound_ext': 'wav'},
 '173': {'id': 173,
  'name': 'Ay_Ay_Ay',
  'label': 'Ай-ай-ай-ай-ай',
  'message': 'Ай-ай-ай-ай-ай, что сейчас произошло',
  'sound_ext': 'wav'},
 '174': {'id': 174,
  'name': 'Ehto_G_G',
  'label': 'Это ГГ',
  'message': 'Это ГГ',
  'sound_ext': 'wav'},
 '175': {'id': 175,
  'name': 'Oy_Oy_Bezhat',
  'label': 'Ой-ой-ой-ой-ой, бежать!',
  'message': 'Ой-ой-ой-ой-ой, бежать!',
  'sound_ext': 'wav'},
 '176': {'id': 176,
  'name': 'Eto_Sochno',
  'all_chat': True,
  'label': 'Как же это сочно, ах!',
  'message': 'Как же это сочно, ах!',
  'sound_ext': 'wav'},
 '177': {'id': 177,
  'name': 'Da_Da_Da_Nyet',
  'all_chat': True,
  'label': 'Да? Да? Да? Нет.',
  'message': 'Да? Да? Да? Нет.',
  'sound_ext': 'wav'},
 '178': {'id': 178,
  'name': 'Wot_Eto_Bru',
  'label': 'Вот Это Врыв!',
  'message': 'Вот Это Врыв!',
  'sound_ext': 'wav'},
 '179': {'id': 179,
  'name': 'Kreasa_Kreasa',
  'label': 'Резать Резать Резать Резать',
  'message': 'Резать Резать Резать Резать',
  'sound_ext': 'wav'},
 '180': {'id': 180,
  'name': 'Eto_Nenormalno',
  'label': 'Это ненормально, это нечестно!',
  'message': 'Это ненормально, это нечестно!',
  'sound_ext': 'wav'},
 '181': {'id': 181,
  'name': 'Krasavchik',
  'label': 'Красавчик!',
  'message': 'Красавчик!',
  'sound_ext': 'wav'},
 '182': {'id': 182,
  'name': 'Eto_Prosto_Netchto',
  'all_chat': True,
  'label': 'Это. Просто. Нечто.',
  'message': 'Это. Просто. Нечто.',
  'sound_ext': 'wav'},
 '183': {'id': 183,
  'name': 'Zhil_Do_Konsta',
  'label': 'Как Герой',
  'message': 'Жил до конца, умер как герой',
  'sound_ext': 'wav'},
 '190': {'id': 190,
  'name': 'Goodness_Gracious',
  'all_chat': True,
  'label': 'Goodness Gracious',
  'message': 'Sir Chief. Goodness Gracious Papable.',
  'sound_ext': 'wav'},
 '191': {'id': 191,
  'name': 'Nakupuuu',
  'all_chat': True,
  'label': 'NAKUPUU',
  'message': 'NAKUPUU',
  'sound_ext': 'wav'},
 '192': {'id': 192,
  'name': 'Whats_Cooking',
  'all_chat': True,
  'label': "What's Cooking",
  'message': "You know what's cooking? BOOM!",
  'sound_ext': 'wav'},
 '193': {'id': 193,
  'name': 'Eughahaha_Aah_Ha_Ha_Ha_Ha',
  'all_chat': True,
  'label': 'Eughahaha Aah Ha Ha Ha Ha',
  'message': 'Eughahaha Aah Ha Ha Ha Ha',
  'sound_ext': 'wav'},
 '194': {'id': 194,
  'name': 'TI9_GlaDOS_Estimate_99',
  'all_chat': True,
  'label': '99% Probability of Winning.',
  'message': '99% Probability of Winning.',
  'sound_ext': 'wav'},
 '195': {'id': 195,
  'name': 'TI9_GlaDOS_Disappointed',
  'label': "I'm Just Disappointed",
  'message': "I'm not angry, I'm Just Disappointed",
  'sound_ext': 'wav'},
 '196': {'id': 196,
  'name': 'TI9_GlaDOS_Estimate_1',
  'all_chat': True,
  'label': '1% Probability of Winning.',
  'message': '1% Probability of Winning.',
  'sound_ext': 'wav'},
 '197': {'id': 197,
  'name': 'TI9_GlaDOS_Estimate_17',
  'all_chat': True,
  'label': '17% Probability of Winning.',
  'message': '17% Probability of Winning.',
  'sound_ext': 'wav'},
 '199': {'id': 199,
  'name': 'TI9_GlaDOS_Excellent_Work',
  'all_chat': True,
  'label': 'Excellent Work',
  'message': 'Once again, excellent work',
  'sound_ext': 'wav'},
 '200': {'id': 200,
  'name': 'TI9_GlaDOS_The_Point',
  'all_chat': True,
  'label': 'The Point',
  'message': "I'm not sure what the point of that was",
  'sound_ext': 'wav'},
 '202': {'id': 202,
  'name': 'Commend_This_Man',
  'label': 'Commend this man',
  'message': 'Commend this man, immediately.',
  'sound_ext': 'wav'},
 '203': {'id': 203,
  'name': 'Slacks_OMG',
  'all_chat': True,
  'label': 'Oh My God',
  'message': 'Oh My God! Never in all my years as a caster',
  'sound_ext': 'wav'},
 '204': {'id': 204,
  'name': 'TI9_GlaDOS_That_Happened',
  'all_chat': True,
  'label': 'That Just Happened',
  'message': 'That Just Happened',
  'sound_ext': 'wav'},
 '211': {'id': 211,
  'name': 'Ni_Qi_Bu_Qi',
  'all_chat': True,
  'label': '你气不气?',
  'message': '你气不气?',
  'sound_ext': 'wav'},
 '212': {'id': 212,
  'name': 'Zai_Jian_Le_Bao_Bei',
  'all_chat': True,

In [ ]:
def parsear_partida(match_id):
  job = realiza_request(f"https://api.opendota.com/api/request/{match_id}", method='post')
  jobId = job['job']['jobId']
  acabou = realiza_request(f"https://api.opendota.com/api/request/{jobId}")
  return acabou

In [ ]:
parsear_partida(8840133635)

{'id': 362558313,
 'type': 'parse',
 'timestamp': '2026-06-07T18:49:09.357Z',
 'attempts': 1,
 'data': {'match_id': 8840133635},
 'next_attempt_time': '2026-06-07T18:49:09.357Z',
 'priority': -2,
 'job_key': 'parse:8840133635',
 'jobId': 362558313}

In [ ]:
parsear_partida(8840152578)

{'id': 362558326,
 'type': 'parse',
 'timestamp': '2026-06-07T18:49:11.657Z',
 'attempts': 1,
 'data': {'match_id': 8840152578},
 'next_attempt_time': '2026-06-07T18:49:11.657Z',
 'priority': -2,
 'job_key': 'parse:8840152578',
 'jobId': 362558326}

In [ ]:
teste = constants("ability_ids")

In [ ]:
buscar_chat_partida(8840133635)

Buscando detalhes da partida 8840133635...

['[00:22] Jogador 128: 14010',
 '[00:24] Jogador 131: 10001',
 '[01:27] Jogador 128: 11',
 '[01:37] Jogador 2: 30001',
 '[02:02] Jogador 3: 1',
 '[03:06] Jogador 131: 10003',
 '[03:10] Jogador 3: 595',
 '[04:07] Jogador 128: 11',
 '[04:32] Jogador 132: 71',
 '[05:19] Jogador 128: 11',
 '[05:54] Jogador 131: 10003',
 '[06:42] Jogador 130: 4',
 '[06:44] Jogador 130: 3',
 '[07:14] Jogador 128: 14010',
 '[07:15] Jogador 128: 14011',
 '[08:46] Jogador 131: 10004',
 '[09:38] Jogador 128: 14010',
 '[09:41] Jogador 131: 10001',
 '[14:37] Jogador 3: 7',
 '[14:39] Jogador 3: 401304',
 '[16:17] Jogador 2: 62',
 '[16:33] Jogador 2: 66',
 '[17:20] Jogador 4: 71',
 '[18:48] Jogador 128: 1',
 '[22:27] Jogador 130: 128001',
 '[23:30] Jogador 131: 10003',
 '[26:30] Jogador 2: 30001',
 '[26:32] Jogador 2: 30004',
 '[26:56] Jogador 128: 14010',
 '[28:18] Jogador 128: 14010',
 '[28:50] Jogador 128: 14010',
 '[28:54] Jogador 130: 128002',
 '[28:58] Jogador 132: GG']